### PR TITLE
Fixes for PAYARA-677

### PR DESCRIPTION
**Pull request by lprimak**
Fixed a small issue with META-INF/services processing that may make the fix incompatible with previous versions in the default configuration under rare circumstances

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins please test

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
failed the first test due to a missing dependency, should work this time

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
ran tests manually and they passed, so merging

**Pull request merged**
