### PR TITLE
APPSERV-112 Upgrade H2DB to version 1.4.200

### PR DESCRIPTION
**Pull request by Cousjava**
# Description
This is a component upgrade

# Important Info

This is a breaking change, by adding a password to the default database.

### Blockers
Depends on Payara/Payara_PatchedProjects#300

# Testing

### Testing Performed
- JavaEE7 Samples

### Testing Environment
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.0"

### CODE REVIEW

**Comment by jbee** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Does not pass quicklook locally still.

**Pull request closed without merging**
