### PR TITLE
PAYARA-2723 Update Hazelcast to 3.10.2 - Payara 4

### PR DESCRIPTION
**Pull request by lprimak**

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins quick test payara 4 jdk7

**Comment by lprimak** [comment]
jenkins quick test payara 4 jdk7

**Comment by arjantijms** [comment]
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007fbf2cca59f1, pid=22813, tid=140458865313536
> #
> # JRE version: OpenJDK Runtime Environment (7.0_181-b01) (build 1.7.0_181-b01)
> # Java VM: OpenJDK 64-Bit Server VM (24.181-b01 mixed mode linux-amd64 compressed oops)
> # Problematic frame:
> # V  [libjvm.so+0x4b89f1]  ClassHierarchyWalker::is_witness(klassOopDesc*)+0x101
> #
> # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> #
> # An error report file with more information is saved as:
> # /JenkinsWorkspace/JenkinsJobs/PayaraQuickBuildTest-JDK7/hs_err_pid22813.log
> #
> # If you would like to submit a bug report, please visit:
> #   http://www.azulsystems.com/support/
> #
> runTests.sh: line 925: 22813 Aborted                 (core dumped) mvn clean test -U -Dglassfish.home="$PAYARA_HOME/glassfish" -fae -f "$PAYARA_SOURCE/appserver/tests/quicklook/pom.xml"
> CLI306: Warning - The server located at /JenkinsWorkspace/JenkinsJobs/PayaraQuickBuild-JDK7/appserver/distributions/payara/target/stage/payara41/glassfish/domains/test-domain i

**Comment by lprimak** [comment]
jenkins quick test payara 4

**Comment by lprimak** [comment]
jenkins quick test payara 4

**Comment by arjantijms** [comment]
jenkins quick test payara 4 jdk7

**Comment by lprimak** [comment]
jenkins quick test payara 4

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Pull request merged**
