### PR TITLE
Master merge 2017-12-11

### PR DESCRIPTION
**Pull request by Pandrex247**
Merge of master from roughly the 174 release.

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Issues with fault tolerance

**Pull request closed without merging**
