### PR TITLE
Production Payara domain enhancements - PAYARA-846

### PR DESCRIPTION
**Pull request by lprimak**

### CODE REVIEW

**Comment by ggam** [comment]
What about enabling Hazelcast by default?

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
@ggam I am not sure, I will pose the question to the rest of the team

**Comment by ggam** [comment]
@lprimak it is one of Payara killer features. What are the objections there?

**Comment by lprimak** [comment]
@ggam It's just a big step and I want other team members to chime in first, that's all.
I personally think it's a good idea.

**Comment by lprimak** [comment]
Also, it drags in a few more questions, like,
- do we switch default session replication to hazelcast?
- there is also new feature about EJB timers stored in hazelcast, do we enable that?

It's not quite as trivial as it seems at first glance

**Comment by smillidge** [comment]
I think a new config within the payaradomain is a good idea. hz-cluster-config or something like that?

**Comment by pdudits** [comment]
I think enabling hazelcast with its default multicast discovery would be quite dangerous production setting. Hazelcast themselves recommend TCP-IP joiners for production.

**Comment by lprimak** [comment]
I think given all the comments, this deserves some discussion, and probably a separate issue,
instead of shoehorning it into this issue.

**Comment by ggam** [comment]
@lprimak I'll create another issue for that.

Another possible production improvement: enable precompilation of jsp by default.

Btw a development configuration would also ve nice.

**Comment by ggam** [comment]
Another one I just found: when creating a new data source, enable ping by default

**Comment by lprimak** [comment]
@ggam Unfortunately, your above comments would not be in scope for this enhancement.  This deals with application deployment and are not part of the domain creation

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Pull request merged**
