### PR TITLE
FISH-5806: removing jobManager service and some references

### PR DESCRIPTION
**Pull request by breakponchito**
FISH-5806 Remove JobManager functionality that is not relevant for Payara Server and is causing issues when replicating the issue from the following ticket: [FISH-5806](https://payara.atlassian.net/browse/FISH-5806)
## Description

This is a bug fix to remove JobManager functionality that is not relevant for the Payara Server implementation since it was identified 
is not really used and is causing issues when trying to start server after replicating issue from following ticket: [FISH-5806](https://payara.atlassian.net/browse/FISH-5806)
### Testing Performed

local testing with the reproducer attached on the ticket [FISH-5806](https://payara.atlassian.net/browse/FISH-5806)
now the server restarts well after the deployment group cause the issue of the blocking port:
`
[#|2022-10-12T18:38:39.457-0500|INFO|Payara 5.2022.4-SNAPSHOT|javax.enterprise.web|_ThreadID=161;_ThreadName=Thread-14;_TimeMillis=1665617919457;_LevelValue=800;_MessageID=AS-WEB-GLUE-00200;|
  Created virtual server server|#]

[#|2022-10-12T18:38:39.458-0500|INFO|Payara 5.2022.4-SNAPSHOT|javax.enterprise.web|_ThreadID=161;_ThreadName=Thread-14;_TimeMillis=1665617919458;_LevelValue=800;_MessageID=AS-WEB-GLUE-00200;|
  Created virtual server __asadmin|#]

[#|2022-10-12T18:38:39.583-0500|INFO|Payara 5.2022.4-SNAPSHOT|javax.enterprise.web|_ThreadID=161;_ThreadName=Thread-14;_TimeMillis=1665617919583;_LevelValue=800;_MessageID=AS-WEB-GLUE-00201;|
  Virtual server server loaded default web module |#]

[#|2022-10-12T18:38:40.098-0500|INFO|Payara 5.2022.4-SNAPSHOT|javax.enterprise.system.core|_ThreadID=161;_ThreadName=Thread-14;_TimeMillis=1665617920098;_LevelValue=800;_MessageID=NCLS-CORE-00022;|
  Loading application __admingui done in 1,249 ms|#]

[#|2022-10-12T18:38:40.704-0500|INFO|Payara 5.2022.4-SNAPSHOT|javax.enterprise.resource.webcontainer.jsf.config|_ThreadID=161;_ThreadName=Thread-14;_TimeMillis=1665617920704;_LevelValue=800;_MessageID=jsf.config.listener.version;|
  Initializing Mojarra |version.string| for context ''|#]

[#|2022-10-12T18:38:41.320-0500|INFO|Payara 5.2022.4-SNAPSHOT|javax.enterprise.web|_ThreadID=161;_ThreadName=Thread-14;_TimeMillis=1665617921320;_LevelValue=800;_MessageID=AS-WEB-GLUE-00172;|
  Loading application [__admingui] at [/]|#]
`
We can't see any UnmarshalException trying to read jobs.xml file with the invalid characters
### Testing Environment

Ubuntu 20.04, Azul JDK 8

### CODE REVIEW

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by luiseufrasio — APPROVED** [review]
LGTM!

**Pull request merged**
