### PR TITLE
PAYARA-3004 Configure virtual servers for MP endpoints (Payara 4.x)

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 please

**Comment by Pandrex247** [comment]
Confirmed to break on my local machine on the same test.

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by jGauravGupta** [comment]
Thanks @Pandrex247

**Pull request merged**
