### PR TITLE
Fixing sonar blocker bugs with class CircuitBreakerState

### PR DESCRIPTION
**Pull request by svendiedrichsen**
1) Usage of wrong operator =+ when += is meant (or are they really?)
2) Usage of volatile field with non-atomic operations replaced with usage of Atomics
3) Update of copyright year

https://sonarcloud.io/code?id=org.glassfish.main%3Aglassfish-main-aggregator&selected=fish.payara.microprofile.fault-tolerance%3Amicroprofile-fault-tolerance%3Asrc%2Fmain%2Fjava%2Ffish%2Fpayara%2Fmicroprofile%2Ffaulttolerance%2Fstate%2FCircuitBreakerState.java

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
This class also has a problem with daylight savings time switches because it works based on nanos as long values. It should work with `ZonedDateTime` instead.

**Comment by smillidge** [comment]
This will need running through the FT TCK

**Comment by arjantijms** [comment]
@MeroRai TCK testing internally tracked by PAYARA-3210

**Comment by MeroRai** [comment]
Passed the MicroProfile Fault-Tolerance TCK

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
It built for me locally, clearly Jenkins is borked somehow. I'll have a look.

**Comment by Pandrex247** [comment]
New Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
