### PR TITLE
FISH-6034 Rework Eclipse Transformer Integration into an Extension

### PR DESCRIPTION
**Pull request by Pandrex247**
## Description
Reworks the Payara Jakarta EE Eclipse Transformer integration into an extension, loaded via ServiceLoader.

### Blockers
PR to create API and Implementation extensions: https://github.com/payara/transformer/pull/26
Release of API.

### New tests
None

### Testing Performed
Ran `simple-servlet` servlet test of Java EE 7 samples (_Payara6_ branch):
* Without extension implementation - passed
* With extension implementation - passed
* With extension implementation and `fish.payara.deployment.transform.namespace=true` - passed
* With extension implementation and `fish.payara.deployment.transform.namespace=false` - passed

Ran `simple-servlet` servlet test of Java EE 7 samples (_master_ branch):
* Without extension implementation - failed (expected)
* With extension implementation - passed
* With extension implementation and `fish.payara.deployment.transform.namespace=true` - passed
* With extension implementation and `fish.payara.deployment.transform.namespace=false` - failed (expected)

### Testing Environment
Windows 10, Zulu JDK 8

## Documentation
https://github.com/payara/Payara-Community-Documentation/pull/313

## Notes for Reviewers
To review:
* Build the `internal-api` and install it into your local maven repo
* Check out the [deployment-transformer-1.0 tag](https://github.com/payara/transformer/releases/tag/deployment-transformer-1.0) and build it using JDK 11.
* Build Payara Server
* Add the `deployment-transformer-impl` extension to `payara6/glassfish/modules`

### CODE REVIEW

**Review by aubi — APPROVED** [review]
LGTM

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
