### PR TITLE
FISH-8142 Upgrade Mojarra to 4.0.7 with Patches Reapplied

### PR DESCRIPTION
**Pull request by Pandrex247**
## Description
Upgrades Mojarra to 4.0.7 with patches reapplied.

### Blockers
Merge of patched project PR, and release of patched artefact.
https://github.com/payara/patched-src-mojarra/pull/22

### New tests
None

### Testing Performed
Started the admin console and clicked around - nothing obviously broken.

### Testing Environment
Windows 11, Java 11.

## Documentation
N/A

## Notes for Reviewers
None

### CODE REVIEW

**Comment by Pandrex247** [comment]
Successful run here: https://jenkins.payara.fish/blue/organizations/jenkins/Payara%20Community%20PR%20Testing/detail/PR-6825/1/pipeline

**Comment by JamesHillyard** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Pull request merged**
