### PR TITLE
PAYARA-2425 Added Environment substitution for JVM options

### PR DESCRIPTION
**Pull request by Cousjava**

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
@Pandrex247 The regular expression is just copied from TranslatedConfigView, I didn't come up with it

**Comment by andyfcdl** [comment]
Was the System.out.println left in on purpose? Should it be a debug logging statement, or removed?

**Comment by Cousjava** [comment]
@andyfcdl it was removed in #2560

**Pull request merged**
