### PR TITLE
FISH-8044 Avoid crashing due to FileSystemNotFound while behind a Spring boot

### PR DESCRIPTION
**Pull request by ctabin**
Hi,

We are using payara-embedded-all to deploy our application. This dependency (among) other are (re-)packaged in an überjar for the delivery.
While making some test to migrate from this überjar to spring boot, we hit the exception below while deploying our app with
```java
Deployer earDeployer = glassfish.getDeployer();
earDeployer.deploy("myFile.ear");
```

This is because the URIs returned are pointing to internal jar (and hence starting with `jar:<path>` (for instance `jar:file:/path/to/app-spring-boot.jar!/BOOT-INF/lib/mylib-1.0.0.jar!/`). So, I suggest to simply ignore those in this case.

Here is the stacktrace that this PR intended to fix.
```
SEVERE: Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException
        at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:188)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:1255)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:514)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:570)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:131)
        at ...
Caused by: java.lang.RuntimeException
        at org.glassfish.javaee.core.deployment.JavaEEDeployer.prepare(JavaEEDeployer.java:228)
        at org.glassfish.ejb.startup.EjbDeployer.prepare(EjbDeployer.java:232)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:1255)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepareBundle(EarDeployer.java:301)
        at org.glassfish.javaee.full.deployment.EarDeployer.lambda$prepare$0(EarDeployer.java:164)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnBundles(EarDeployer.java:221)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllTypedBundles(EarDeployer.java:233)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllBundles(EarDeployer.java:259)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:162)
        ... 23 more
Caused by: java.nio.file.FileSystemNotFoundException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
        at java.base/java.nio.file.Path.of(Path.java:209)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at org.glassfish.loader.util.ASClassLoaderUtil.getModulesClasspath(ASClassLoaderUtil.java:275)
        at org.glassfish.loader.util.ASClassLoaderUtil.getModuleClassPath(ASClassLoaderUtil.java:120)
        at org.glassfish.loader.util.ASClassLoaderUtil.getModuleClassPath(ASClassLoaderUtil.java:146)
        at org.glassfish.javaee.core.deployment.JavaEEDeployer.getModuleClassPath(JavaEEDeployer.java:116)
        at org.glassfish.ejb.startup.EjbDeployer.generateArtifacts(EjbDeployer.java:427)
        at org.glassfish.javaee.core.deployment.JavaEEDeployer.prepare(JavaEEDeployer.java:223)
```

We are using payara-embedded-all 6.2023.9 with JDK17 and Spring boot 3.1.4.

### CODE REVIEW

**Comment by ctabin** [comment]
Jenkins test please

**Review by luiseufrasio — CHANGES_REQUESTED** [review]
@ctabin Could you please provide the Spring boot app and the EAR file you used to reproduce it?

**Comment by ctabin** [comment]
@luiseufrasio I'll provide a test case asap.

**Comment by ctabin** [comment]
@luiseufrasio Please find a reproducer [here](https://github.com/ctabin/gf-test-spring). As stated in the README, it seems that with the latest version of `spring-boot-maven-plugin` (3.2.2), the issue does not appear anymore.

**Review by luiseufrasio — APPROVED** [review]
LGTM!

**Pull request merged**
