### PR TITLE
CUSTCOM-260 Fixed possible deadlock in StandardSession

### PR DESCRIPTION
**Pull request by sgflt**
# Description
This is a bug fix of deadlock described in #4281 

I could not create simple reproducer because race conditions are hard to reproduce. 
EDIT dmatej: the possible deadlock is well visible from sources.

# Notes for Reviewers
Reviewer should proove that the cycle between classes existed in previous version and now is fixed correctly.

@dmatej

### CODE REVIEW

**Comment by rdebusscher** [comment]
@sgflt  We are awaiting the signed CLA (https://github.com/payara/Payara/blob/master/PayaraCLA.pdf) otherwise we need to close this PR.

**Comment by sgflt** [comment]
CLA on the way :)

**Comment by smillidge** [comment]
We've got the CLA

**Comment by dmatej** [comment]
Jenkins test please

**Pull request merged**
