### PR TITLE
QACI-158 Fixed windows line endings in all bat files

### PR DESCRIPTION
**Pull request by dmatej**
# Description

Fixes problems with changing branches, cherrypicks and rebases

### CODE REVIEW

**Comment by dmatej** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
A find on Payara directrory yields 28 results. Why aren't the other 15 in here?

**Comment by dmatej** [comment]
> Disputed that all .bats have been done. See conversation

I don't see any problem in other than these, so they don't need any change.
Did you find any bat file with incorrect line endings? What command did you use to find it?

**Comment by dmatej** [comment]
I made it a global rule and fixed remaining bat files with this command:
`find . -type f -name "*.bat" -print0 | xargs -0 unix2dos`
I did not change .gitattributes files updated by @pdudits , because they enforce unix line endings in their subdirs, but we don't have such global rule, because it could result in much more changes and cause problems.

**Comment by dmatej** [comment]
Jenkins test please

**Pull request merged**
