### PR TITLE
Revert "[FISH-387] Don't check client certificates by default - fails…

### PR DESCRIPTION
**Pull request by cubastanley**
Title

### CODE REVIEW

**Comment by cubastanley** [comment]
Jenkins test please

**Review by kalinchan — APPROVED** [review]

**Comment by Pandrex247** [comment]
Does https://github.com/payara/Payara/pull/5241 not also need to come out?

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Does https://github.com/payara/Payara/pull/5241 not also need to come out?

**Comment by cubastanley** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Comment by cubastanley** [comment]
Jenkins test please

**Comment by cubastanley** [comment]
Jenkins test please

**Pull request merged**
