### PR TITLE
FISH-459 Cleanup of sonar warnings in jdbc40 module

### PR DESCRIPTION
**Pull request by Cousjava**
## Description
This is a code cleanup.

### Testing Performed
- JavaEE7Samples

### Testing Environment
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3

## Notes for Reviewers
This adds in a bunch of `@Override`s and fixes some javadoc errors

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Review by MattGill98 — APPROVED** [review]
LGTM - can't see any functional changes

**Pull request merged**
