### PR TITLE
PAYARA-999 CDI scanning

### PR DESCRIPTION
**Pull request by lprimak**
CDI scanning configuration improvements

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by smillidge** [comment]
@lprimak can you resolve the conflicts

**Comment by lprimak** [comment]
@smillidge will do

**Comment by lprimak** [comment]
@smillidge done

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Pull request merged**
