### PR TITLE
PAYARA-1265-Create-asadmin-command-for-Slack-notifier

### PR DESCRIPTION
**Pull request by mulderbaba**
also contains asadmin commands for email, eventbus, hipchat, log, jms and xmpp notifiers

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Pull request merged**
