### PR TITLE
[PAYARA-3965] - Updated all admin console graphics

### PR DESCRIPTION
**Pull request by cubastanley**
Okay! So this PR does the following things in the Admin Console:

1. Updates the name of the new image file (to prevent caching issues)
2. Updates the console shutdown screen to use the new logo
3. Updates the "Console Loading" screen to use the new logo and colours
4. Resolves all issues with invisible blue text in the console (finally!)

Would be worth pulling the changes and doing a proper go over to make sure everything is behaving as described - there was an issue with the original PR for this that pulled in a whole bunch of commits from elsewhere in the codebase so I'm not 100% confident that the PR has everything included but it should do

### CODE REVIEW

**Comment by cubastanley** [comment]
Jenkins test please

**Comment by cubastanley** [comment]
Jenkins test pleaseeee

**Comment by cubastanley** [comment]
Jenkins Test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
