### PR TITLE
FISH-230: specify certificate alias for MP rest client and MP config

### PR DESCRIPTION
**Pull request by breakponchito**
## Description

Adding support for custom configuration of sslContext using certificate alias property
### Testing Performed

unit test and manual test documented here: (pending documentation and update of the wiki about design)
I added mock testing for the class
### Testing Environment

Windows 10, JDK 8
## Documentation

Pending documentation on the wiki page for the user view section: https://payara.atlassian.net/wiki/spaces/PAYAR/pages/3033006087/Feature+Design+-+Provide+Means+to+Specify+a+Certificate+Alias+for+JAX-RS+and+MP+REST+Client

### CODE REVIEW

**Comment by breakponchito** [comment]
Jenkins test

**Comment by breakponchito** [comment]
Jenkins test

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test

**Comment by breakponchito** [comment]
Jenkins test

**Comment by breakponchito** [comment]
Jenkins test

**Comment by breakponchito** [comment]
Jenkins test

**Comment by breakponchito** [comment]
Jenkins test

**Comment by breakponchito** [comment]
Jenkins test

**Pull request merged**
