### PR TITLE
refactored asm-all dependency to asm-all-repackaged

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by smillidge** [comment]
Does it fix the lambda bug?

**Comment by smillidge** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
yes Steve, I also tried with lambda-web-demo provided by zappee. 

I replaced all org.glassfish.external:asm-all:3.3 dependencies with org.glassfish.hk2.external:asm-all-repackaged:hk2_version, which is a repackaging of asm-all 5.0.3 in the background. I refactored all org.objectweb.asm.* imports to org.glassfish.hk2.external.org.objectweb.asm.*. The interfaces that were turned into abstract classes are now being extended. Since those abstract classes don't have any default constructors I added the call super(Opcodes.ASM5); to the constructor of the classes that extend those abstract classes. I removed the class EmptyVisitor, the open source projects that were upgraded from ASM 3.x to ASM 5.x had the same approach. Instead of the EmptyVisitor I introduced the regarding visitor, such as MethodVisitor. I removed the dependency auto-depends, since it was introducing asm-all transitively. Instead of it I used the dependency hk2-junitrunner where it provides a newer version for HK2Runner. It's a not JUnit Runner extension anymore so I introduced it in the class hierarchy as a super class to ConfigApiTest.

**Comment by smillidge** [comment]
Fixes #647

**Comment by smillidge** [comment]
jenkins test please

**Pull request merged**
