### PR TITLE
PAYARA-845 Add option to disable the Server Header

### PR DESCRIPTION
**Pull request by MeroRai**

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Pull request merged**
