### PR TITLE
PAYARA-1114 distributed deadlock in JTA - TestSuite (PR-1146)

### PR DESCRIPTION
**Pull request by jGauravGupta**
TestSuite for Pull Request https://github.com/payara/Payara/pull/1146 distributed deadlock in JTA

### CODE REVIEW

**Comment by lprimak** [comment]
This is awesome, thanks Gaurav!

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
Fantastic.  Test failed

**Comment by jGauravGupta** [comment]
@lprimak, oh sorry, I missed the portion copyright.
Jenkins tests will pass with PR-1146 changes.

**Comment by OndrejM** [comment]
@jGauravGupta, would you please sign our [contributor's agrement](https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md) so that we may accept your code, if you haven't done so?

**Comment by jGauravGupta** [comment]
Signed :)

**Comment by lprimak** [comment]
depends on #1146

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Pull request merged**
