### PR TITLE
PAYARA-2879-Remove-JDK8-specific-jvmOption-UseStringDeduplication - Payara4

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 4 JDK7

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 4 JDK7

**Comment by lprimak** [comment]
jenkins quick test payara 4 jdk7

**Comment by arjantijms** [comment]
> Running org.javaee7.batch.batchlet.simple.MyBatchletTest
> Jun 22, 2018 9:02:32 PM fish.payara.arquillian.container.payara.CommonPayaraManager start
> SEVERE: Could not connect to DAS on: http://localhost:4848 | Connection refused (Connection refused)
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.894 sec <<< FAILURE! - in org.javaee7.batch.batchlet.simple.MyBatchletTest
> org.javaee7.batch.batchlet.simple.MyBatchletTest  Time elapsed: 1.893 sec  <<< ERROR!
> org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not connect to DAS on: http://localhost:4848 | Connection refused (Connection refused)

**Comment by arjantijms** [comment]
jenkins quick test payara 4 jdk7

**Comment by arjantijms** [comment]
jenkins quick test payara 4

**Comment by arjantijms** [comment]
jenkins quick test payara 4 jdk7

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 4 JDK7

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 4 JDK7

**Comment by Pandrex247** [comment]
jenkins quick test payara 4 jdk7

**Pull request merged**
