### PR TITLE
PAYARA-2479 PAYARA-3118 MP health check checker - Payara4

### PR DESCRIPTION
**Pull request by Cousjava**
PAYARA-2479 PAYARA-3118 MP health check checker

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Cousjava** [comment]
@Pandrex247 pulled in that PR

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Pull request merged**
