### PR TITLE
PAYARA-1866 Update Soteria version

### PR DESCRIPTION
**Pull request by Pandrex247**
This compiles on my local machine, but I don't know if this is the correct artefact - I can't find any copies of org.glassfish.soteria:soteria to compare it against.
@arjantijms do you know? Did they rename the Soteria artefact?

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins, quick test JDK8 please

**Comment by Pandrex247** [comment]
A comparison against the _1.0-m01_ version still available on [bintray](http://search.maven.org/remotecontent?filepath=org/glassfish/soteria/javax.security.enterprise/1.0-b07/javax.security.enterprise-1.0-b07.jar) would lead me to believe that this is the correct artifactId

**Comment by Pandrex247** [comment]
Ah, looks like we need a new build job to account for Payara 5.

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Needs #1780 before it'll pass the quicklook tests.
Also looks like CDI is throwing a major wobbly.

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by michaelranaldo** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Doesn't seem to have been a one-off - CDI looks quite broken.

**Pull request closed without merging**
