### PR TITLE
PAYARA-3477-Upgrade-Eclipselink-to-2.7.4

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by mulderbaba** [comment]
jenkins test

**Comment by mulderbaba** [comment]
> I'm not convinced they were and that the previous upgrade to vanilla 2.7.3 was also incorrect.

@Pandrex247 I only checked one version before, ok make sense, time to dig down the parchments to find out what's in or not.

**Comment by mulderbaba** [comment]
jenkins test

**Comment by mulderbaba** [comment]
jenkins test

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
