### PR TITLE
PAYARA-488 Add a message to the admin console warning against using the restart button if running Payara as a service.

### PR DESCRIPTION
**Pull request by MeroRai**

### CODE REVIEW

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Pull request merged**
