### PR TITLE
Payara 1985 Change Payara 5 Installation Folder

### PR DESCRIPTION
**Pull request by MattGill98**
Updated install folder to exclude minor version number

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins quick test payara 5 please

**Comment by MattGill98** [comment]
Payara Tests won't pass until merge of PR https://github.com/payara/PayaraTests/pull/12

**Comment by MattGill98** [comment]
jenkins quick test payara 5 please

**Comment by michaelranaldo** [comment]
Jenkins quick test Payara 5 please

**Comment by MattGill98** [comment]
Jenkins quick test Payara 5 please

**Pull request merged**
