### PR TITLE
PAYARA-2401-Integrate-Weld-3.0.2.Final-into-Payara-5

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins quick test payara 5 please

**Comment by arjantijms** [comment]
jenkins quick test payara 5 please

**Comment by mulderbaba** [comment]
jenkins quick test payara 5 please

**Comment by mulderbaba** [comment]
jenkins quick test payara 5 please

**Comment by arjantijms** [comment]
jenkins quick test payara 5 please

**Pull request merged**
