### PR TITLE
PAYARA-2764 Translate Payara only feature to Japanese

### PR DESCRIPTION
**Pull request by khasunuma**

### CODE REVIEW

**Comment by khasunuma** [comment]
I consider alternative some plans regarding to this issue as follows:

1. Reduce the resource bundle - Remove l10n resources without Japanese. (Probably, it works well)
2. Divide the pull request - DD/DG (required) and Other features (Optional)

Introducing new l10n features required to create new many l10n modules. So the PR becomes often too large size. I think it's better that this PR should be divided to several PRs now.

Please let me know your suggestion about this PR. Then, I'll once withdraw the PR and create several PRs instead of this.

**Comment by khasunuma** [comment]
I removed l10n resources without Japanese. Currently there are ja_JP resources into new modules.

**Comment by MeroRai** [comment]
@khasunuma, forgot to mention, everything looks good on the admin console.

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Pull request merged**
