### PR TITLE
PAYARA-1738 Some minor refactoring

### PR DESCRIPTION
**Pull request by arjantijms**

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins, would you kindly?

**Comment by arjantijms** [comment]
This was intended as preparation to accept reflective calls via a Method instance obtained from a MDB proxy (as JBoss supports), but now I think we should just adjust the client code to obtain the Method instance from the Bean Class. Not 100% sure what the spec requires, will try to ask this on the JMS and EJB lists, but those EGs are not active currently.

Did some refactoring before that, and didn't want to waste them.

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
Should this be merged?

**Pull request merged**
