### PR TITLE
PAYARA-3994 HotDeploy initial support in deploy/redeploy asadmin command

### PR DESCRIPTION
**Pull request by jGauravGupta**
New `-hotDeploy` flag added to `deploy`/`redeploy` asadmin command intended for machine-to-machine communication (IDE, build tools etc).

Currently, HotDeploy features are:
- Skips un-deployment of existing application 
- Skips writing application properties to domain.xml
- Reuse existing Module to deploy the application

**Apache NetBeans IDE client:**
https://github.com/apache/netbeans/pull/1562

How to enable and test HotReload in the NetBeans IDE:

- Build the IDE: `ant -Dcluster.config=enterprise`
- Run the IDE: `ant tryme`
- Add the Payara Server in IDE.
- Open the properties of Payara Server and enable the `Hot Reload` checkbox.HotReload
- Create a new Maven web application and deploy it to the Payara Server.
- Create or modify any Servlet and refresh the browser to test.

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by MattGill98** [comment]
Not sure if I'm doing something wrong, but when using a metrics application I get: 

~~~
Error invoking ServletContainerInitializer fish.payara.microprofile.metrics.rest.MetricsServletContainerInitializer
java.lang.IllegalStateException: Wrapper already initialized with servlet instance, class, or name
	at org.apache.catalina.core.StandardWrapper.setServletClass(StandardWrapper.java:719)
~~~

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Thanks @MattGill98, Fixed the dynamically registered Servlet/Filter(s).

**Comment by pdudits** [comment]
On Windows I'm constantly hitting `.jar` file locks when redeploying, which might be caused by skipping undeployment step.

I also think that `--hotDeploy` should imply `--force` because it always is a redeploy.

**Comment by jGauravGupta** [comment]
Hi @pdudits,

I am also developing on Windows but not found the locking issue tested war via manual asadmin command and exploded war via NetBeans IDE plugin.

The `-force` flag is by default enabled on the invocation of `redeploy` asadmin command.

https://github.com/payara/Payara/blob/70e98fbe94cd3bb72b4e1b6f88f87f9eedab459e/nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/ReDeployCommand.java#L128

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
It was just my build :) Works after a rebuild.

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by MeroRai** [comment]
@jGauravGupta and @pdudits, I haven't tested it on Windows and have not encountered the file locking issue.

**Pull request merged**
