### PR TITLE
PAYARA-3391 Upgrade maven-jar-plugin to 3.1.1 (Payara 4.x)

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
> You are using 'useDefaultManifestFile' which has been removed from the maven-jar-plugin.

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Pull request merged**
