### PR TITLE
PAYARA-2027 MicroProfile Metrics implementation (Payara-5)

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins quick test payara 5 please

**Comment by jGauravGupta** [comment]
jenkins quick test payara 5 please

**Comment by jGauravGupta** [comment]
jenkins quick test payara 5 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
