### PR TITLE
FISH-6495 : verifying if property was passed

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
A customer would like to provide a path to a hazelcast configuration file when using Payara Embedded with Arquillian.

### New tests
None

### Testing Performed
1. Download the attached reproducer application & hazelcast-config.xml
2. Modify the embedded arquillian configuration in arquillian.xml to specify a path to the hazelcast-text.xml file:
    <?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian
                http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="payara-embedded" default="true">
        <configuration>
            <property name="bindHttpPort">9990</property>
            <property name="hazelcastConfigurationFile">C:/Users/luise/Downloads/hazelcast-test.xml</property>
        </configuration>
    </container>
</arquillian>
3. Run the test with mvn clean install and the test should pass

### Testing Environment
Zulu JDK 1.8_212 on Windows 10 with Maven 3.8.4

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — COMMENTED** [review]
Eyeballing it: LGTM

Needs portions copyright however.

**Comment by luiseufrasio** [comment]
> Eyeballing it: LGTM
> 
> Needs portions copyright however.

done

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Tested against the `ejb30/lite/appexception` TCK tests and that now passes, however the original reproducer attached to FISH-6495 (as described in the PR description) doesn't seem to work?

It continues to bind to port 4900

**Comment by luiseufrasio** [comment]
> 6495

It's because the original arquillian.xml file does not contain this property: 
`<property name="hazelcastConfigurationFile">C:/Users/luise/Downloads/hazelcast-test.xml</property>`

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
I added the property, it still doesn't seem to work

**Review by Pandrex247 — APPROVED** [review]
Issue resolved.
Would be nice if the automated test was placed somewhere, even if just under `appserver/tests`

**Comment by luiseufrasio** [comment]
jenkins test please

**Pull request merged**
