### PR TITLE
Move API back into Payara Project

### PR DESCRIPTION
**Pull request by Pandrex247**
Moves the Payara API back into the Payara Project at the top level.

### CODE REVIEW

**Comment by Pandrex247** [comment]
This will probably get into conflict with https://github.com/payara/Payara/pull/1558

**Comment by smillidge** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins, would you kindly?

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by OndrejM** [comment]
@lprimak - with what you suggest, it wouldn't be possible to access any new additions in the API added in a quarterly release. I think it's pretty normal that the API tracks server versions. But we need to maintain backwards compatibility, so that anything compiled with e.g. API version 4.1.1.171 would run on Payara Server 172 and later.

**Comment by lprimak** [comment]
@OndrejM Think about it this way:
Let's say Java EE APIs tracked every version of every app server version ever released.  This would be impossible right?
I think API should remain as stable as possible, definitely not quarterly release with incompatible changes.

**Comment by OndrejM** [comment]
@lprimak That's easy to do with Java EE, because it's never updated until the next major version. But e.g. WildFly provides a BOM for every version, and the BOM specifies exactly the versions provided by the corresponding server version. And that's exactly what's happening with Payara Server too - we're adding new features in every version and some of them are exposed in the API (e.g. some notifiers added new interfaces in 171, CDI event bus was updated for 171 and may be updated again in future versions)

**Comment by OndrejM** [comment]
What I wanted to say that Payara API changes with every release, while Java EE changes only with a major EE release. It's not possible to fix the version of Payara API and add new API for developers unless we provide each API addition as a separate dependency.

**Comment by OndrejM** [comment]
But we should keep the API backwards compatible, so when you compile against API v4.1.1.171, you can easily run it on Payara Server v4.1.1.172 and future versions. I don't see how this is confusing.

**Comment by lprimak** [comment]
As someone who's dealt with APIs all my life, this breaks number of conventions which makes it very confusing:

- Semanic versioning for APIs is broken here, i.e APIs don't change with every minor release, only major releases
- Users are forced to track quarterly changes for APIs

In reality, API changes are very rare, and usually are prompted by the developer rather than operation need, such as upgrading the server itself.
API changes are rather rare, compare with server releases,
thus realistically it makes no sense to use the same version for the server as for APIs

**Comment by OndrejM** [comment]
> @lprimak In reality, API changes are very rare

This is just no the case in Payara Server - API changes happen almost with every 3-monthly release. How could we ship these changes to the developers if the API version doesn't change?

We could have a "stable" API artifact with a simple version like API-4.1, but what would it include? Only the features available in the first 4.1 version Payara Server? Those would be only JCache integration and possibly CDI bus, but even those were probably added later than in the first version.

We could release a new version of the API only if it changes, having versions like 4.0 for the initial API (JCache, CDI bus) matching versions 144+, 4.1 for later additions (RequestTracing interceptor introduced in 163) matching versions 163+, 4.2 for other additions in v171, etc.

But wouldn't this be even more confusing, as people would need to check which Payara Server version is compatible with which API artifact? In real world projects, applications are being developed against a particular version of a server, not an API. With each server upgrade, there's a migration step for the application. There's no point in having too much abstraction, because people general know what they are doing with the API artifact. If they don't need any specific APi feature from Payara Server, they can use the stable Java EE API, which would change only with a major Payara Server version.

**Comment by OndrejM** [comment]
Even if we start versioning the API with the 171 release, having API-4.0 matching Payara Server 171, I still expect that the API will be updated regularly with smaller or bigger updates, so there would be API-4.1, 4.2 ... in the future.

Payara v5 might change things a bit, but even once we release Payara v5 and API-5.0, I expect that the API might be changed pretty frequently - at least every second or third public release. And then I repeat my question, would it be less confusing to map API versions to server versions, or to keep the versions in synch and make the mapping evident? We would ensure that apps built against older API versions would run with new versions of Payara Server and devs don't have to update the API version if they don't  need the new features.

**Comment by lprimak** [comment]
This will be different from every other API versioning scheme out there, and that alone makes it a non-starter for me.  I don't care if it's by date, 1,2,3,4,5 any combination of the two, or something else, it just *can't* be tied to the server version.  It's too much of a breaking tradition with every other naming convention that's out there

**Comment by OndrejM** [comment]
Lenny, I think we have a different view on the API. 

I see the API as a gateway to the features exposed by Payara Server, and every new version can add new features. Without an API artifact there's no way to access these features, because Payara Server isn't a library that you can simply add to your classpath. For me the API is very close to a library that you drop into your app, except it's provided by the server.

I think what you expect from the API is something stable that doesn't change a lot. It's natural with Java EE, because that's solid API, and usually the implementations add non-standard features on top of it. E.g. hibernate provides additional API, which is AFAIK versioned with the impl, because with hibernate IMPL = API. With most libraries IMPL = API in fact. But we can't just expose Payara features as a library that devs can build against by importing it via a BOM into a maven project. Payara features are not compiled as a standalone library and the only way to build against these features is to build against the API.

I'd like to see an example of the tradition you mentioned, because so far the only example is Java EE, On the other hand, there are many examples whre API is versioned together with the IMPL, besides all libraries that don't provide a separate API (API = IMPL in that case), WildFly also couples API versions with IMPL, e.g. [wildfly-security-api](http://search.maven.org/#search%7Cga%7C1%7Cwildfly-security-api), [OpenEJB-API](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22openejb-api%22) is also couple with impl, even [SLF4J](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.slf4j%22) keeps the same version for the API and connectors to the underlying impl - in this case the connectors are in fact the impl of the common API.

I think it's very hard to find an example where API and IMPL are maitained by the same project and have different versions. And I believe that if there are such cases, the main focus is on the API, while with Payara Server's API artifact, in my view, the main focus is on the server and exposing the new functionality to the developers.

**Comment by smillidge** [comment]
The glassfish public api jar just tracks the GlassFish version. I see this as similar to the glassfish api jar.
https://github.com/payara/Payara/blob/master/nucleus/common/glassfish-api/pom.xml 
https://mvnrepository.com/artifact/org.glassfish.main.common/glassfish-api

**Comment by lprimak** [comment]
I'm not sure this applies. GF APIs are not publicized as I know of and nobody uses it that I know of. 

I think our API should project stability and ease of use

**Comment by OndrejM** [comment]
Glassfish-API wasn't known even to me until now :) Maybe it's not a question of versioning but of how we can make the API more accessible to the developers (blogs, guides, tutorials, examples, etc.)

I would continue with versions of glassfish-api and payara-api in line with server versions, but maybe we can improve versioning and distribution in the future. I just now don't see a better versioning scheme, which would be more stable yet still understandable and easy to use for developers.

**Comment by smillidge** [comment]
Both these apis are really just apis to internal server functionality so I think they should be aligned with the server version. More generic for features layered on top of the server I would envisage having a different version lifecycle. 

GlassFish api defines thins like start up classes, SQL Trace Listeners etc.

**Pull request merged**
