### PR TITLE
Migration to Jakarta Persistence 3.0 namespace for EJB Timer services

### PR DESCRIPTION
**Pull request by ctabin**
Migrate EJB timer services to Jakarta Persistence 3.0 namepace.

This is an attempt to solve #6148 and remove a dependency on Oracle thirt-party website (although it still depends on an external XSD).

### CODE REVIEW

**Comment by ctabin** [comment]
I wonder if the xmlns would even be requiered regarding the [persistence.xml](https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/tests/quicklook/ejb/slsbnicmt/metadata/persistence.xml) in GlassFish... It could be completely removed, hence avoiding any dependency on a third-party website. :thinking:

**Comment by pzygielo** [comment]
Not 100% sure, but after this I suspect the XSD to be solved by AS from the local catalogue to https://github.com/payara/Payara/blob/7455a779de9deba99b41f745c9f7a08cd18b294d/appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/persistence_3_0.xsd#L16
with no need to ask external service.

**Comment by ctabin** [comment]
Jenkins test please

**Comment by ctabin** [comment]
Any idea why the tests are failing ? My changes shouldn't have any impact other than avoiding request to oracle's servers... :thinking:

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by breakponchito** [comment]
Thank you very much for your contribution

**Pull request merged**
