### PR TITLE
Payara 604 upgrade version of guava

### PR DESCRIPTION
**Pull request by mulderbaba**
this one also contains the 3 commits from branch PAYARA-577-Get-Weld-2.3.x-working-on-Payara since weld 2.3.2 needs to be included first.

### CODE REVIEW

**Comment by danPowell52** [comment]
jenkins test please

**Comment by smillidge** [comment]
@mulderbaba which is the correct pull #635 or this one or both? BTW this has the same merge conflicts.

**Comment by mulderbaba** [comment]
@smillidge first #635, then this one. I'll take care of the conflicts now, having webservices-osgi pushed to version payara-p3 led to conflicts. I'll add new commits to resolve them.

**Comment by smillidge** [comment]
no worries it's the pax-logging changes that are conflicting.

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
Fixes #437 
Fixes #376

**Pull request merged**
