### PR TITLE
PAYARA-3296 Upgrade jsonp to 1.1.4 (Payara 4.x) 

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by Cousjava** [comment]
1.1.5 is the latest version of Jsonp, which is an EE 8 version

**Comment by jGauravGupta** [comment]
jenkins test please

**Pull request closed without merging**
