### PR TITLE
PAYARA-2846 StackOverflowException in OpenAPI

### PR DESCRIPTION
**Pull request by Pandrex247**
Add check for classes with fields with a type of themselves to prevent infinite recursion

### CODE REVIEW

**Comment by Pandrex247** [comment]
In conjunction with https://github.com/payara/Payara/pull/2827

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by dantonepinto** [comment]
I updated my microprofile-openapi.jar with the ApplicationProcessor.class from the latest build of Payara Server 5.
A similar StackOverflowError is happening:
`java.lang.StackOverflowError
        at java.lang.Class.getSimpleName(Class.java:1306)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:948)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:897)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:917)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:448)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:951)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:897)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:917)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:448)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:951)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:897)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.createSchema(ApplicationProcessor.java:917)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.visitSchema(ApplicationProcessor.java:448)
        at fish.payara.microprofile.openapi.impl.processor.ApplicationProcessor.insertObjectReference(ApplicationProcessor.java:951)
`

**Comment by MattGill98** [comment]
Hi @dantonepinto,

Can you create a Github issue for this, along with a small reproducer?

Kind regards,

Matt

**Pull request merged**
