### PR TITLE
FISH-6596 Jakarta Form Data

### PR DESCRIPTION
**Pull request by aubi**
## Description
Improvements for JakartaEE 8 applications running on Payara 6, original idea is https://github.com/payara/Payara/issues/5842

This PR is the opposite part to https://github.com/payara/Payara/pull/6031, which improved support of Java EE 9 apps on Payara 5.

The only change happens in jsf-uncompressed.js
All `jakarta.faces.*` post data is duplicated with `javax.faces` copies.

E.g. the reproducer application produced this output:
```
form: form
form:input: Message
jakarta.faces.behavior.event: action
jakarta.faces.partial.ajax: true
jakarta.faces.partial.event: click
jakarta.faces.partial.execute: form:jsfButton form:input
jakarta.faces.partial.render: form:output
jakarta.faces.source: form:jsfButton
jakarta.faces.ViewState: 3768650063610317665:-4574714117490412382
```

The new version produces this:

```
form: form
form:input: Message
javax.faces.ViewState: 1818319852855307414:-2863703350972090453
javax.faces.source: form:jsfButton
jakarta.faces.source: form:jsfButton
javax.faces.partial.event: click
jakarta.faces.partial.event: click
javax.faces.partial.execute: form:jsfButton form:input
jakarta.faces.partial.execute: form:jsfButton form:input
javax.faces.partial.render: form:output
jakarta.faces.partial.render: form:output
javax.faces.behavior.event: action
jakarta.faces.behavior.event: action
javax.faces.partial.ajax: true
jakarta.faces.partial.ajax: true
jakarta.faces.ViewState: 1818319852855307414:-2863703350972090453
```

### Testing Performed
Reproducer attached to the issue: https://github.com/payara/Payara/issues/5842
Deploy to Payara, open http://localhost:8080/Jakarta9-1.0-SNAPSHOT/ fill some data to the edit and click JSF button. Watch request details in the browser's Developer Tools in the Network tab. Details are in Mojarra PR: https://github.com/payara/patched-src-mojarra/pull/18

### Testing Environment
OpenJDK 11, Linux

## Notes for Reviewers
Depends on patched Mojarra PR: https://github.com/payara/patched-src-mojarra/pull/18

### CODE REVIEW

**Comment by aubi** [comment]
Jenkins test please

**Comment by aubi** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Pull request merged**
