### PR TITLE
FISH-9456 Resource Bundles

### PR DESCRIPTION
**Pull request by Viii3**
### Testing Performed

Started the server, created a new instance, closed the server, and then started the server again.

### Testing Environment

Maven version: 3.9.6
Java version: 11.0.23, vendor: Eclipse Adoptium
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### CODE REVIEW

**Review by Pandrex247 — COMMENTED** [review]
I think is a bit of a band-aid fix.
It resolves the issue, as `LogDomain` explicitly looks for LogStrings.properties, but it seems to be at odds with `LogFacade` which is explicitly looking for LogMessages.properties which is where the actual log messages exist.

It seems the file was renamed in https://github.com/payara/Payara/pull/5579 (and with a follow up https://github.com/payara/Payara/pull/5588) to fix an l10n issue.

This might need unpicking a bit...

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
tested on linux ubuntu 20.04, azul jdk 11, maven 3.8.6

**Review by breakponchito — APPROVED** [review]
LGTM

**Pull request merged**
