### PR TITLE
PAYARA-1255 ensure ActivationConfigProperty values of MDBs are transl…

### PR DESCRIPTION
**Pull request by smillidge**
…ated.

### CODE REVIEW

**Comment by lprimak** [comment]
Jenkins test please

**Comment by lprimak** [comment]
@smillidge I tested this scenario. EnvironmentProperty has its own mechanism for system property substitution. 
Although I don't see any harm in this change, what prompted you to make it?
Just curious.

**Comment by smillidge** [comment]
It didn't work with the ${ENV=} syntax for environment variables.

**Comment by lprimak** [comment]
Ah!  I see.  This is the best way to make the change then, thanks!

**Pull request merged**
