### PR TITLE
PAYARA-1891 First cut of some Ansi Color on the log formatters

### LINKED ISSUE #1672: JSON logging in payara micro
# Description #
----------
Hi, i tried to activate JSON logging in payara micro but could not get it to work.

## Current Outcome
In version 1: prebootcommand there is no change in the log format
In version 2: postbootcommand there is no change in the log format
In version 3: A slight change in the log format but still no JSON

## Steps to reproduce (Only for bug reports) 

Version 1
```
echo "set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.formatter='fish.payara.enterprise.server.logging.JSONLogFormatter'" > prebootcommands.txt && java -jar payara-micro-4.1.2.172.jar --prebootcommandfile prebootcommands.txt
```
Version 2
```
echo "set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.formatter='fish.payara.enterprise.server.logging.JSONLogFormatter'" > postbootcommands.txt && java -jar payara-micro-4.1.2.172.jar --postbootcommandfile postbootcommands.txt
```

Version 3: That's the only time there is a change in the log output format but still no JSON.
```
cat > logging.properties << EOF
#Payara Micro Logging Properties File

## Handlers
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=fish.payara.enterprise.server.logging.JSONLogFormatter
java.util.logging.ConsoleHandler.level=FINE

## Global Level
.level=INFO
EOF
java -jar payara-micro-4.1.2.172.jar --logProperties logging.properties
```

The full payara seems to have the same problem when started in verbose mode `./asadmin start-domain -v domain1`

## Environment ##

- **Payara Version**: 4.1.2.172
- **JDK Version**: 1.8.0_72 - Oracle
- **Operating System**: Mac
- **Database**: MongoDB

### PR DESCRIPTION
**Pull request by smillidge**
Also fixes #1672

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by ljnelson** [comment]
For posterity, this does not fix #1672; see [my comment over there](https://github.com/payara/Payara/issues/1672#issuecomment-347684157).  The root issue might be that the recommended formatters are not on the system classpath, [which they must be for the `LogManager#getFormatterProperty(String, Formatter)` method to work](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/logging/LogManager.java#1550).

**Comment by ljnelson** [comment]
(Ah, looking deeper, it appears that perhaps [this set of changes](https://github.com/payara/Payara/pull/1835/files#diff-c3bff768c64e43a75c305c89f4201d1fR1537), where you explicitly work around the system classloader requirement, is in effect only if someone does _not_ supply a `logging.properties` file via the Payara Micro `--logProperties` command line option.)

**Comment by smillidge** [comment]
Thanks for the analysis I will try and reproduce and fix. I was sure  tested this :-(

**Comment by ApoDBC** [comment]
Any update on this?

**Pull request merged**
