### PR TITLE
Fixing sonar blocker bugs in module core servlet container

### PR DESCRIPTION
**Pull request by svendiedrichsen**
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9gY1B6WA4TgV2zt&resolved=false&severities=BLOCKER&types=BUG

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Sorry for any email spam you may be getting Sven - we're getting some weird behaviour from the new Jenkins instance with who can and cannot trigger builds which changes between PRs.

**Comment by svendiedrichsen** [comment]
@Pandrex247 I'm ok with this.

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
