### PR TITLE
PAYARA-2546 Update Metrics to 1.1

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by smillidge** [comment]
Does the tck runner also need an update?

**Comment by smillidge** [comment]
Can you also make a PR to 4.x?

**Comment by jGauravGupta** [comment]
TCK Runner PR : https://github.com/payara/MicroProfile-TCK-Runners/pull/1

**Pull request merged**
