### PR TITLE
Update guava to version 18.0

### LINKED ISSUE #312: Upgrade payara to use the latest guava version
The latest version at this time is 18.0. Currently Payara uses 13.1

### PR DESCRIPTION
**Pull request by davewinters**
Fixes #312

### CODE REVIEW

**Comment by jerrinot** [comment]
Is Guava accessible to applications deployed? 

If so then this could be a backward incompatible change as I believe they removed bunch of deprecated methods.

**Comment by davewinters** [comment]
Yes and we need to have a mechanism of controlling which classes are delegated and not delegated to application classloaders from jars in the Glassfish modules directory.This existing Glassfish defect illustrates this issue : https://java.net/jira/browse/GLASSFISH-20850

**Comment by davewinters** [comment]
As per the 18.0 release notes these are the relevant changes regarding removal of deprecated methods and methods which use deprecated parameters.

Methods which took an InputSupplier or OutputSupplier parameter or which returned an InputSupplier or OutputSupplier (all of which were deprecated in Guava 15.0) have been removed. Additionally, ByteSource, ByteSink, CharSource and CharSink no longer implement InputSupplier or OutputSupplier.
The InputSupplier and OutputSupplier interfaces, which no longer have any usages in Guava, will be deleted in December 2015.  Enums class which was marked as deprecated which has been removed in 18.0. 

https://code.google.com/p/guava-libraries/wiki/Release18

**Comment by smillidge** [comment]
As we' e upgraded weld can you check the weld required version?

**Comment by davewinters** [comment]
Weld depends on guava 13.0.1:( http://mvnrepository.com/artifact/org.jboss.weld/weld-core/2.2.10.SP1

**Comment by smillidge** [comment]
Probably needs a JIRA raising on WELD then or get them to shade the dependency.

Steve Millidge
C2B2
T: 08450 539457 | M: 07920 100626 | W: www.c2b2.co.uk<http://www.c2b2.co.uk/> | E: smillidge@c2b2.co.uk<mailto:smillidge@c2b2.co.uk>

**Comment by davewinters** [comment]
Ok I'll raise a jira on Weld

**Comment by davewinters** [comment]
There is an existing jira on weld regarding this issue among many others: https://issues.jboss.org/browse/WELD-1574
I raised this weld task regarding shading the guava dependency: https://issues.jboss.org/browse/WELD-1965

**Comment by davewinters** [comment]
Looks like they will allow for guava versions greater than 11.0 in an upcoming weld release https://issues.jboss.org/browse/WELD-1966

**Comment by drupalspring** [comment]
Does it mean that after Weld fixes https://issues.jboss.org/browse/WELD-1966 to upgrades to use guava 18 and I upgrade the weld bundled in glassfish4.1 , then this issue https://java.net/jira/browse/GLASSFISH-20850 will be solved ? I just upgrade the glassfish 's WELD to 2.3.0.Beta1  but the issue of GLASSFISH-20850 still happens

**Pull request closed without merging**
