### PR TITLE
Fixing blocker bugs in microprofile jwt module

### PR DESCRIPTION
**Pull request by svendiedrichsen**
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9hu1B6WA4TgV3of&resolved=false&rules=squid%3AS2095&severities=BLOCKER%2CCRITICAL%2CMAJOR&types=BUG

### CODE REVIEW

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Will need to be tested with MicroProfile JWT TCK

**Comment by arjantijms** [comment]
@MeroRai Depends on PAYARA-3188

**Comment by MeroRai** [comment]
Passed the MicroProfile JWT TCK

**Pull request merged**
