### PR TITLE
PAYARA-2330 Add option to disable logging to file

### PR DESCRIPTION
**Pull request by MeroRai**

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by OndrejM** [comment]
Looks good. Just too many changes picked up by github in `GFFileHandler.java`, probably because of changes in formatting. It would be good to revert changes on lines which weren't really changed so that it's obvious which code was really changed.

**Comment by MeroRai** [comment]
@OndrejM changes in `GFFilehandler.java` is due to code indentation.

**Comment by michaelranaldo** [comment]
jenkins test please

**Pull request merged**
