### PR TITLE
PAYARA-3449-list-protocol-filters-command-fails-with-NPE

### LINKED ISSUE #3654: Internal Server error: /command/list-protocol-filters
# Internal Server error: /command/list-protocol-filters #
----------

I'm looking at the network configuration using asadmin commands (instead of opening up domain.xml).

There's a command called list-protocol-filters.

$ ./asadmin list-protocol-filters http-listener-1

## Expected Outcome

$ ./asadmin list-protocol-filters http-listener-1
A list of assigned filters on that protocol.

## Current Outcome

$ ./asadmin list-protocol-filters http-listener-1
remote failure: Request failed.
Command list-protocol-filters failed.

## Steps to reproduce (Only for bug reports) 

This happens on an empty payara 5.184, with secure-admin enabled.

1 -**  Start the domain

    ./asadmin start-domain domain1

2 -**  Request filters via the CLI:

$ ./asadmin list-protocol-filters http-listener-1

## Context (Optional)

I am trying to get http automatically redirected to https. Therefore I am examing the network configuration using adasmin commands.

Oddly enough I cannot seem to find the filters in the domain.xml either.

The server log says:
[2019-01-27T00:17:28.671+0100] [Payara 5.184] [SEVERE] [NCLS-CORE-00003] [javax.enterprise.system.core] [tid: _ThreadID=272 _ThreadName=admin-thread-pool::admin-listener(15)] [timeMillis: 1548544648671] [levelValue: 1000] [[
  Exception while running a command
java.lang.NullPointerException
	at org.glassfish.web.admin.cli.ListProtocolFilters.execute(ListProtocolFilters.java:100)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:549)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:545)
	at java.security.AccessController.doPrivileged(Native Method)

[2019-01-27T00:17:28.674+0100] [Payara 5.184] [INFO] [NCLS-REST-00003] [javax.enterprise.admin.rest] [tid: _ThreadID=272 _ThreadName=admin-thread-pool::admin-listener(15)] [timeMillis: 1548544648674] [levelValue: 800] [[
  An error occurred while processing the request. Please see the server logs for details.
java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
	at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:222)
	at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:90)
	
## Environment ##

- **Payara Version**: 4.1.1.x
- **Edition**:  Full
- **JDK Version**: 8 u191 b13 - OpenJDK
- **Operating System**: Linux
- **Database**: n.a.

### PR DESCRIPTION
**Pull request by mulderbaba**
Fixes #3654

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test

**Comment by MarkWareham** [comment]
jenkins test please

**Pull request merged**
