### PR TITLE
[QACI-542] Parallel stress test bugs

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Fixed all bugs discovered during parallel testing
A lot of this is rename / moves, so this PR is not that big :)

## Important Info
Actual parallel tests will pass once Arquillian connectors 2.4 and Arquillian Core 1.7 is released

### Testing Performed
Payara samples with enabled parallelism

## Notes for Reviewers
Use Ignore Whitespace Changes
About 3/4 of changes are just renames / file moves

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
Jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test please

**Review by MattGill98 — APPROVED** [review]

**Pull request merged**
