### PR TITLE
PAYARA-2215 Splitting --addjars to let the classpath separator be decided upon OS

### PR DESCRIPTION
**Pull request by svendiedrichsen**
under Windows uses ; otherwise : is used.

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
using the File.pathSeparator property to split

**Comment by mikecroft** [comment]
jenkins test please

**Comment by svendiedrichsen** [comment]
To my knowledge I already signed the CLA.

**Comment by mikecroft** [comment]
Thanks @svendiedrichsen - we have it on record :smiley:  The green CLA label is a green light to say all is well! We have a yellow "awaiting CLA" label if we need one.

**Comment by svendiedrichsen** [comment]
Thanks @mikecroft. I didn't know that.

**Comment by svendiedrichsen** [comment]
Do we need an approval on windows too?

**Comment by svendiedrichsen** [comment]
How about the `fish.payara.micro.cmd.options.SeperatedFilesValidator` class. It also uses : hard coded?

**Comment by arjantijms** [comment]
@Cousjava 
>Tested and works on Linux

Would probably be a good idea indeed to test this on Windows ;)

**Comment by svendiedrichsen** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Does indeed need testing on Windows before merging

**Comment by svendiedrichsen** [comment]
I'd love to help out but
* I don't have a Windows machine
* I made the changes

**Comment by Pandrex247** [comment]
@svendiedrichsen That was a poke at us not you! It had been a week since our last update on this PR, so I put the "Action Required" label and my comment as a reminder / big lilac flag to get this tested.
We're capable of testing it ourselves, we just need to actually do it and not let this languish and be forgotten about.

**Comment by Pandrex247** [comment]
Fixes #2070

**Comment by MeroRai** [comment]
Tested and works in windows 10

**Comment by arjantijms** [comment]
@MeroRai tested on Windows 10 and confirmed this to be working!

I'll now merge it in.

Thanks to everyone involved!

**Pull request merged**
