### PR TITLE
Payara-449 When clearing JDBC references, check if the JDBCLeakPreven…

### LINKED ISSUE #525: sproadic "attempted duplicate class definition for name" in Payara 4.1.153
The following error is occasionally seen on application unload:

remote failure: java.lang.LinkageError: loader (instance of 
org/glassfish/web/loader/WebappClassLoader): attempted duplicate class 
definition for name: "org/glassfish/web/loader/JdbcLeakPrevention"

### PR DESCRIPTION
**Pull request by davidweaver**
…tionClass has previously been defined to prevent duplicate class definition errors.

Fixes #525

### CODE REVIEW

**Comment by smillidge** [comment]
payara test please

**Comment by danPowell52** [comment]
payara test please

**Comment by danPowell52** [comment]
payara test please

**Comment by Pandrex247** [comment]
payara test please

**Comment by danPowell52** [comment]
jenkins build please

**Comment by danPowell52** [comment]
Flow Test Please

**Comment by danPowell52** [comment]
Flow Test Please

**Pull request merged**
