### PR TITLE
PAYARA-446 edit webservices version to use updated patch

### LINKED ISSUE #426: Multiple cookies cannot be added using Headers.putAll()

### PR DESCRIPTION
**Pull request by Pandrex247**
Fixes #426.
Relies upon https://github.com/payara/Payara_PatchedProjects/pull/12.

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
The server.log shows a Java version error, `Unsupported major.minor version 52.0`, which is likely causing the other errors.

I compiled the updated artefact with JDK8, and it looks like Jenkins is running under JDK7 and doesn't like it.

**Comment by smillidge** [comment]
It needs to be compiled for Java 7.

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Pull request merged**
