### PR TITLE
CUSTCOM-27: Fix that steady-pool-size can be 0

### PR DESCRIPTION
**Pull request by sergitrujillo**
# Description
This is a bug fix
https://github.com/payara/Payara/issues/4197

# Notes for Reviewers
It's my first pull request to payara. Sorry if if did some mistake in some convenion.

### CODE REVIEW

**Comment by jbee** [comment]
jenkins test please

**Comment by jbee** [comment]
@smillidge Do we need a CLA for this small of a change?

**Comment by smillidge** [comment]
No that's too small and obvious to be covered by copyright.

**Comment by jbee** [comment]
@rdebusscher you seemed to know the context of PAYARA-4205 - maybe you can have a look and see if the change is the solution you were looking for in your comments.

**Comment by dmatej** [comment]
It is rather PAYARA-4207, 4205 was about the error message. Both issues should join in correct solution = correct check allowing zero steady pool size and correct error message.
I will finish the test case for that tomorrow.

**Comment by rdebusscher** [comment]
@jbee The PR is good for the fix of the steady pool size. The 'issue' that we perform 2 checks (maxPoolSizeValue should be larger then steadyPoolSizeValue and values larger then 0) and show only 1 error message still needs to be addressed.

**Comment by dmatej** [comment]
Tested both with asadmin and DAS UI.

**Pull request merged**
