### PR TITLE
PAYARA-3046 listing cache keys not working Payara4

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Doesn't look like this actually compiles

**Comment by MattGill98** [comment]
Jenkins test please

**Comment by MattGill98** [comment]
Jenkins test please

**Comment by MattGill98** [comment]
Jenkins test please

**Pull request merged**
