### PR TITLE
FISH-6500 : hazelcast config file being read at startup

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
Payara seems to completely ignore hazelcast config file

### New tests
None

### Testing Performed
1. Build the project: mvn clean install -DskipTests
2. Start Payara Server
3. Go to localhost:4848 and click on Data Grid
4. Save the file Hazelcast-test.xml available at: https://payara.atlassian.net/browse/FISH-6500
5. Fill input: "Override configuration file" with the path of "Hazelcast-test.xml"
6. Click on Save button
7. Check content of "DAS Start Port"... It should be changed to 8876

### Testing Environment
Open JDK 1.8.0_312 on Windows 10 with Maven 3.8.4

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
