### PR TITLE
PAYARA-1583 clone the captured invocation rather than instantiating a…

### LINKED ISSUE #1506: Remote CDI events throw Exception instead of triggering the observers
# Description #
----------

Remote CDI Events don't work (or I'm not implementing it as I should).

## Expected Outcome

I expect that when I fire a remote CDI event, all Observers get notified and their method get triggered.

## Current Outcome

The following Exception is thrown when Payara tries to trigger the remote Observers. The exception is thrown for every observable.

```
[2017-04-03T07:17:48.210+0200] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.container.ejb.org.glassfish.ejb.security.application] [tid: _ThreadID=75 _ThreadName=hz._hzInstance_1_development.event-5] [timeMillis: 1491196668210] [levelValue: 1000] [[
  SECEJB9000: Exception while running pre-invoke
java.lang.ClassCastException: org.glassfish.api.invocation.ComponentInvocation cannot be cast to com.sun.ejb.EjbInvocation
	at org.glassfish.ejb.security.application.EjbSecurityComponentInvocationHandler$1.beforePreInvoke(EjbSecurityComponentInvocationHandler.java:76)
	at org.glassfish.api.invocation.InvocationManagerImpl.preInvoke(InvocationManagerImpl.java:181)
	at fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.eventReceived(ClusteredCDIEventBusImpl.java:181)
	at fish.payara.appserver.micro.services.PayaraInstance.receiveMessage(PayaraInstance.java:167)
	at fish.payara.nucleus.eventbus.TopicListener.onMessage(TopicListener.java:56)
	at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:134)
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
]]

[2017-04-03T07:17:48.211+0200] [Payara 4.1] [SEVERE] [] [com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl] [tid: _ThreadID=75 _ThreadName=hz._hzInstance_1_development.event-5] [timeMillis: 1491196668211] [levelValue: 1000] [[
  [172.20.0.56]:5900 [development] [3.7.4] hz._hzInstance_1_development.event-5 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@7b73507e
org.glassfish.api.invocation.InvocationException
	at org.glassfish.api.invocation.InvocationManagerImpl.postInvoke(InvocationManagerImpl.java:215)
	at fish.payara.micro.cdi.extension.ClusteredCDIEventBusImpl.eventReceived(ClusteredCDIEventBusImpl.java:207)
	at fish.payara.appserver.micro.services.PayaraInstance.receiveMessage(PayaraInstance.java:167)
	at fish.payara.nucleus.eventbus.TopicListener.onMessage(TopicListener.java:56)
	at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:134)
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
]]
```

## Steps to reproduce (Only for bug reports) 

1 -** Enable Hazelcast**
    default-config -> hazelcast -> check the "enabled" box
2 -** Set Hazelcast as the availability service**
    default-config -> availability service -> web- and ejb- container -> Persistence type: hazelcast
3 -** Deploy the Remote EJB application**
4 -** Deploy the other application(s)**
5 -** Trigger the Remote CDI event**

### Samples

All applications (The remote application and the 'normal' applications) have the following maven dependency:
```
<dependency>
	<groupId>fish.payara.api</groupId>
	<artifactId>payara-api</artifactId>
	<version>4.1.1.171.1</version>
	<scope>provided</scope>
</dependency>
```

Remote EJB application: 
```
@Singleton
@LocalBean
public class MyEventTriggerBean {

    @Inject
    @Outbound(loopBack = true) // loopBack true is required if the observing application is deployed on the same Payara Server instance
    Event<MyPayloadPOJO> event;

    private Map<String, CsnDto> map;

    public MyEventTriggerBean() {
    }

    public void doTheTrigger(String myContent) {
        event.fire(new MyPayloadPOJO(myContent));
    }
}
```

My listeners are coded like this:
```
public void handleEvent(@Observes @Inbound MyPayloadPOJO event) {
    logger.info("Received MyPayloadPOJO: " + event.getPayload());
}
```

The applications look like this:
- Remote EJB (The observable)
- EAR 1
    - Common EJB
        - Observer 1 (with the listener code)
    - App 1 EJB
        - Observer 2 (with the listener code)
    - App 1 WEB
        - Observer 3 (with the listener code)
        - WEB-INF/lib/ Common WEB jar
            - Observer 4 (with the listener code)
- EAR 2
    - Common EJB
        - Observer 5 (with the listener code)
    - App 2 EJB
        - Observer 6 (with the listener code)
    - App 2 WEB
        - Observer 7 (with the listener code)
        - WEB-INF/lib/ Common WEB jar
            - Observer 8 (with the listener code)

## Environment ##

- **Payara Version**: 4.1.1.171.1
- **Edition**: Full
- **JDK Version**: 7u79 - Oracle
- **Operating System**: Windows
- **Stackoverflow**: http://stackoverflow.com/questions/43111276/observable-pattern-in-remote-ejb

### PR DESCRIPTION
**Pull request by smillidge**
… ComponentInvocation.

Fixes #1506

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by lprimak** [comment]
@smillidge let me work on the other issue which should encompass this PR as well

**Comment by smillidge** [comment]
Can do

**Comment by lprimak** [comment]
subsumed by #1551

**Pull request closed without merging**
