### PR TITLE
APPSERV-70 Upgrade Sun Java Streaming XML Parser to 1.0.2

### PR DESCRIPTION
**Pull request by MeroRai**
# Description
This is a component upgrade of the Sun Java Streaming XML Parser to 1.0.2

### CODE REVIEW

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
as @dmatej  says. This has twice caused Jenkins to hang, needing admin intervention. The problem needs resolving locally before asking Jenkins to build again

**Comment by MarkWareham** [comment]
Added "DO NOT MERGE" label. Remove after code freeze

**Pull request closed without merging**
