### PR TITLE
FISH-8672 bugfix: removed class loader leaks

### LINKED ISSUE #4098: Out of memory after number of redeployments
# Description #
----------

On our preprod env after a couple tenths of redeployments instances are lacking memory and have to be killed manually from OS. Problem is reproduced on two separate environments.

## Expected Outcome
No out of memory error.

## Current Outcome
```
2019-07-22 11:50:12 WARNING [org.apache.catalina.core.ApplicationDispatcher doInvoke] Servlet.service() for servlet Faces Servlet threw exception
java.lang.OutOfMemoryError: Java heap space

2019-07-22 11:50:12 WARNING [org.apache.catalina.core.ApplicationDispatcher doInvoke] Servlet.service() for servlet Faces Servlet threw exception
java.lang.OutOfMemoryError: Java heap space

2019-07-22 11:50:06 WARNING [com.sun.enterprise.web.logger.CatalinaLogger write] StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.OutOfMemoryError: Java heap space

2019-07-22 11:50:12 WARNING [com.sun.enterprise.web.logger.CatalinaLogger write] org.apache.catalina.core.StandardHostValve@409d228: Exception Processing ErrorPage[errorCode=500, location=/WEB-INF/error_500.html]
javax.servlet.ServletException: Java heap space
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:725)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:824)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:688)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:527)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:496)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:378)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:507)
	at org.apache.catalina.core.StandardHostValve.dispatchToErrorPage(StandardHostValve.java:701)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:385)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:319)
	at org.apache.catalina.core.StandardHostValve.postInvoke(StandardHostValve.java:217)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:373)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$0(WorkerThreadIOStrategy.java:90)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
----- Root Cause -----
java.lang.OutOfMemoryError: Java heap space

```

## Steps to reproduce (Only for bug reports) 

Start the deployment group, perform multiple redeployments of your application and at some time the error will occur.
## Environment ##

- **Payara Version**: 5.191
- **Edition**: Full
- **JDK Version**:  zulu8.38.0.13-ca-jre8.0.212-linux_x64
- **Operating System**: RHEL
- Instances memory: -Xmx2g

### LINKED ISSUE #6301: Bug Report: Suspected WebappClassLoader Leak
### Brief Summary

We are currently using payara version 5.2022.5.

We noticed an increase in memory usage after each redeployment of our web application and thus we spent some time in investigating it. We captured the heap dump of the payara server after redeployment. We found that the instance of `WebappClassLoader` from the last deployment was not garbage collected, holding most of the resources with it.  

We tried to find out which GC root was holding a reference to it and prevented the destruction of the classloader. The screenshot attached below shows our finding. It looks like a cached request in the DefaultWorkerThread's cache is holding a reference to the classloader. However, we have searched online and looked into the codes, and yet failed to find a way to tell it to evict the cache.  

image

### Expected Outcome

The old `WebappClassLoader` instance shall be garbage collected to recover the memory held by objects of the last instances 

### Current Outcome

The old `WebappClassLoader` instance remains alive and prevented the garbage collection of other objects.

### Reproducer

To be provided later

### Operating System

Centos 6.5

### JDK Version

Oracle JDK 1.8.202

### Payara Distribution

Payara Server Web Profile

### LINKED ISSUE #6554: Bug Report: Application deployment and AS startup takes more RAM (ever growing) and too long (more than twice the time it took on previous releases)
### Brief Summary

Since Payara release 6.2023.9 we observe the application deployment time is at least twice as much as it was in 6.2023.8 and earlier versions. This includes the latest 6.2024.1 release.

We have tried to trace this performance regression and there seems to be no obvious reason for it:

 - We see no extra errors or warnings on the logs before or while deploying the application ear.
 - Increasing the available resources does not help (It reduces the application deployment time, but it's still nowhere near previous releases).
 - We see [a commit](https://github.com/payara/Payara/commit/34153c8741382e051df38717b92b07905837bf4b) added after 2023.8 that could be causing this issue.
 - A simple reproducer does not reproduce the issue.

We need a mitigation or fix to prevent the upgrade to the latest Payara release from severely impacting our instance deployment times. 

We want to know:

 - Is anyone else experiencing this issue?
 - Is there a documented way to optimise deployment times we may have missed to help us get 2023.8 and earlier deployment times in the latest Payara release for the affected application?

### Expected Outcome

Application deployment time remains approximately the same after upgrading from Payara 6.2023.8 to latest.

### Current Outcome

Application deployment time more than doubles after upgrading from Payara 6.2023.8 to latest. No reason given in the logs. We do not know which component is causing the delay.

### Reproducer

I wrote a reproducer deploying pretty much every Jakarta component we use (JAX-RS, JPA, @Startup EJBs) packed on a single ear, but it only helped to discard those components, at least on a basic level: https://github.com/elcodedocle/payara-sscce/tree/latest 

We'd appreciate any pointers on how to extend it to reproduce (Perhaps running a profiler during the startup of the affected application would be more helpful, for example?)

### Operating System

Debian bookworm

### JDK Version

Debian openjdk 17 JRE (17.0.10+7-1~deb12u1) / application built with target 11 on Debian openJDK 11.0.22+7-1~deb11u1

### Payara Distribution

Payara Server Full Profile

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Fixes ClassLoader leaks
fixes #6554 (partial fix, performance isn't addressed, just leaks)
fixes #6301 
fixes #4098 

## Testing
Tested with `appserver/tests/payara-samples/classloader-data-api` leak tester app and VisualVM

### Testing Environment
Any

### CODE REVIEW

**Comment by RInverid** [comment]
Testing locally, this MR does not address the memory issues mentioned in https://github.com/payara/Payara/issues/6554

**Comment by lprimak** [comment]
@RInverid Can you please elaborate? Do you have a reproducer that you are using?
Do you have any "GC Root" output from VisualVM?

My applications that I am testing with may not hit all of the leaks you are experiencing, as it doesn't use all of Jakarta EE APIs and only simple configurations.

Thank you for your help.

**Comment by lprimak** [comment]
You can also use this pre-built binary: https://nexus.hope.nyc.ny.us/repository/maven-releases/fish/payara/distributions/payara/6.2024.4-3/payara-6.2024.4-3.zip

**Comment by lprimak** [comment]
Ok, I found some more leaks... WAR deployments should be fixed, working on EAR deployments

**Comment by RInverid** [comment]
> @RInverid Can you please elaborate? Do you have a reproducer that you are using? Do you have any "GC Root" output from VisualVM?
> 
> My applications that I am testing with may not hit all of the leaks you are experiencing, as it doesn't use all of Jakarta EE APIs and only simple configurations.
> 
> Thank you for your help.

I have our own application that I'm testing deployment time and memory usage on, which is how I found the commit that caused #6554 . I'll re-run with your updated branch and let you know the results!

**Comment by lprimak** [comment]
I did test with reproducer from https://github.com/payara/Payara/issues/6554 and that works without leaks now.

**Comment by lprimak** [comment]
Looks like https://github.com/payara/Payara/pull/6637 introduced a regression.There are now dangling threads, and this PR needs to be updated to make `class ContainerBackgroundSessionProcessor` static as well

**Comment by lprimak** [comment]
Fixed regressions. Ready to go.

**Review by kalinchan — APPROVED** [review]

**Pull request merged**
