### PR TITLE
Changed the name suffix for the Windows service. (PAYARA-776)

### LINKED ISSUE #628: Windows service is named  "domain1 GlassFish Server"
Payara registers Windows services under the following name

   _domain1 **GlassFish** Server_

with a description of

   _**GlassFish** Server_

This is not nice. Certainly it should be "**Payara**" in both places. :-)

### PR DESCRIPTION
**Pull request by mikecroft**
Now reads "Payara" instead of "GlassFish"

### CODE REVIEW

**Comment by mikecroft** [comment]
Fixes #628

**Comment by smillidge** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Pull request merged**
