### PR TITLE
null check added for Base*HealthChecks

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
@mulderbaba can you resolve the conflicts please.

**Comment by mulderbaba** [comment]
we can skip this patch since part of it already implemented and merged to master with PR#601.

**Comment by smillidge** [comment]
Shall I close this then without merging?

**Comment by mulderbaba** [comment]
yes please do.

**Pull request closed without merging**
