### PR TITLE
PAYARA-3472-Update-Weld-to-3.1.0.Final

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by arjantijms** [comment]
@mulderbaba Did you look at integration SPI requirements? http://weld.cdi-spec.org/news/2019/02/06/weld-310Final/

**Comment by mulderbaba** [comment]
I haven't yet @arjantijms, I think they can be handled in a separate PR for the sake of the changelog. I'd get the upgrade in first to have the more bug-free latest version :)

**Comment by mulderbaba** [comment]
> Were whatever our patches were fixed in this new version of Weld?

@Pandrex247 yes this is the [diff](https://github.com/weld/core/compare/master...payara:weld-core-3.0.5.Final.payara-maintenance). The only commit that we cherry-picked was [this](https://github.com/weld/core/commit/f5f64068f7541dea3e29a4bb5e399881fa70a350) and [this](https://github.com/weld/core/commit/28ada5bd6386f9426d4e043608617a45d74cb20b) is the origin of it.

**Pull request merged**
