### PR TITLE
Payara 2094 upgrade hk2 to 2.5.0.b61

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by MattGill98** [comment]
Shouldn't the patched artifact be uploaded to nexus first?

**Comment by mulderbaba** [comment]
@MattGill98 they can be retrieved from Payara_PatchedProjects as well, there is a PR already for it.

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
