### PR TITLE
PAYARA-2288 MicroProfile Settings Page - Payara4

### PR DESCRIPTION
**Pull request by Pandrex247**
https://github.com/payara/Payara/pull/3011
https://github.com/payara/Payara_PatchedProjects/pull/186

### CODE REVIEW

**Comment by MeroRai** [comment]
Jenkins, quick test Payara 4 please

**Comment by Pandrex247** [comment]
Needs https://github.com/payara/Payara_PatchedProjects/pull/186 first

**Comment by Pandrex247** [comment]
Also checking JDK7 compatibility now

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Pull request merged**
