### PR TITLE
PAYARA-1946 Change X-Powered-By to Servlet 4.0 in Payara 5

### PR DESCRIPTION
**Pull request by smillidge**

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
