### PR TITLE
PAYARA-3216 Make Weld concurrent bean loading configurable

### PR DESCRIPTION
**Pull request by smillidge**
Concurrent Bean Loading is now configurable at the server level using asadmin.

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
/code java.lang.IllegalArgumentException: invalid version "3.0.5.Final.payara-p1": invalid qualifier "Final.payara-p1"
	at org.osgi.framework.Version.validate(Version.java:205)
	at org.osgi.framework.Version.<init>(Version.java:156)
	at org.apache.felix.framework.util.VersionRange.parse(VersionRange.java:98)
	at

**Comment by smillidge** [comment]
that is broken by the weld patch.

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
I think that because the patched Weld version is `3.0.5.Final.payara-p1` (as per our usual naming conventions), the generated bundle version is actually `3.0.5.Final_payara-p1`. Would it be better to update the patched projects by changing the patch version name to the one produced by the bundle plugin, or to just add a `weld.bundle.version` property to our poms to fix this?

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
#3412 depends on this

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
This looks like a legitimate test failure to me

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
It was a bug and is now fixed.

**Pull request merged**
