### PR TITLE
Removed jdk8 profile

### PR DESCRIPTION
**Pull request by Cousjava**
Fix for #1666 breaking on JDK8

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins, would you kindly?

**Comment by arjantijms** [comment]
Jenkins, would you kindly?

**Comment by lprimak** [comment]
Jenkins, would you kindly?

**Pull request merged**
