### PR TITLE
PAYARA-2905 Prevent creation of databases used for Timer Service when only non-persistent timers are present - Payara4

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by MeroRai** [comment]
jenkins test please

**Pull request merged**
