### PR TITLE
APPSERV-80 Upgrade Weld to 3.1.3.Final

### PR DESCRIPTION
**Pull request by MeroRai**
# Description
This is a component upgrade of the Weld to 3.1.3.Final

### CODE REVIEW

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Fails with the following error:

```
Launching Payara Server on Felix platform
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@3c28dd6f in service registry.
Completed shutdown of GlassFish runtime
We are in non-embedded mode, so fish.payara.server.internal.core.glassfish [76] has nothing to do.
Feb 21, 2020 9:24:58 AM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
Caused by: A MultiException has 2 exceptions.  They are:
1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [36]], State = [NEW]
2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
	implementation=org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector
	name=batch-runtime-configuration
	contracts={org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector,org.jvnet.hk2.config.ConfigInjector}
	scope=javax.inject.Singleton
	qualifiers={org.jvnet.hk2.config.InjectionTarget}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=@table-suffix={optional,default\:,datatype\:java.lang.String,leaf},@data-source-lookup-name={optional,datatype\:java.lang.String,leaf},@table-prefix={optional,default\:,datatype\:java.lang.String,leaf},@schema-name={optional,default\:APP,datatype\:java.lang.String,leaf},@executor-service-lookup-name={optional,default\:concurrent/__defaultManagedExecutorService,datatype\:java.lang.String,leaf},target={org.glassfish.batch.spi.impl.BatchRuntimeConfiguration},Bundle-SymbolicName={fish.payara.server.internal.batch.glassfish-batch-connector},Bundle-Version={5.201.0.SNAPSHOT}
```

**Comment by MarkWareham** [comment]
Added DO_NOT_MERGE label. remove after code freeze

**Comment by Pandrex247** [comment]
Upon further investigation, there appears to be a bug in this version of Weld - it seems to want something to provide it EJB 2 rather than 3.2.

**Pull request closed without merging**
