### PR TITLE
Add missing file headers and update (C) year

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by jbee** [comment]
jenkins test please

**Comment by pzygielo** [comment]
> Thanks again, could you also update the header of `HazelcastTimerStore.java` that was changed in #4311?

Updated.
I hoped for that change to transfer from #4377 :wink:

**Comment by jbee** [comment]
> I hoped for that change to transfer from #4377 

Miss that. It does so this was a bit unnecessary :D

**Comment by jbee** [comment]
jenkins test please

**Pull request merged**
