### PR TITLE
Change parent POM of nucleus to top-level parent

### PR DESCRIPTION
**Pull request by Pandrex247**
This helps prevent IntelliJ from getting stuck trying to resolve the project

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by dmatej** [comment]
Not sure if we need the https://maven.java.net/content/repositories/releases/ or not, and other things declared in the jvnet pom. Did you try to build with renamed local maven repository directory?

**Comment by Pandrex247** [comment]
I did not, I shall do so though - you're right building with local maven would probably means it survives the changes

**Comment by dmatej** [comment]
Wait a few minutes, I'm trying that right now ... downloading the Maven Universe :D

**Comment by dmatej** [comment]
[INFO] Payara-API 5.193-SNAPSHOT .......................... FAILURE
The following artifacts could not be resolved: org.glassfish.main.admin:config-api:jar:5.193-SNAPSHOT, org.glassfish.main.external:ldapbp-repackaged:jar:5.193-SNAPSHOT: Could not find artifact org.glassfish.main.admin:config-api:jar:5.193-SNAPSHOT in payara-patched-externals (file:///repo/git/Payara_PatchedProjects)

**Comment by dmatej** [comment]
I switched back to master, because this still may be caused by the dependency hell - each complete clean install downloads something, that is not nice. There is masked some dependency recursion ... 

OK, same in master ... I think I will try to kill it in next week at all costs ... seems this change does not cause any new problem, approved.

**Comment by Pandrex247** [comment]
#worksonmymachinewithcleanmaven
`mvn clean install -DskipTests -T 3 -PQuickBuild`

**Comment by dmatej** [comment]
Concurrent pull request: https://github.com/payara/Payara/pull/4139

**Pull request closed without merging**
