### PR TITLE
FISH-5778 : removing original property to not duplicate field in OpenApi

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
When using OpenAPI annotation @Schema on the Class attribute, it does not rename it instead it appears twice (initial attribute name and the renamed one)

### Blockers
None

### New tests
None

### Testing Performed
1. mvn clean install -T 3C -DskipTests
2. .\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain
3. Download and unzip: https://github.com/payara/Payara/files/7254999/payara-openapi-schema-name-error.zip
4. cd C:\Dev\reproducers\payara-openapi-schema-name-error
5. C:\Dev\reproducers\payara-openapi-schema-name-error\mvn clean package
6. C:\Users\luise\git\Payara\appserver\distributions\payara\target\stage\payara5\bin\asadmin deploy .\payara-openapi-schema-name-error.war
7. Poke http://localhost:8080/openapi
8. It should show only: components->schemas->TestModel->properties->friendly_name

### Testing Environment
Zulu JDK 1.8_212 on Windows 10 with Maven 3.8.4

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by breakponchito** [comment]
Jenkins test please

**Pull request merged**
