### PR TITLE
PAYARA-1590 Update EclipseLink to 2.6.4.payara-p2

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
@Cousjava  
Please approve the PR

**Comment by jGauravGupta** [comment]
jenkins test please

**Pull request merged**
