### PR TITLE
PAYARA-751 Incorporate Soteria

### PR DESCRIPTION
**Pull request by Pandrex247**
Incorporates the Soteria and javax.security-api JARs into Payara Server.
Given the lack of an easily accessible JAR for both, I shall upload my own builds to the Payara patched projects repository.

### CODE REVIEW

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
waiting on upload to payara patched projects

**Comment by smillidge** [comment]
You could ask @arjantijms to upload a build to maven cental

**Comment by Pandrex247** [comment]
He replied to someone a few days ago saying it's not easy for anyone outside of oracle to do: https://github.com/javaee-security-spec/soteria/issues/4

**Comment by arjantijms** [comment]
@Pandrex247 

Indeed, only a limited amount of Oracle staff can deploy to Maven central using the official group IDs, but as we know the activity or Oracle is currently not at the same level as it once was. An m1 in Maven central is however long overdue, so I'm going to try to get that done.

I'm also going to set up a maven repository on GitHub like you guys do, thanks for that tip ;)

**Comment by arjantijms** [comment]
Just as an update, currently we're looking into releasing a 1.0-m01 milestone (non snapshot) build via bintray. 

I also recently made a small change in the impl. bundle, where before it would include the API classes (so you could only put the soteria jar in /modules in Payara in you wanted to), it's not a strict impl and api jar.

**Comment by Pandrex247** [comment]
Thanks Arjan. We've held off on pushing our own build of Soteria to our PatchedProjects repo, as on reflection we're a little wary of essentially publishing the spec.

**Comment by lprimak** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
@arjantijms 
I saw that you've uploaded a milestone release to Bintray. I was looking at editing this PR to use that artefact, but the build fails as the artefact's parent can't be found:

```
    <parent>
       <groupId>org.glassfish.soteria</groupId>
       <artifactId>parent</artifactId>
       <version>1.0-m01</version>
    </parent>
```

Is this present on Bintray or somewhere else? I can't spot it.

Thanks

**Comment by arjantijms** [comment]
@Pandrex247 

Indeed, we just discovered this as well. Although the parent is not needed at runtime, it's needed for the build to succeed. A workaround is to exclude the parent:

    <exclusions>
        <exclusion>
            <groupId>org.glassfish.soteria</groupId>
            <artifactId>parent</artifactId>
        </exclusion>
    </exclusions>

But we need to look at this of course. CC @rdebusscher

**Comment by Pandrex247** [comment]
Thanks for the tip Arjan, but I can't get that exclusion to work - I don't think the `exclusion` tag works with the POM hierarchy. I'll wait until a proper fix is pushed out, as I'd rather not merge in workarounds if possible anyway.

**Comment by rdebusscher** [comment]
I uploaded the parent POM to Bintray.

I requested for inclusion into JCenter which takes normally a day or so.  I'll report back when I have the confirmation it is OK.

**Comment by rdebusscher** [comment]
A Bintray package with a POM only is not allowed in BinTray for release, as it seems. Got this response:

**In addition to the .pom file, a binary jar and a sources jar files are required.**

Working on alternatives.
Anyone an expert on BinTray?

**Pull request merged**
