### PR TITLE
PAYARA-1905 Integrate jmx monitoring with the notification service

### PR DESCRIPTION
**Pull request by Cousjava**

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by smillidge** [comment]
Also there are some PAYARA-1924 commits in the commit history.

**Comment by Cousjava** [comment]
The asadmin commands are the same as for healthcheck and request tracing

**Comment by smillidge** [comment]
OK the whole thing needs a bit of a refactor then for Payara 5. As this is nasty architecturally,

**Comment by Cousjava** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Pull request merged**
