### PR TITLE
WIP Ejb container - replaced usage of synchronized with unsynchronized classes where possible

### PR DESCRIPTION
**Pull request by svendiedrichsen**
First I want to apologize for the size of this PR but it basically handles with replacing synchronized classes. Additionally some generics were added where possible.

If this can't be accepted as it may be deemed to be too dangerous of a change that is not a problem. I just thought it would be a good idea to get rid of some of the ancient remains in the code. Besides it may speed up app deployment. I have seen speedup of admingui deployment of around 20%.

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by svendiedrichsen** [comment]
Tests failed with deployment of `singleton.ear`. I can't find the server logs to analyze.

**Comment by Pandrex247** [comment]
FYI, the quicklook tests are actually in the Payara source if you want to try and run them locally to debug this yourself. To run them:
1) Create a domain called _test-domain_: `asadmin create-domain test-domain`
2) Start the Derby database: `asadmin start-database --dbtype=derby`
3) Start the test domain: `asadmin start-domain test-domain`
4) Move into the _quicklook_ tests directory: `cd Payara/appserver/tests/quicklook`
5) Run the tests with Maven, providing the location of _payara5/glassfish_: `mvn clean test -Dglassfish.home=Payara/appserver/distributions/payara/target/stage/payara5/glassfish`

You can get away with not creating the test-domain for the purpose of testing this issue, though quicklook will fail on a few tests due to them being hard-coded to the test-domain.

**Comment by svendiedrichsen** [comment]
@Pandrex247 Thank you. I will fix this.

**Comment by svendiedrichsen** [comment]
@Pandrex247 I have fixed the permission problem with remote EJBs. All but the last 2 test succeed. Those two MDB tests fail because of a problem initialising the PayaraExecutorService:
```
   [testng] ERROR>java.lang.NullPointerException
   [testng] ERROR>	at fish.payara.nucleus.executorservice.PayaraExecutorService.initialiseThreadPools(PayaraExecutorService.java:133)
   [testng] ERROR>	at fish.payara.nucleus.executorservice.PayaraExecutorService.postConstruct(PayaraExecutorService.java:116)
```
Any hints on that?

**Comment by lprimak** [comment]
Looks like a bug in PayaraExecutorService.java:133 Should be very evident and easy to fix :) @svendiedrichsen please feel free to fix it

**Comment by svendiedrichsen** [comment]
@lprimak The reason for the NPE is simple. The fix is not so obvious at least for me.
```
        int threadPoolExecutorQueueSize = Integer.valueOf(
                payaraExecutorServiceConfiguration.getThreadPoolExecutorQueueSize());
```
The `payaraExecutorServiceConfiguration` is NULL. It should have been either injected or loaded by lookup.
```
    @Inject
    @Named(ServerEnvironment.DEFAULT_INSTANCE_NAME)
    @Optional
    private PayaraExecutorServiceConfiguration payaraExecutorServiceConfiguration;
```
In post construct method
```
        if (payaraExecutorServiceConfiguration == null) {
            payaraExecutorServiceConfiguration = Globals.getDefaultHabitat()
                    .getService(PayaraExecutorServiceConfiguration.class);
        }
```

**Comment by lprimak** [comment]
@svendiedrichsen @Pandrex247 ah, I didn't notice the secondary initialization.
Looks like PayaraExecutorService does not work correctly in Client Container (ACC) context

**Comment by lprimak** [comment]
Perhaps a "default case" where a configuration is simply not available, i.e. default ThreadPoolExecutor configuration can be used in that case

**Comment by lprimak** [comment]
Jenkins test

**Comment by svendiedrichsen** [comment]
There is still one last test failing. I'm working on it. Merry Christmas.

**Comment by svendiedrichsen** [comment]
@lprimak @Pandrex247 I have a problem with the MDB test. The test client can't find the deployed queue. Does my test setup have anything to do with it?

```
   [testng] ERROR>Dec 20, 2018 1:28:24 AM org.glassfish.enterprise.iiop.api.GlassFishORBHelper postConstruct
   [testng] ERROR>INFORMATION: GlassFishORBFactory service initialized.
   [testng] ERROR>com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Env-Prop: MsgBeanQueue@Field-Injectable Resource. Class name = com.sun.mdb.client.Client Field name=msgBeanQueue@java.lang.String@@@ into class com.sun.mdb.client.Client: Lookup failed for 'java:comp/env/MsgBeanQueue' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:638)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:439)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectClass(InjectionManagerImpl.java:199)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectClass(InjectionManagerImpl.java:195)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer$ClientMainClassSetting.getClientMainClass(AppClientContainer.java:636)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer.getMainMethod(AppClientContainer.java:525)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer.completePreparation(AppClientContainer.java:419)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer.prepare(AppClientContainer.java:320)
   [testng] ERROR>	at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:283)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:83)
   [testng] ERROR>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] ERROR>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [testng] ERROR>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] ERROR>	at java.lang.reflect.Method.invoke(Method.java:498)
   [testng] ERROR>	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
   [testng] ERROR>	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
   [testng] ERROR>Caused by: javax.naming.NamingException: Lookup failed for 'java:comp/env/MsgBeanQueue' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, com.sun.enterprise.naming.logicalName=java:comp/env/MsgBeanQueue} [Root exception is com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor from JNDI]]
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
   [testng] ERROR>	at javax.naming.InitialContext.lookup(InitialContext.java:417)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:561)
   [testng] ERROR>	... 15 more
   [testng] ERROR>Caused by: javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, com.sun.enterprise.naming.logicalName=java:comp/env/MsgBeanQueue} [Root exception is com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor from JNDI]
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:518)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
   [testng] ERROR>	at javax.naming.InitialContext.lookup(InitialContext.java:417)
   [testng] ERROR>	at com.sun.enterprise.naming.util.JndiNamingObjectFactory.create(JndiNamingObjectFactory.java:97)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:765)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:735)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
   [testng] ERROR>	... 18 more
   [testng] ERROR>Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor from JNDI
   [testng] ERROR>	at com.sun.enterprise.resource.naming.AdministeredObjectFactory.getObjectInstance(AdministeredObjectFactory.java:104)
   [testng] ERROR>	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.getObjectInstance(SerialContext.java:532)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:492)
   [testng] ERROR>	... 25 more
   [testng] 
   [testng] PASSED: createJMSRscTest("ejb/mdb/create_resources.asadmin")
   [testng] PASSED: deployJMSAppTest("./dist/mdb/")
   [testng] FAILED: runJMSAppTest("./dist/mdb/")
   [testng] java.lang.AssertionError: Run appclient against JMS APP failed ... expected:<true> but was:<false>
   [testng] 	at test.mdb.MDBTests.runJMSAppTest(MDBTests.java:87)
   [testng] ... Removed 26 stack frames
   [testng] SKIPPED: undeployJMSAppTest
   [testng] SKIPPED: deleteJMSRscTest
   [testng] 
   [testng] ===============================================
   [testng]     MDB_tests
   [testng]     Tests run: 5, Failures: 1, Skips: 2
   [testng] ===============================================
```

**Comment by lprimak** [comment]
I don't think it has to do with your setup. JNDI lookup of resources code is kinda fragile and i bet you uncovered a bug in it by doing your refactoring.
This issue is also with the ACC client container which isn't well tested.

**Comment by lprimak** [comment]
jenkins test

**Comment by svendiedrichsen** [comment]
Still working on it why in this test the AppClientContainer cannot lookup `jmsra` by JNDI lookup.

**Comment by lprimak** [comment]
> Still working on it why in the failing test the AppClientContainer cannot lookup jmsra over JNDI.

That is indeed what I found in the past. That code is fragile.

I usually debug appclient with gfclient.jar for the app client container, which is plain java startup so I can add the debug parameters straight to command line and attach NetBeans to the debug port.

**Comment by svendiedrichsen** [comment]
I close this PR because I can't get the tests to run reliably.

**Pull request closed without merging**
