### PR TITLE
PAYARA-4123 Refactored server JAXRS Request Tracing

### PR DESCRIPTION
**Pull request by dmatej**
- removed filter + exception mapper solution, which failed TCK's completitioncallback tests
- introduced EventListener solution, depends on Jersey
- removed trailing whitespaces in the module
- added logging and several generics
- reduced nesting of blocks in favor of readibility
- EnvironmentConfigSource uses AccessController to avoid security exceptions

### CODE REVIEW

**Comment by dmatej** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
`endpoint4` of the example app was just me messing around btw and wasn't included in the blog - I don't _think_ that one works.

**Comment by dmatej** [comment]
Jenkins test please

**Comment by dmatej** [comment]
&& span.getTraceEndTime().compareTo(comparisonSpan.getTraceEndTime()

Could it be currently processed request?

**Comment by Pandrex247** [comment]
I didn't get conflicts when I merged them locally...

**Comment by dmatej** [comment]
It depends on merging strategy and GIT settings - it detected "file copy" but it was false positive. I will push rebased version after TCK tests ...

**Comment by dmatej** [comment]
Jenkins test please

**Pull request merged**
