### PR TITLE
PAYARA-1015 Update Jersey to 2.22.2

### PR DESCRIPTION
**Pull request by michaelranaldo**

### CODE REVIEW

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
dan build

**Comment by michaelranaldo** [comment]
fix all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins call all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by michaelranaldo** [comment]
jenkins cure all ills

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
Looks like we have been too aggressive in upgrading this. Jersey 2.23+ requires HK2 2.5+ which is not released yet!!

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by smillidge** [comment]
This now has conflicts that need resolving

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Pull request merged**
