### PR TITLE
PAYARA-628 Created Hazelcast and Batch configuration 

### PR DESCRIPTION
**Pull request by MeroRai**

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by smillidge** [comment]
Can you redo the pull request as it has a lot of unrelated commits

**Pull request closed without merging**
