### PR TITLE
update to asm 9.3 for java 19 compatibility

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Compatibility enhancement. Will run on JDK 19
See #5659 and #5716

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by lprimak** [comment]
Jenkins test

**Comment by pdudits** [comment]
Jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Review by arieki — APPROVED** [review]
LGTM, related issue for patched eclipselink (ASM 9.3 upgrade) will be on separate PR https://github.com/payara/Payara/pull/5815

**Pull request merged**
