### PR TITLE
Payara issue 502.1

### PR DESCRIPTION
**Pull request by dmatej**
This is a first part resolving the issue (manually tested).

### CODE REVIEW

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
Similar to the other comments on the other pull requests

One thing we need changing to comply with the CDDL we need a comment in each changed file of the form;

Portions Copyright [2015] [C2B2 Consulting Limited]

Can you add please?

**Comment by danPowell52** [comment]
payara test please

**Comment by danPowell52** [comment]
payara test please

**Comment by danPowell52** [comment]
payara test please

**Comment by danPowell52** [comment]
payara test please

**Comment by dmatej** [comment]
Already done, I don't know if you noticed it :)

**Comment by smillidge** [comment]
Is there any order we need to do to merge 502.1 and 502.2?

**Pull request merged**
