### PR TITLE
FISH-374 Remove Support Portal Integration from Admin Console

### PR DESCRIPTION
**Pull request by MattGill98**
This PR removes the Zendesk admin console integration, as it's no longer applicable to Payara Community Edition.

It also adds a link to the Payara Enterprise information page on the Payara Website, as without this Payara Community has no admin console references to Payara Enterprise anymore as far as I can see.

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by MattGill98** [comment]
jenkins test please

**Review by MeroRai — APPROVED** [review]

**Pull request merged**
