### PR TITLE
FISH-6449: Fix optional resource injection and related EJB construction issues

### PR DESCRIPTION
**Pull request by pdudits**
## Description
This feature removes use of Weld's ResourceInjectionServices, which do not support optional injection of simple environment values as specified in  Platform spec 5.4 "Simple Environment Entries".

At same time it needs to fix JNDI naming of EJB interceptors, for which this component was used. It is fixed by creating ejb interceptors as non-contextual CDI beans.

This however breaks support for constructor injection of such interceptors as well as injection of `@Introspected Bean<?>` into them. For such cases the original method of constructing an interceptor is used.

### New tests

New module `reproducers` in payara-samples where test cases for specific bugs can be placed, rather than demonstration of payara features.

### Testing Performed

In addition to reproducer all CDI TCK tests related to interceptors and JNDI were run.

### Testing Environment
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.6
Java version: 11.0.12, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-11
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Kicked off a run of full EJB TCK here: https://jenkins.payara.fish/blue/organizations/jenkins/TCK-Suite/detail/TCK-Suite/484/pipeline

**Comment by Pandrex247** [comment]
Also kicked off a run of the CDI TCK since PAYARA-4078 / FISH-1830 was to do with failures in the CDI TCK: https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-10-TCK/detail/JakartaEE-10-TCK/154/pipeline

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
