### PR TITLE
FISH-6298 OpenAPI document doesn't take into account multiple applications deployment

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
When we have 2 applications deployed in one Payara Server instance, we are getting only one API Documentation

### Blockers
None

### New tests
None

### Testing Performed
Steps:
1. mvn clean install -DskipTests
2. ./appserver/distributions/payara/target/stage/payara5/bin/asadmin start-domain -v
3. Deploy two simple applications to the Payara server: https://payara.atlassian.net/browse/FISH-6298
4. http://localhost:8080/openapi/ shows the API documentation for the 2 apps.

### Testing Environment
JDK 1.8_212 on Windows 10 with Maven 3.8.4

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — COMMENTED** [review]
Hmm, need to check the specification and do some specific testing.
It's picking up the endpoints from the multiple applications, but it's formatting them in such a way that it's not obvious what the actual endpoints are, for example:

```
servers:
- url: http://PCA-0002:8080/jaxrs-beanvalidation
  description: Default Server.
- url: https://PCA-0002:8181/jaxrs-beanvalidation
  description: Default Server.
- url: http://PCA-0002:8080/jaxrs-jsonp
  description: Default Server.
- url: https://PCA-0002:8181/jaxrs-jsonp
  description: Default Server.
paths:
  /webresources/array:
    post:
      operationId: echoArray
      requestBody:
        content:
          application/json:
            schema:
              type: array
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
          description: Default Response.
  /webresources/endpoint:
    post:
      operationId: post2
      requestBody:
        content:
          '*/*':
            schema:
              type: string
      responses:
        default:
          content:
            '*/*':
              schema:
                type: object
          description: Default Response.
  /webresources/object:
    post:
      operationId: echoObject
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        default:
          content:
            application/json:
              schema:
                type: object
          description: Default Response.
```

What's the path of the _array_ endpoint? Could be one or both of these
* http://PCA-0002:8080/jaxrs-beanvalidation/webresources/array
* http://PCA-0002:8080/jaxrs-jsonp/webresources/array

On a similar topic, I'm curious what happens if two applications have the same endpoint but with different values. For example, what if both applications have the `webresources/array` endpoint, but one of them is a `PUT` rather than a `POST`, or one of them specifically returns JSON and the other plaintext.
I will knock something together to test this scenario.

On a similar note an integration test under payara-samples wouldn't go amiss ;)

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
From local testing, this breaks the OpenAPI TCK

**Comment by Pandrex247** [comment]
OK so having a simple get with different response types in two different applications seems to work nicely, it just seems to do a union of them:

* 1 Application with response type of plaintext:
```
servers:
- url: http://PCA-0002:8080/simple-get
  description: Default Server.
- url: https://PCA-0002:8181/simple-get
  description: Default Server.
paths:
  /rest/resource/hi:
    get:
      operationId: hi
      responses:
        default:
          description: Default Response.
          content:
            text/plain:
              schema:
                type: string
````
* 2 Applications, one with response type of plaintext and one with response type of json
```
servers:
- url: http://PCA-0002:8080/simple-get2
  description: Default Server.
- url: https://PCA-0002:8181/simple-get2
  description: Default Server.
- url: http://PCA-0002:8080/simple-get
  description: Default Server.
- url: https://PCA-0002:8181/simple-get
  description: Default Server.
paths:
  /rest/resource/hi:
    get:
      operationId: hi
      responses:
        default:
          description: Default Response.
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                type: string
```
* 2 Applications, both with response type of plaintext
```
servers:
- url: http://PCA-0002:8080/simple-get2
  description: Default Server.
- url: https://PCA-0002:8181/simple-get2
  description: Default Server.
- url: http://PCA-0002:8080/simple-get
  description: Default Server.
- url: https://PCA-0002:8181/simple-get
  description: Default Server.
paths:
  /rest/resource/hi:
    get:
      operationId: hi
      responses:
        default:
          description: Default Response.
          content:
            text/plain:
              schema:
                type: string
```

Still to look at though is this seemingly breaking MicroProfile TCK, and what the specification says about differentiating "servers" and paths - from a surface level it seems odd to me that the context root is a part of the "server" rather than the path.

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
