### PR TITLE
Keep the same JSON structure for normal logs and exceptions. Fixes #2952

### LINKED ISSUE #2952: Log Json Formatter - LogMessage type
Issue was closed due to inactivity (my bad) - https://github.com/payara/Payara/issues/2580

Also not sure how re-open the original issue.

Hi there,

I'm currently using Payara v4.1.2.173 with the JSON log formatter (https://payara.gitbooks.io/payara-server/documentation/payara-server/logging/json-formatter.html).

However I have an issue with the JSON generated for the LogMessage field.

https://github.com/payara/Payara/blob/master/nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java

Depending on the log it will generate not the same type of JSON.

i.e

Normal log message:

```
{
  "_Timestamp": "2018-05-29T13:14:00.378+0000",
  "_Level": "INFO",
  "_Version": "",
  "_LoggerName": "org.mongodb.driver.connection",
  "_ThreadID": "144",
  "_ThreadName": "__ejb-thread-pool3",
  "_TimeMillis": "1527599640378",
  "_LevelValue": "800",
  "_LogMessage": "Opened connection [connectionId{localValue:8, serverValue:10597}] to my-mongo-server:27017"
}
```

Exception log message:

```
{
  "_Timestamp": "2018-05-29T13:16:00.683+0000",
  "_Level": "WARNING",
  "_Version": "",
  "_LoggerName": "de.llorenzen.FormatterTest",
  "_ThreadID": "153",
  "_ThreadName": "__ejb-thread-pool12",
  "_TimeMillis": "1527599760683",
  "_LevelValue": "900",
  "_LogMessage": {
    "_Exception": "My exception message",
    "_StackTrace": "com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: [rest of the stacktrace]"
  }
}
```

One possible solution would be to add the stacktrace into an other field.

```
{
  "_Timestamp": "2018-05-29T13:16:00.683+0000",
  "_Level": "WARNING",
  "_Version": "",
  "_LoggerName": "de.llorenzen.FormatterTest",
  "_ThreadID": "153",
  "_ThreadName": "__ejb-thread-pool12",
  "_TimeMillis": "1527599760683",
  "_LevelValue": "900",
  "_LogMessage": "My exception message",
  "_StackTrace": "com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: [rest of the stacktrace]"
}

```
Thanks for your help,
Regards,
Jerome.

### PR DESCRIPTION
**Pull request by larslorenzen**
This implements the suggestion i made in #2580

https://github.com/payara/Payara/issues/2580#issuecomment-392966788

### CODE REVIEW

**Comment by smillidge** [comment]
I think this is implementing the same thing as PR #3139

**Comment by smillidge** [comment]
Thanks for the contribution can you send us a CLA https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md that way we can merge the PR and you can get Payara swag.

**Comment by smillidge** [comment]
Thanks we've received the CLA

**Comment by arjantijms** [comment]
Closing this for now, if someone wants to resolve the merge conflict this can always be re-opened.

**Pull request closed without merging**
