### PR TITLE
FISH-7451 Fixes for Issue 6274

### PR DESCRIPTION
**Pull request by thehpi**
## Description
This PR fixes issue [6274](https://github.com/payara/Payara/issues/6274).

When using @Transactional(Transactional.TxType.REQUIRES_NEW) the interceptor suspends and resumes the transaction but also the transaction in the current invocation. But when resuming it sets the tx in the invocation also when there was none when the interceptor started. This causes issues when using an observer method with @Observes(during = TransactionPhase.AFTER_SUCCESS) because when this method is executed the tx is already committed and when calling datasource.getConnection() this causes an exception because it is checking the tx status in the current invocation.

### New tests
No new tests because the current code do not allow for setting or mocking the invocationmanager/current invocation.

### Testing Performed
Reran the reproducer, no more exception.

### Testing Environment
MacOS Ventura 13.3.1, openjdk 11.0.17 2022-10-18, mvn version 3.8.6

## Documentation
See reproducer: https://github.com/thehpi/payara-after-success

## Notes for Reviewers
This is a quick fix, it might be better to fix it in TransactionalInterceptorBase so other interceptor implementations are also fixed but I cannot oversee this.

### CODE REVIEW

**Comment by thehpi** [comment]
Dear payara, I found a bug and spent considerable time to a) create a reproducer and b) to create a fix. I would be grateful if you could acknowledge this is a bug and have a look at the fix.

I would be happy to improve on the fix or maybe apply it in other places (interceptors).

**Comment by bramn** [comment]
+1 for this bug fix.

**Comment by aubi** [comment]
Jenkins test please

**Comment by aubi** [comment]
@thehpi 
Thank you for your PR, I was happy to review it and it looks well and works well.
The only problem was the reproducer, PostgreSQL complained during delete about the UUID:
```
db_1      | ERROR:  operator does not exist: character varying = uuid at character 28
db_1      | HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
db_1      | STATEMENT:  DELETE FROM HANS WHERE (ID = $1)
```

As the topic of this PR is somewhere else, I modified it to use String instead and I've got the expected results.
So I'm going to merge it.
Thank you!

**Review by aubi — APPROVED** [review]
LGTM, verified

**Pull request merged**
