### PR TITLE
Perform preInvoke and postInvoke steps symmetrically in BaseContainer

### PR DESCRIPTION
**Pull request by pdudits**

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by pdudits** [comment]
Thanks, it also operates flawlessly for almost two months in our XA-heavy production environment.

**Comment by smillidge** [comment]
OK let's go with it as it is passing all the test suites.

**Pull request merged**
