### PR TITLE
FISH-6718 (P6) Upgrade Build and Test Plugins

### PR DESCRIPTION
**Pull request by JamesHillyard**
## Description
Updates various components to newer versions.

### Blockers
None

### New tests
None

### Testing Performed
Compiled and started the server, created an instance and deployed application.

### Testing Environment
Windows 10, Maven 3.6.3, JDK 11

## Documentation
None

## Notes for Reviewers
None

### CODE REVIEW

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Breaks javadoc and source generation

**Comment by JamesHillyard** [comment]
Jenkins test please

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
