### PR TITLE
FISH-330 Implement LDAP MicroProfile Config Source

### PR DESCRIPTION
**Pull request by jGauravGupta**
## Description
This is a feature to use LDAP as a MicroProfile Config source and read the values from the LDAP server.

The implementation support **simple** and **none** auth type,
If **simple** auth type is selected then  Bind DN and Bind DN Password is mandatory otherwise optional.
If **searchBase** and **searchFilter** are not defined then data fetched from direct binding.

**asadmin command to configure LDAP config source:**
``` 
asadmin set-ldap-config-source-configuration --enabled true --dynamic=true --url ldap://ldap.forumsys.com:389 --authType none --searchFilter "(&(objectClass=top)(objectClass=person))" --searchBase dc=example,dc=com

asadmin get-ldap-config-source-configuration
Enabled  Url                           Auth Type  Start TLS Enabled  BindDN  BindDN Password  Search Base        Search Filter                             Search Scope  Connection Timeout  Read Timeout
true     ldap://ldap.forumsys.com:389  none       false                                       dc=example,dc=com  (&(objectClass=top)(objectClass=person))  subtree          
```
**Using the admin console:**
Go to Resources -> Configurations ->  Server Config -> MicroProfile -> LDAP

## Testing LDAP config source
LDAP provider configuration for **sample** auth type
**URL:** ldap://ldap.forumsys.com:389/
**Bind DN:** cn=read-only-admin,dc=example,dc=com
**Bind DN Password:** password
````
asadmin set-ldap-config-source-configuration --bindDNPassword=${ALIAS=my-password} --enabled=true --dynamic=true --url=ldap://ldap.forumsys.com:389  --bindDN=cn=read-only-admin,dc=example,dc=com --authType=simple 
asadmin create-password-alias my-password
Enter the alias password>password
Enter the alias password again>password

asadmin get-config-property --propertyName=sn --source=ldap
Read Only Admin
Command get-config-property executed successfully.
````

LDAP provider configuration for **none** auth type
**URL:** ldap://ldap.forumsys.com:389/
**Search Base:** dc=example,dc=com
**Search Filter:** &(objectClass=top)(objectClass=person))
``` 
asadmin set-ldap-config-source-configuration --enabled true --dynamic=true --url ldap://ldap.forumsys.com:389 --authType none --searchFilter "(&(objectClass=top)(objectClass=person))" --searchBase dc=example,dc=com     

asadmin get-config-property --propertyName=sn --source=ldap
Newton,Einstein,Tesla,Galilei,Euler,Gauss,Riemann,Euclid,Read Only Admin,Test,Curie,Nobel,Boyle,Pasteur,Group,training,training

```
## Documentation
https://github.com/payara/Payara-Community-Documentation/pull/95

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Review by MattGill98 — CHANGES_REQUESTED** [review]
Nothing wrong with the datasource itself, but the config source is currently configured as a 'cloud' config source in the get-config-property command. This is due to it using the partially implemented extension system, which might need refactoring here

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Review by MattGill98 — APPROVED** [review]

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
Jenkins passed, just isn't reporting it: https://jenkins.payara.fish/job/PayaraQuickBuildAndTest/2500/

**Pull request merged**
