### PR TITLE
FISH-6357 Ensure No Longer Using Jakarta Milestone Components

### PR DESCRIPTION
**Pull request by arieki**
## Description

Enhancement to upgrade milestone components 

### New tests

None

### Testing Performed

+ Performed Payara sample and Quicklook
+ JakartaEE-10-tck -> [test-result](https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-10-TCK/detail/JakartaEE-10-TCK/222/pipeline/)
+ TCK Suite -> [test-result](https://jenkins.payara.fish/blue/organizations/jenkins/TCK-Suite/detail/TCK-Suite/569/pipeline); `activation` and `java-mail-standalone` got failure due to configuration which fails to read test result however all test cases is passed for both

### Testing Environment

Windows 11, WSL, OpenJDK11, Maven 3.8.4

## Documentation

None

## Notes for Reviewers

None

### CODE REVIEW

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Review by pdudits — APPROVED** [review]

**Pull request merged**
