### PR TITLE
PAYARA-3516-Upgrade-hibernate-validator-to-5.4.3.Final-Payara4

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Doesn't seem to like this, it fails the build tests on the validation stuff.

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
> java.lang.AssertionError: Expected test to throw (an instance of javax.validation.ConstraintViolationException and exception with message a string containing "javax.validation.constraints.Size" and exception with message a string containing "org.javaee7.validation.methods.MyBean.sayHello")

**Comment by mulderbaba** [comment]
this needs more work on the hk2 upgrade.

**Comment by mulderbaba** [comment]
jenkins test

**Comment by mulderbaba** [comment]
jenkins test

**Pull request merged**
