### PR TITLE
PAYARA-1461-Refactor-core-server-to-use-the-new-public-api-jar

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
@Cousjava this needs a new releae of payara-api jar

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Pull request merged**
