### PR TITLE
FISH-6680 Upgrade mojarra to 2.3.18.payara-p1

### PR DESCRIPTION
**Pull request by arieki**
## Description

Upgrade patched Jersey from `2.3.14.payara-p3` to `2.3.18.payara-p1`

### Blockers

https://github.com/payara/patched-src-mojarra/pull/15

### New tests

None

### Testing Performed

Build and run payara server
Run payara samples and quicklook test

### Testing Environment

Windows 11, WSL, OpenJDK8, Maven 3.8.4

## Documentation

None

## Notes for Reviewers

None

### CODE REVIEW

**Comment by arieki** [comment]
jenkins test please

**Review by aubi — APPROVED** [review]
LGTM

**Comment by arieki** [comment]
jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Pull request merged**
