### PR TITLE
FISH-342 CopyOnWriteArrayList throws UnsupportedOperationException in WebdavServlet

### LINKED ISSUE #4695: CopyOnWriteArrayList throws expected exceptions in WebdavServlet
# Description #
----------
When a client tries to access a webdav resource which has been locked before and the lock has already expired, an UnsupportedOperationException is thrown. 

Please see: https://github.com/payara/Payara/blob/f8679df03bf6ad45fb5ffd1ca85c25a644201c50/appserver/web/web-core/src/main/java/org/apache/catalina/servlets/WebdavServlet.java at line 1521, where method "remove" is used on an iterator of https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html,
which explicitly does not support this method: "Element-changing operations on iterators themselves (remove, set, and add) are not supported. These methods throw UnsupportedOperationException."

## Environment ##

- **Payara Version**: 5.201
- **Edition**: Full
- **Operating System**: docker image

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Fixes: https://github.com/payara/Payara/issues/4695

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
@borisheithecker the whole point of a CopyOnWriteArrayList (or -Set) ist that it allows modification while reading from it. 
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html
Only modifications through its iterator (a weird concept for an iterator to begin with) is unsupported. Which is a bug IMHO. At least a break of the iterator contract.
You can test it for yourself with a simple unit test.
```
    @Test
    public void test() {
        List<String> list = new CopyOnWriteArrayList<>(Arrays.asList("1", "2", "3"));
        for (String v : list) {
            list.remove(v);
        }
    }
```
Cheers.

**Comment by borisheithecker** [comment]
@svendiedrichsen Thanks, I see. Hoping to get this merged for the next community release.

**Comment by jbee** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by svendiedrichsen** [comment]
I don't think the jenkins build failures have anything to do with the changes.

**Comment by jbee** [comment]
jenkins test please

**Comment by svendiedrichsen** [comment]
Looks like from the console that some server restart failed:
```
restart-server:

restart-server-unix:
Sending interrupt signal to process
Aborted by admin
     [exec] Result: 143
     [echo] 

restart-server-windows:
script returned exit code 143
Post stage
[Pipeline] zip
Writing zip file of /var/lib/jenkins/workspace/PayaraQuickBuildAndTest/appserver/distributions/payara/target/stage/payara5/glassfish/domains/test-domain/logs filtered by [server.*] to /var/lib/jenkins/workspace/PayaraQuickBuildAndTest/quicklook-log.zip
Zipped 1 entries.
Archiving /var/lib/jenkins/workspace/PayaraQuickBuildAndTest/quicklook-log.zip
[Pipeline] echo
tidying up after tests:
[Pipeline] sh
+ ./appserver/distributions/payara/target/stage/payara5/bin/asadmin stop-domain test-domain
CLI306: Warning - The server located at /var/lib/jenkins/workspace/PayaraQuickBuildAndTest/appserver/distributions/payara/target/stage/payara5/glassfish/domains/test-domain is not running. 
No domains are currently running.
Command stop-domain failed.
Error when executing always post condition:
hudson.AbortException: script returned exit code 1
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:569)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:515)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:461)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by svendiedrichsen** [comment]
@jbee Would you mind trying again, please? Would be nice to see this get merged.

**Comment by lprimak** [comment]
@svendiedrichsen is the latest master merged into this PR? I had an issue when it wasn't and tests were failing

**Comment by svendiedrichsen** [comment]
@lprimak I have pulled the latest master changes in now.

**Comment by MeroRai** [comment]
jenkins test please

**Comment by svendiedrichsen** [comment]
@MeroRai Would you consider this approvable?

**Comment by MeroRai** [comment]
@svendiedrichsen, looks good to me. I will create an internal issue to track the fix. Thank you for your contribution

**Pull request merged**
