### PR TITLE
Replace synchronized classes in module DOL

### PR DESCRIPTION
**Pull request by svendiedrichsen**
... and in the classes of modules which use DOL classes.

### CODE REVIEW

**Comment by jbee** [comment]
Thanks @svendiedrichsen for the contribution. Can you please provide a bit of reasoning why the order feature of the set wasn't important and why synchronisation isn't needed as both properties are lost when using `HashSet`.

**Comment by svendiedrichsen** [comment]
@jbee There was no order enforced within the OrderedSet. It was simply ordered as added to it as the implementation extended java.util.Vector. It was used as a Set and always only iterated over thus assuming no specific order. The question for synchronization should be answered by the tests doing all kinds of deployments.

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by svendiedrichsen** [comment]
There seems to be a problem with a test. I can't see the relation to my changes. I have added some more debug output. Does anyone have a clue?
```
   [testng] MDBTests.runJMSAppTest RtExec.execute: /work/develop/misc/Payara/appserver/distributions/payara/target/stage/payara5/glassfish/bin/appclient -targetserver localhost:3700 -client /work/develop/misc/Payara/appserver/tests/quicklook/./dist/mdb/ejb-ejb30-hello-mdbAppClient.jar -name ejb-ejb30-hello-mdb-client 
   [testng] 
   [testng] ERROR>Jul 15, 2019 9:46:10 PM org.glassfish.enterprise.iiop.api.GlassFishORBHelper postConstruct
   [testng] ERROR>INFORMATION: GlassFishORBFactory service initialized.
   [testng] ERROR>com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Unresolved Message-Destination-Ref MsgBeanQueue@java.lang.String@null into class com.sun.mdb.client.Client: Lookup failed for 'java:comp/env/MsgBeanQueue' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:638)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:439)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectClass(InjectionManagerImpl.java:199)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectClass(InjectionManagerImpl.java:195)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer$ClientMainClassSetting.getClientMainClass(AppClientContainer.java:639)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer.getMainMethod(AppClientContainer.java:526)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer.completePreparation(AppClientContainer.java:420)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.AppClientContainer.prepare(AppClientContainer.java:321)
   [testng] ERROR>	at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:283)
   [testng] ERROR>	at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:83)
   [testng] ERROR>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] ERROR>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [testng] ERROR>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] ERROR>	at java.lang.reflect.Method.invoke(Method.java:498)
   [testng] ERROR>	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
   [testng] ERROR>	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
   [testng] ERROR>Caused by: javax.naming.NamingException: Lookup failed for 'java:comp/env/MsgBeanQueue' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, com.sun.enterprise.naming.logicalName=java:comp/env/MsgBeanQueue} [Root exception is com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor [__SYSTEM/descriptors/jmsra] from JNDI]]
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
   [testng] ERROR>	at javax.naming.InitialContext.lookup(InitialContext.java:417)
   [testng] ERROR>	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:561)
   [testng] ERROR>	... 15 more
   [testng] ERROR>Caused by: javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, com.sun.enterprise.naming.logicalName=java:comp/env/MsgBeanQueue} [Root exception is com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor [__SYSTEM/descriptors/jmsra] from JNDI]
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:518)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
   [testng] ERROR>	at javax.naming.InitialContext.lookup(InitialContext.java:417)
   [testng] ERROR>	at com.sun.enterprise.naming.util.JndiNamingObjectFactory.create(JndiNamingObjectFactory.java:97)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:765)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:735)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:159)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
   [testng] ERROR>	... 18 more
   [testng] ERROR>Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to look up ConnectorDescriptor [__SYSTEM/descriptors/jmsra] from JNDI
   [testng] ERROR>	at com.sun.enterprise.resource.naming.AdministeredObjectFactory.getObjectInstance(AdministeredObjectFactory.java:105)
   [testng] ERROR>	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.getObjectInstance(SerialContext.java:532)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:492)
   [testng] ERROR>	... 25 more
   [testng] ERROR>Caused by: javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, com.sun.enterprise.naming.logicalName=java:comp/env/MsgBeanQueue} [Root exception is java.rmi.MarshalException: CORBA MARSHAL 1330446343 No; nested exception is: 
   [testng] ERROR>	org.omg.CORBA.MARSHAL: FEIN: 00810007: Underflow in BufferManagerReadStream after last fragment in message  vmcid: OMG  minor code: 7  completed: No]
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:518)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
   [testng] ERROR>	at javax.naming.InitialContext.lookup(InitialContext.java:417)
   [testng] ERROR>	at com.sun.enterprise.resource.naming.AdministeredObjectFactory.getObjectInstance(AdministeredObjectFactory.java:99)
   [testng] ERROR>	... 28 more
   [testng] ERROR>Caused by: java.rmi.MarshalException: CORBA MARSHAL 1330446343 No; nested exception is: 
   [testng] ERROR>	org.omg.CORBA.MARSHAL: FEIN: 00810007: Underflow in BufferManagerReadStream after last fragment in message  vmcid: OMG  minor code: 7  completed: No
   [testng] ERROR>	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.mapSystemException(Util.java:267)
   [testng] ERROR>	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:201)
   [testng] ERROR>	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
   [testng] ERROR>	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
   [testng] ERROR>	at com.sun.enterprise.naming.impl._SerialContextProvider_DynamicStub.lookup(com/sun/enterprise/naming/impl/_SerialContextProvider_DynamicStub.java)
   [testng] ERROR>	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
   [testng] ERROR>	... 31 more
   [testng] ERROR>Caused by: org.omg.CORBA.MARSHAL: FEIN: 00810007: Underflow in BufferManagerReadStream after last fragment in message  vmcid: OMG  minor code: 7  completed: No
   [testng] ERROR>	at com.sun.proxy.$Proxy36.endOfStream(Unknown Source)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.BufferManagerReadStream.underflow(BufferManagerReadStream.java:122)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_1.grow(CDRInputStream_1_1.java:111)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_octet_array(CDRInputStream_1_0.java:531)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.getConvertedChars(CDRInputStream_1_0.java:2098)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.internalReadString(CDRInputStream_1_0.java:472)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readStringOrIndirection(CDRInputStream_1_0.java:458)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_repositoryId(CDRInputStream_1_0.java:1718)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_repositoryIds(CDRInputStream_1_0.java:1700)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRepositoryIds(CDRInputStream_1_0.java:811)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRepositoryIds(CDRInputStream_1_0.java:776)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:877)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:518)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObjectField(IIOPInputStream.java:2091)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.inputClassFields(IIOPInputStream.java:2333)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.defaultReadObjectDelegate(IIOPInputStream.java:525)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.InputStreamHook.defaultReadObject(InputStreamHook.java:233)
   [testng] ERROR>	at java.util.concurrent.ConcurrentHashMap.readObject(ConcurrentHashMap.java:1438)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.invokeObjectReader(IIOPInputStream.java:1764)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObject(IIOPInputStream.java:1146)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.simpleReadObject(IIOPInputStream.java:350)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValueInternal(ValueHandlerImpl.java:311)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValue(ValueHandlerImpl.java:277)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:826)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:928)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:518)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObjectField(IIOPInputStream.java:2091)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.inputClassFields(IIOPInputStream.java:2333)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.inputObject(IIOPInputStream.java:1156)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.IIOPInputStream.simpleReadObject(IIOPInputStream.java:350)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValueInternal(ValueHandlerImpl.java:311)
   [testng] ERROR>	at com.sun.corba.ee.impl.io.ValueHandlerImpl.readValue(ValueHandlerImpl.java:277)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.readRMIIIOPValueType(CDRInputStream_1_0.java:826)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:928)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(CDRInputStream_1_0.java:746)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_value(CDRInputObject.java:512)
   [testng] ERROR>	at com.sun.corba.ee.impl.corba.TCUtility.unmarshalIn(TCUtility.java:289)
   [testng] ERROR>	at com.sun.corba.ee.impl.corba.AnyImpl.read_value(AnyImpl.java:608)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_any(CDRInputStream_1_0.java:582)
   [testng] ERROR>	at com.sun.corba.ee.impl.encoding.CDRInputObject.read_any(CDRInputObject.java:469)
   [testng] ERROR>	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.readAny(Util.java:452)
   [testng] ERROR>	at com.sun.corba.ee.impl.presentation.rmi.DynamicMethodMarshallerImpl$10.read(DynamicMethodMarshallerImpl.java:298)
   [testng] ERROR>	at com.sun.corba.ee.impl.presentation.rmi.DynamicMethodMarshallerImpl.readResult(DynamicMethodMarshallerImpl.java:482)
   [testng] ERROR>	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:191)
   [testng] ERROR>	... 35 more
   [testng] 
   [testng] PASSED: createJMSRscTest("ejb/mdb/create_resources.asadmin")
   [testng] PASSED: deployJMSAppTest("./dist/mdb/")
   [testng] FAILED: runJMSAppTest("./dist/mdb/")
   [testng] java.lang.AssertionError: Run appclient against JMS APP failed ... expected:<true> but was:<false>
   [testng] 	at test.mdb.MDBTests.runJMSAppTest(MDBTests.java:93)
   [testng] ... Removed 26 stack frames
   [testng] SKIPPED: undeployJMSAppTest
   [testng] SKIPPED: deleteJMSRscTest
```

**Comment by jbee** [comment]
> The question for synchronization should be answered by the tests doing all kinds of deployments.
@svendiedrichsen If I understand you correctly you say that we should rely on the tests to verify that synchronisation actually isn't needed? I don't think the tests are that thorough that they would detect a threading problem with certainty.

**Comment by svendiedrichsen** [comment]
> @svendiedrichsen If I understand you correctly you say that we should rely on the tests to verify that synchronisation actually isn't needed? I don't think the tests are that thorough that they would detect a threading problem with certainty.

In a system as complex as the payara server you can't detect _any_ threading problem with certainty. The tests is all you have to detect _anything_ wrong with the server.

**Comment by svendiedrichsen** [comment]
The app-client JNDI lookup problem shows up again. Better not touch anything.

**Pull request closed without merging**
