### PR TITLE
PAYARA-2975 'metrics.xml' parsed and metadata re-registered on every call to '/metrics' endpoint

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Hi @Cousjava,

The lazy loaded mbeans are now stored in `unresolvedBaseMetadataList` & `unresolvedVendorMetadataList` for further evaluation so it will not be ignored.

**Comment by Cousjava** [comment]
@jGauravGupta But they will only be resolved to one MBean, in cases where they are for multiple when it has a wildcard it will only resolve the first one. I have tested this.

**Comment by jGauravGupta** [comment]
jenkins test please

**Pull request merged**
