### PR TITLE
Properly cleaning up ContainerBackgroundSessionProcessor threads after application is undeployed

### LINKED ISSUE #6747: Bug Report: Regression results in dangling ContainerBackgroundSessionProcessor threads
### Brief Summary

Looks like https://github.com/payara/Payara/pull/6637 introduced a regression.
`ContainerBackgroundSessionProcessor` threads aren't getting removed when an application is undeployed.

Looking at the code, I don't see any obvious issues, but thread dumps show that the threads are dangling.
This prevents application from unloading and creates more memory leaks, and prevents #6677 from working.

I will try to debug and see what I can find out, and submit a PR if I can.
But currently, I can't see any obvious cause of this.

### Expected Outcome

`ContainerBackgroundSessionProcessor` threads exit when application is unloaded

### Current Outcome

Dangling `ContainerBackgroundSessionProcessor`
As you can see in the image below, there are more `ContainerBackgroundSessionProcessor` threads than `ContainerBackgroundProcessor` threads, which is wrong

336649914-52319230-da10-40fb-9a36-7e6c99cf2a5b

### Reproducer

Any WAR application will show this behavior

### Operating System

Any

### JDK Version

Any

### Payara Distribution

Payara Server Full Profile, Payara Server Web Profile

### PR DESCRIPTION
**Pull request by lprimak**
fixes #6747 

## Description
Bugfix. #6637 caused a regression that left dangling threads around

## Testing
Manual testing for memory leaks

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by breakponchito** [comment]
thank you @lprimak for your contribution

**Pull request merged**
