### PR TITLE
PAYARA-2181 Use less than a second on JMX Monitoring

### PR DESCRIPTION
**Pull request by michaelranaldo**
…han-a-second-on-JMX-Monitoring-breaks

PAYARA-2181, PAYARA-2183 Values less than 1 second do not work

### CODE REVIEW

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Failed to start test domain

**Comment by Cousjava** [comment]
jenkins test please

**Comment by smillidge** [comment]
Jenkins quick test Payara 5 please

**Comment by michaelranaldo** [comment]
Jenkins quick test Payara 5 please

**Comment by michaelranaldo** [comment]
Jenkins quick test payara 5 please

**Comment by smillidge** [comment]
There's no changes in this branch

**Comment by michaelranaldo** [comment]
Changes here have been included with the 174-Release merge into 5. This PR can be closed.

**Pull request closed without merging**
