### PR TITLE
PAYARA-2111 Fixed warning in logs from mismatched error page

### LINKED ISSUE #1886: BUG: logs flooded by [WARNING] [AS-WEB-CORE-00230] despite correct error-page
# Description #
----------

Logs get flooded by 
[2017-08-21T18:01:44.932+0200] [Payara 4.1] [WARNING] [AS-WEB-CORE-00230] [javax.enterprise.web.core] [tid: _ThreadID=34 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1503331304932] [levelValue: 900] [[
  The error-page /home/kbachl/dev/servers/payara41/glassfish/domains/domain1/applications/error-1.0-SNAPSHOT/code-404 or /code-404 does not exist]]

despite the config in web.xml beeing done:

 	<filter-mapping>
		<filter-name>wicket.error</filter-name>
		<url-pattern>/*</url-pattern>
		<dispatcher>REQUEST</dispatcher>
		<dispatcher>ERROR</dispatcher>
	</filter-mapping>

	<error-page>
		<error-code>404</error-code>
		<location>/code-404</location>
	</error-page>

and having a valid error page under that location path; It happens when the location is satisfied by a wicket page. Error page however is correctly shown. A quickstart to demonstrate is available.

Glassfish 3 didnt show this behaviour. After upgrade to payara it happens to us (payara 4.1.172 and 4.1.173 affected - others not tested by me)

## Expected Outcome
no warning should be logged as the error page is used as expected

## Steps to reproduce (Only for bug reports) 

grab the quickstart error war and deploy it under / in a fresh payara; Open the browser at localhost:payaraport and then click on the link - watching the logfiles; You see the correct error page but still warning logged

All code is supplied in the error-w7-quickstart-maven-project.tar.gz file;

[error-1.0-SNAPSHOT.war.zip](https://github.com/payara/Payara/files/1239438/error-1.0-SNAPSHOT.war.zip)
[error-w7-quickstart-maven-project.tar.gz](https://github.com/payara/Payara/files/1239441/error-w7-quickstart-maven-project.tar.gz)

### PR DESCRIPTION
**Pull request by michaelranaldo**
Tested with example application and custom application, behaviour remains the same, just without the error page. If a file is provided and configured within Wicket, but cannot be found, then Wicket will throw the error - if a file is correct but incorrectly configured then Payara's behaviour remains the same.

Thanks for @arjantijms and @MattGill98 for the help!

Fixes #1886

### CODE REVIEW

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
2 extra to look at:

The pattern is now compared via "glob", but the Servlet patterns are a bit different, namely:


_In the Web application deployment descriptor, the following syntax is used to define mappings:_

- A string beginning with a ‘/’ character and ending with a ‘/*’ suffix is used for path mapping.
- A string beginning with a ‘*.’ prefix is used as an extension mapping.
- A string containing only the ’/’ character indicates the "default" servlet of the application. In this case the servlet path is the request URI minus the context path and the path info is null.
- All other strings are used for exact matches only.

Internally there should be a specific matcher for this available, as Payara used this too internally to dispatch. From a spec point of view, `WebRoleRefPermission` on a `PermissionCollection` does this same kind of match as well. Semi-internally, see also `javax.security.jacc.URLPattern`.

Another thing that I'm missing is the check on the filter to see if the filter filters the error dispatch. Only those filters should be taken into account for the URL match.

Otherwise, looks good!

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Pull request merged**
