### PR TITLE
PAYARA-3163 WebAppClassLoader fails to find JAX-WS Handler class

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
