### PR TITLE
FISH-5808 : exhibiting single @Path method

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
JAX-RS Subresources don't Appear in OpenAPI Document

### Blockers
None

### New tests
None

### Testing Performed
1. mvn clean install -T 3C -DskipTests
2. .\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain
3. cd C:\Dev\reproducers\FISH-5808
4. C:\Dev\reproducers\FISH-5808\mvn clean install
5. C:\Users\luise\git\Payara\appserver\distributions\payara\target\stage\payara5\bin\asadmin deploy .\openapi-test.war
6. Poke http://localhost:8080/openapi
7. It should show: /resources/foo/bar into **paths** & **endpoints**

### Testing Environment
Zulu JDK 1.8_212 on Windows 10 with Maven 3.8.4

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — APPROVED** [review]
Reproducer and OpenAPI TCK tested and worked.

Looks Good™

The reproducer does look simple enough that it could be easily automated under `appserver/tests/payara-samples/samples/reproducers` if you wanted to go the extra mile 😉

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Pull request merged**
