### PR TITLE
FISH-381 Update nimbus-jose-jwt to 8.20

### PR DESCRIPTION
**Pull request by Pandrex247**
## Description
This is a component upgrade, fixing a security vulnerability.

## Testing
Ran payara-samples and the MicroProfile TCKs using managed profile.

### Testing Environment
Linux, JDK 8u252

### CODE REVIEW

**Comment by OndroMih** [comment]
Fixes https://github.com/payara/Payara/issues/4831

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by svendiedrichsen** [comment]
There were some maven problems concerning the availability of some dependencies.
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for fish.payara.samples:jakartaee-namespace-transformer:5.2020.4-SNAPSHOT: Could not find artifact fish.payara.samples:payara-samples-profiled-tests:pom:5.2020.4-SNAPSHOT in payara-staging (https://nexus.payara.fish/content/repositories/payara-staging) and 'parent.relativePath' points at wrong local POM @ line 48, column 13
```

**Comment by Pandrex247** [comment]
Thanks Sven, should hopefully be resolved now
Came about from a PR with a new module getting created before a version increment

**Comment by jGauravGupta** [comment]
Jenkins test please

**Pull request merged**
