### PR TITLE
PAYARA-3824 Use KeyID from JWT header to find public key in JSON Web Key Set

### PR DESCRIPTION
**Pull request by lreimer**
This patch will use the KeyID `kid` header field (if present) from the JSON web token to find the matching public key in a JSON Web Key Set (JWKS) array. If there is no KeyID, then the first key entry will be used just like before.

Following changes:
- I had to split parsing and verification of the JWT in `JwtTokenParser.java` so that I can access the JWT header without having to parse the `SignedJWT` twice.
- I had to pass the obtained `keyID` down to the `createPublicKeyFromJWKS` method in order to be able to find the matching JWK.

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
LGTM, Need to test with MP TCK Runner.

**Comment by jGauravGupta** [comment]
Jenkins test MicroProfile

**Comment by arjantijms** [comment]
Jenkins test MicroProfile

**Comment by arjantijms** [comment]
@MeroRai 
Can you test with the MP TCK Runner?

**Comment by MeroRai** [comment]
Pass the MircoProfile TCK on the Payara Server. Although the TCK Runner will need to be updated once the PR has been merged. I believe @jGauravGupta already did it but it has been revert back until this PR is merged.

**Comment by smillidge** [comment]
Fixes #3795

**Comment by Pandrex247** [comment]
Need to make sure both repos are updated at the same time.

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Pull request merged**
