### PR TITLE
FISH-6507: Remove admin gui from static embedded shell

### PR DESCRIPTION
**Pull request by pdudits**
## Description

Alternative to #5922, removes admingui from classpath of static embedded shell that TCK uses as embedded container.

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins is currently quite busy crunching through various other full TCK runs, but I'll add this to the list.
As an aside I was also looking at doing something like this but more from a "pull all of these admingui plugins out of these packages and have dedicated packages for them" POV.

**Comment by Pandrex247** [comment]
Passed everything but JACC TCK - I don't think your branch is up to date.

**Comment by Pandrex247** [comment]
I have kicked off another full run after updating your branch for you.

**Review by Pandrex247 — APPROVED** [review]
Passes the TCK (barring the signature test)

**Comment by pdudits** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Merging for the Alpha release

**Pull request merged**
