### PR TITLE
PAYARA-166 hogging threads are now identified with a CPU usage percentage

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
Failure is due to a new unrelated test failing. Will submit for testing again when this is fixed

**Comment by MeroRai** [comment]
jenkins test please

**Pull request merged**
