### PR TITLE
PAYARA-4104 Fixes NPE in monitoring console startup in case hazelcast is disabled

### PR DESCRIPTION
**Pull request by jbee**
PR fixes error reported in #4186 .

### CODE REVIEW

**Comment by jbee** [comment]
jenkins test please

**Comment by jbee** [comment]
@AlanRoth Does not look related to me but we can wait with the merge and look for more insight.

**Comment by AlanRoth** [comment]
@jbee If you think it's unrelated, you're free to merge. :)

**Comment by svendiedrichsen** [comment]
@jbee Would this fix lead to a release of Payara 5.193.1?

**Comment by dmatej** [comment]
@AlanRoth  Usually this is caused by one of these:

- JDK11 as default java program (no AS_HOME or JAVA_HOME set)
- some instance is already running

**Comment by jbee** [comment]
@svendiedrichsen I have a chat internal on a 5.193.1 release.

**Comment by jbee** [comment]
@svendiedrichsen We feel that turning of hazelcast on DAS is so uncommon that a release isn't justified. There is an easy enough workaround in removing the `monitoring-console-core.jar` from `glassfish/modules` that can be applied by those that use the setting for some reason.

**Comment by svendiedrichsen** [comment]
> @svendiedrichsen We feel that turning of hazelcast on DAS is so uncommon that a release isn't justified. There is an easy enough workaround in removing the `monitoring-console-core.jar` from `glassfish/modules` that can be applied by those that use the setting.

Thanks for the info, @jbee .

**Pull request merged**
