### PR TITLE
FiSH-156 Ignore bad test

### PR DESCRIPTION
**Pull request by MarkWareham**
## Description
Ignores bad test until rectified

### CODE REVIEW

**Comment by MarkWareham** [comment]
jenkins test please

**Comment by MarkWareham** [comment]
This is not fixing the problem. This is ignoring the test until it is fixed

**Comment by AlanRoth** [comment]
There's a bug that needs fixing, but while its not fixed it is obfuscating test results

**Comment by MarkWareham** [comment]
jenkins test please

**Comment by MarkWareham** [comment]
> There's a bug that needs fixing, but while its not fixed it is obfuscating test results

To put it more clearly, tests are only valid if they work correctly

**Comment by MarkWareham** [comment]
jenkins test please

**Pull request merged**
