### PR TITLE
PAYARA-406 Wrong thread name in server.log

### LINKED ISSUE #500: Wrong thread name in server.log
[PAYARA-406](https://jira.c2b2.co.uk/browse/PAYARA-406)

### PR DESCRIPTION
**Pull request by Pandrex247**
Fixes #500

### CODE REVIEW

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
There's some weird maven error on the build of this pull request can you investigate

**Comment by Pandrex247** [comment]
payara test please

**Comment by Pandrex247** [comment]
payara test please

**Pull request merged**
