### PR TITLE
FISH-7331 [JDK17] Fixes HK2 config for compilation

### PR DESCRIPTION
**Pull request by ctabin**
While trying to [build](https://docs.payara.fish/community/docs/General%20Info/Build%20Instructions.html) Payara from source, after fixing the bundle plugin (#6262), I hit the following error:

```
[ERROR] Manifest fish.payara.server.core.hk2:hk2-config:glassfish-jar:6.2023.5-SNAPSHOT : package info for org.jvnet.hk2.config attribute [version~='6.2023.5 org.jvnet.hk2.config.provider.annotations'], key must be an EXTENDED (CORE1.3.2 [-.\w]+). From null
[ERROR] Manifest fish.payara.server.core.hk2:hk2-config:glassfish-jar:6.2023.5-SNAPSHOT : package info for org.jvnet.hk2.config attribute [version~~='6.2023.5'], key must be an EXTENDED (CORE1.3.2 [-.\w]+). From null
[ERROR] Error(s) found in manifest configuration
```

Some commas were missing but I tried to align the same declaration as in the other `osgi.bundle` files.

### CODE REVIEW

**Comment by ctabin** [comment]
Jenkins test please

**Comment by ctabin** [comment]
Jenkins test please

**Comment by JamesHillyard** [comment]
Hi @ctabin,

Thank you again for this contribution, I have raised the internal issue `FISH-7331` to track this improvement for our development team to review.

**Comment by JamesHillyard** [comment]
Hi @ctabin,

Before we can accept these changes, could you please sign the Payara CLA and send it back to us: [Payara/PayaraCLA.pdf at master · payara/Payara](https://github.com/payara/Payara/blob/master/PayaraCLA.pdf)

**Review by Pandrex247 — APPROVED** [review]
LGTM! Reviewed it in conjunction with https://github.com/payara/Payara/pull/6262 
Thanks 🙂

**Pull request merged**
