### PR TITLE
FISH-7959: Fixes MultiRelease JAR lookup for specific version classes

### LINKED ISSUE #6452: Bug Report: [JDK21] MultiRelease JAR in EAR (with Lucene)/FISH-7959
### Brief Summary

Hello,

We are checking our application (Jakarata EE10 with payara-embedded-all 6.2023.9) with the JDK21. All seems to run smoothly except for [Lucene](https://lucene.apache.org/), which does not find a class during its lookup:

```
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.store.MemorySegmentIndexInputProvider
        at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:807)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:689)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:2869)
        at org.apache.lucene.store.MMapDirectory.lookupProvider(MMapDirectory.java:422)
```

All the libraries related to Lucene are included in our EAR.

This works fine with the JDK17 because the *lucene-core* dependency was not a multi-release JAR before JDK19. However, since then there are some classes in `META-INF/versions` and the lookup in Payara fails.

```
META-INF/services/
META-INF/services/org.apache.lucene.analysis.TokenizerFactory
META-INF/services/org.apache.lucene.codecs.Codec
META-INF/services/org.apache.lucene.codecs.DocValuesFormat
META-INF/services/org.apache.lucene.codecs.KnnVectorsFormat
META-INF/services/org.apache.lucene.codecs.PostingsFormat
META-INF/services/org.apache.lucene.index.SortFieldProvider
META-INF/versions/
META-INF/versions/19/
META-INF/versions/19/org/
META-INF/versions/19/org/apache/
META-INF/versions/19/org/apache/lucene/
META-INF/versions/19/org/apache/lucene/store/
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInput$MultiSegmentImpl.class
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInput$SingleSegmentImpl.class
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInput.class
META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInputProvider.class
META-INF/versions/20/
META-INF/versions/20/org/
META-INF/versions/20/org/apache/
META-INF/versions/20/org/apache/lucene/
META-INF/versions/20/org/apache/lucene/internal/
META-INF/versions/20/org/apache/lucene/internal/vectorization/
META-INF/versions/20/org/apache/lucene/internal/vectorization/PanamaVectorUtilSupport.class
META-INF/versions/20/org/apache/lucene/internal/vectorization/PanamaVectorizationProvider.class
META-INF/versions/20/org/apache/lucene/store/
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInput$MultiSegmentImpl.class
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInput$SingleSegmentImpl.class
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInput.class
META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInputProvider.class
META-INF/versions/21/
META-INF/versions/21/org/
META-INF/versions/21/org/apache/
META-INF/versions/21/org/apache/lucene/
META-INF/versions/21/org/apache/lucene/store/
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInput$MultiSegmentImpl.class
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInput$SingleSegmentImpl.class
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInput.class
META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInputProvider.class
```

### Expected Outcome

The lookup of the classes inside Lucene should work fine.

### Current Outcome

It crashes with a `ClassNotFoundException`.

### Reproducer

You will find a reproducer [here](https://github.com/ctabin/gf-test-lucene).

### Operating System

Linux Debian

### JDK Version

OpenJDK 21

### Payara Distribution

Payara Embedded All

### PR DESCRIPTION
**Pull request by ctabin**
## Description
This PR fixes lookup of classes in MultiRelease JARs for version-specific classes. Fixes #6452.

### Testing Performed
Tested on my [reproducer](https://github.com/ctabin/gf-test-lucene)

### Testing Environment
OpenJDK 21, Linux Debian
Azul JDK 21, Ubuntu 20.04

### CODE REVIEW

**Comment by ctabin** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
@ctabin I simplify a little the way to use the JarEntry, now it is more simple to create the JarFile using following constructor: JarFile(File, boolean, int, Runtime.Version), here more documentation:

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/jar/JarFile.html#%3Cinit%3E(java.io.File,boolean,int,java.lang.Runtime.Version)

after testing with your reproducer the test is passing with success:
`
INFO: Shutdown procedure finished
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.816 s - in ch.astorm.launcher.LuceneDeploymentTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.3.0:jar (default-jar) @ launcher ---
[INFO] Building jar: /home/alfv83/projects/gf-test-lucene/launcher/target/launcher-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GF Project (Main) 1.0.0-SNAPSHOT:
[INFO]
[INFO] GF Project (Main) .................................. SUCCESS [  0.282 s]
[INFO] GF Project (API) ................................... SUCCESS [  1.272 s]
[INFO] GF Project (EJB) ................................... SUCCESS [  1.312 s]
[INFO] GF Project (WAR) ................................... SUCCESS [  0.443 s]
[INFO] GF Project (EAR) ................................... SUCCESS [  0.676 s]
[INFO] GF Project (Launcher) .............................. SUCCESS [ 15.187 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.294 s
[INFO] Finished at: 2023-10-27T13:12:23-06:00
[INFO] ------------------------------------------------------------------------
`

**Comment by ctabin** [comment]
@breakponchito Thank you very much !

**Review by luiseufrasio — APPROVED** [review]
LGTM!

[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.3.0:jar (default-jar) @ launcher ---
[INFO] Building jar: C:\code\reproducers\gf-test-lucene\launcher\target\launcher-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GF Project (Main) 1.0.0-SNAPSHOT:
[INFO]
[INFO] GF Project (Main) .................................. SUCCESS [  0.277 s]
[INFO] GF Project (API) ................................... SUCCESS [  1.343 s]
[INFO] GF Project (EJB) ................................... SUCCESS [  1.390 s]
[INFO] GF Project (WAR) ................................... SUCCESS [  0.665 s]
[INFO] GF Project (EAR) ................................... SUCCESS [  1.535 s]
[INFO] GF Project (Launcher) .............................. SUCCESS [ 16.658 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.027 s
[INFO] Finished at: 2023-11-01T14:03:22-03:00
[INFO] ------------------------------------------------------------------------

**Pull request merged**
