### PR TITLE
Expired Certificates

### PR DESCRIPTION
**Pull request by Pandrex247**
Title.

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by kalinchan** [comment]
When Payara is built, expired certificates are removed automatically like you mentioned previously.

**Comment by pzygielo** [comment]
> When Payara is built, expired certificates are removed automatically like you mentioned previously.

Could
- #5625

be closed then?
Q: Where was FISH-6107 implemented?

**Comment by kalinchan** [comment]
> > When Payara is built, expired certificates are removed automatically like you mentioned previously.
> 
> Could
> 
> * [Please remove expired certificates from distribution/FISH-6107 #5625](https://github.com/payara/Payara/issues/5625)
> 
> be closed then? Q: Where was FISH-6107 implemented?

This functionality has been present for a while, from my understanding, expired certificates are removed from the keystore when a new domain is created. Certificates are also added from the current JDK.

**Comment by Pandrex247** [comment]
Expired certificates Should™ be removed for Payara Server when a new domain is created. I don't believe the same functionality is present for Micro and Embedded.

In this particular case, this PR removes a certificate that expired literally yesterday.

**Comment by Pandrex247** [comment]
@kalinchan 
Just checked locally. The code I previously spoke about on your PR works for Payara Server, but doesn't for Micro

**Review by kalinchan — APPROVED** [review]

**Pull request merged**
