### PR TITLE
Implements enhancement #2529 ( PAYARA-2722 ) - Payara4

### PR DESCRIPTION
**Pull request by kantor1974**
Hi Payara team,

I have implemented this enhancement based on Hazelcast healthcheck "noisy" feature.
I have made a choice to make this function configurable (switch enable/disable) by each notifier one by one (It's enabled by default, because of compatibility)

Yours sincerely,
Kantor1974

### CODE REVIEW

**Comment by smillidge** [comment]
Hi thanks for your contribution. In order to merge the PR we need to have a signed contributor license agreement on file. Please see https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins quick test payara 4

**Comment by lprimak** [comment]
@kantor1974 I noticed there are changes in the PR that aren't really changes.
Did you re-format every file somehow?  This makes it very difficult to figure out what exactly changed.
Can you please do something to this PR so not every file you touched, that every line isn't changed?  Maybe it's windows vs. unix line encoding or something like that?
Thank you.

**Comment by kantor1974** [comment]
@lprimak I hope so the latest commit will be good! I developed with Eclipse Oxigen on Windows, and unfortunetelly I made a mistake with format the code. Sorry!

**Comment by lprimak** [comment]
jenkins quick test payara 4

**Comment by lprimak** [comment]
Looks much better now, thanks!
Now we can actually start reviewing the changes

**Comment by smillidge** [comment]
Fixes #2529 
Allocated internal JIRA PAYARA-2722

**Comment by mulderbaba** [comment]
@kantor1974 thanks for the PR. it looks good at overall, I have some minor corrections, will push a commit for them, can you grant access to my username for your brach?
And this only applies for healthcheck and we need to have this implemented for request tracing part as well, looking into it.

**Comment by mulderbaba** [comment]
jenkins quick test payara 4

**Pull request merged**
