### PR TITLE
FISH-6963 Make it easier to locate expired certificate

### PR DESCRIPTION
**Pull request by pzygielo**
Similar to
- eclipse-ee4j/glassfish#24218

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by JamesHillyard** [comment]
Hi @pzygielo,

This issue is currently being tracked under the internal id `FISH-6963` for our engineering team to review these changes. Your continued patience in the meantime is much appreciated.

**Comment by JamesHillyard** [comment]
Jenkins test please

**Comment by pzygielo** [comment]
Thanks for checking @JamesHillyard.

**Comment by pzygielo** [comment]
I've noticed that just now that I've used +-wrong Author (from gitlab) in the commit.
I'd like to amend that and force push the same change with new values.
Please let me know if that's ok.

**Comment by JamesHillyard** [comment]
That shouldn't be a problem for either of the two PRs you have open, please feel free to make the amendments

**Comment by JamesHillyard** [comment]
Jenkins test please

**Comment by pzygielo** [comment]
Jenkins failure:
```
Caused by: org.apache.maven.wagon.TransferFailedException: Transfer failed for https://repo.eclipse.org/content/groups/microprofile/net/minidev/accessors-smart/2.4.2.payara-p1/accessors-smart-2.4.2.payara-p1.pom 503 Service Unavailable
```

**Review by JamesHillyard — APPROVED** [review]

**Comment by JamesHillyard** [comment]
Thank you very much for this contribution, we much appreciate the improvement, and your patience in getting these changes reviewed

**Pull request merged**
