### PR TITLE
PAYARA-2162 Added evaluation of commands which erroneously trigger re…

### PR DESCRIPTION
**Pull request by michaelranaldo**
…start-required on instances with dynamic-reconfiguration disabled

### CODE REVIEW

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
Tested that restarting a domain with an unavailable password file (if a password file was used to start it) rightfully fails as per GF-16197, which means that this can now be merged.

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by lprimak** [comment]
Fixes #2019

**Pull request merged**
