### PR TITLE
PAYARA-3266 Using environment variable in logging.properties

### PR DESCRIPTION
**Pull request by Ykus**
Now it's possible to use references to environment variables in logging.properties.

${ENV=XXX}, where XXX is environment variable

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by Ykus** [comment]
Merge conflict resolved

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Fixes #3161

**Pull request merged**
