### PR TITLE
Payara 577 get weld 2.3.x working on payara

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
added another commit into this PR for upgrading jboss-logging dependency in order to loose the log4j dependency that was introduced in the previous version

**Comment by smillidge** [comment]
Hi @mulderbaba this now has conflicts I may have not merged in the correct order. Can you resolve them please?

**Comment by mulderbaba** [comment]
should be ok now @smillidge

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Pull request merged**
