### PR TITLE
GlassFish cherry pick July

### PR DESCRIPTION
**Pull request by Pandrex247**
GlassFish upstream cherry-pick for July

### CODE REVIEW

**Comment by smillidge** [comment]
We need to ensure that all Eclipse patches we have in our Eclpise patched projects are in the Eclipselink referenced in the commit and if not reapply.

**Comment by Pandrex247** [comment]
From looking at their bugzilla, it doesn't look like the bug we patched in issue #241 is incorporated into this release candidate.
Do we want to create a separate task for re-patching 2.6.1-RC1? It looks like all of the patching was done in personal repositories, so I can't easily and quickly re-patch it myself; I don't have the patches!

**Comment by smillidge** [comment]
Yep create a new issue and mark it as upstream bug and 4.1.153 release

**Comment by Pandrex247** [comment]
Missed a couple of commits.
Also reverted the Eclipselink upgrade for now.

**Comment by Pandrex247** [comment]
payara test please

**Comment by Pandrex247** [comment]
payara test please

**Pull request merged**
