### PR TITLE
remove smart quotes in authRealm description

### PR DESCRIPTION
**Pull request by hdhoang**
the closing one is corrupted

### CODE REVIEW

**Comment by smillidge** [comment]
@hdhoang  Thanks for your contribution it is appreciated. Can you send over a CLA so we can merge the pull request. 
See https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md

**Comment by smillidge** [comment]
jenkins test please

**Comment by hdhoang** [comment]
I'll submit the CLA on monday.

I have no idea how `adminconsole_tests` failed with this patch. Any pointer is appreciated.

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by hdhoang** [comment]
I have sent my CLA to payara.

**Comment by davidweaver** [comment]
jenkins test please

**Pull request merged**
