### PR TITLE
QACI-530 QuickLook test fixes

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Fixes numerous errors in QickLook

### New tests
Added back previously disabled tests

### Testing Performed
QuickLook test

### Testing Environment
JDK 8 / mac

## Notes for Reviewers
This includes other PRs and I still need to remove those other commits

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Review by cubastanley — APPROVED** [review]
LGTM

**Comment by MarkWareham** [comment]
were retries removed from internal testing also?

**Review by MarkWareham — APPROVED** [review]
LGTM.

**Review by dmatej — APPROVED** [review]

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Pull request merged**
