### PR TITLE
PAYARA-1740 Deployment and initialization order for Payara 4 (reference only)

### PR DESCRIPTION
**Pull request by lprimak**
- Refactor Payara Server and Micro initiation order
- Facilitate Hazelcast initialization and usage of application's classes

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
Jenkins, would you kindly?

**Comment by arjantijms** [comment]
Jenkins, would you kindly?

**Comment by lprimak** [comment]
Jenkins, would you kindly?

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
Superseded by #1701

**Pull request closed without merging**
