### PR TITLE
common-util: replacing synchronized classes with their unsynchronized counter parts

### PR DESCRIPTION
**Pull request by svendiedrichsen**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by svendiedrichsen** [comment]
@MeroRai I have fixed the code according to your reviews. Also added latest master changes.

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by svendiedrichsen** [comment]
@MeroRai As always. My pleasure! ;)

**Pull request merged**
