### PR TITLE
FISH-108 Add command to clean Jbatch repository

### PR DESCRIPTION
**Pull request by Cousjava**
## Description
This is a feature.

### Testing Performed
Using example app which performs an execution, ran command then went to the admin console server -> batch -> executions and checked that they were deleted.

### Test suites executed
- Java EE7 Samples

### Testing Environment
Zulu JDK 1.8_272 on Ubuntu 20.10 with Maven 3.6.3

## Documentation
Added man pages to PR.

## Notes for Reviewers
See also `purge-jbatch-repository` command which already exists to delete all executions.
This is the community PR for payara/payara-enterprise#272

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Comment by lprimak** [comment]
jenkins test

**Pull request merged**
