### PR TITLE
PAYARA-1012 added requesttracing package

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by phillipross** [comment]
Will we perhaps see this in a short term 153 patch?  Without request tracking, the 153 embedded artifacts fail with arquillian

**Comment by smillidge** [comment]
try this one http://search.maven.org/#artifactdetails%7Cfish.payara.extras%7Cpayara-embedded-all%7C4.1.1.163.0.1%7Cjar

**Comment by phillipross** [comment]
Yep, this fixes it... arquillian tests are all happy again.  thanks!

**Pull request merged**
