### PR TITLE
PAYARA-3034 streamline auth (refactor auth code)

### PR DESCRIPTION
**Pull request by arjantijms**
PAYARA-3034 Start with streamlining authentication flow

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Note: this doesn't add new functionality, but is a refactoring/clean code PR.

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
enkins, quick test Payara 5 please

**Comment by MarkWareham** [comment]
Jenkins, quick test Payara 5 please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins never listens to me.

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins new test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Pull request merged**
