### PR TITLE
PAYARA-2356-increase-delay-on-secret-dir-test

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by arjantijms** [comment]
This is sort of a duplicate of https://github.com/payara/Payara/pull/2225 ;)

Best way btw seems to be to add the following after the write

>FileTime nowplus10 = FileTime.fromMillis(System.currentTimeMillis() + 10000);
>Files.setLastModifiedTime(file1, nowplus10);

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Pull request merged**
