### PR TITLE
PAYARA-1556 Upgraded Derby

### PR DESCRIPTION
**Pull request by michaelranaldo**

### CODE REVIEW

**Comment by michaelranaldo** [comment]
This won't pass on JDK7 tests

**Comment by michaelranaldo** [comment]
Jenkins, quick test JDK8 please

**Comment by michaelranaldo** [comment]
Jenkins, quick test JDK8 please

**Comment by michaelranaldo** [comment]
Jenkins, quick test JDK8 please

**Comment by Pandrex247** [comment]
It's failing to find/download soteria

**Comment by michaelranaldo** [comment]
Requires https://github.com/payara/Payara/pull/1779 before P-5 build will stablize

**Comment by michaelranaldo** [comment]
Jenkins, JDK8 test please

**Comment by michaelranaldo** [comment]
Jenkins, quick test JDK8 please

**Comment by michaelranaldo** [comment]
Jenkins, quick test JDK8 please

_Sent from my Sony F8331 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by michaelranaldo** [comment]
Jenkins, quick test Payara 5 please

**Comment by michaelranaldo** [comment]
Jenkins, quick test Payara 5 please

**Pull request closed without merging**
