### PR TITLE
PAYARA-263 Autobinding port precedence warnings

### PR DESCRIPTION
**Pull request by Pandrex247**
Adds in warnings for when autobinding or setting ports is overriding a domain.xml.

Also cleans up the code formatting to be of one consistent style, and removes walkthrough comments.

### CODE REVIEW

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
This now has branch conflicts can you fix please.

**Comment by Pandrex247** [comment]
Rebased and conflicts resolved.

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
conflicts again

**Comment by Pandrex247** [comment]
Rebased again

**Comment by smillidge** [comment]
jenkins test please

**Pull request merged**
