### PR TITLE
Update Hzl API to 4.1, include tenant control, add APIs for EE context

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Context for this is https://github.com/hazelcast/hazelcast/issues/10875 and all the issues mentioned within this issue as well.
Main feature is that Hazelcast Cache / Map / Queue etc. now work with Java EE constructs, and CDI beans, in Payara Data Grid as well.

### Blockers
https://github.com/hazelcast/hazelcast/pull/17184 needs to be merged and Hz 4.1 released

### New tests
Got https://github.com/payara/Payara/issues/759 / https://github.com/bgjug/jcache-workshop to work in clustered environment using Payara Micro and Server mix.
Most of this PR is removing a whole bunch of Proxy classes that are no longer needed

### Testing Performed
All test suites pass. Manual testing with distributed app mentioned above

### Testing Environment
JDK 8

## Documentation
Bug fixes, features work in more environments

### CODE REVIEW

**Comment by lprimak** [comment]
Payara Hazelcast Tenant (main addition)

https://github.com/payara/Payara/blob/e1c053446acc7b5f499c47b24e9e837adccd1280/nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenant.java

**Comment by lprimak** [comment]
depends on https://github.com/payara/Payara/pull/4762

**Comment by lprimak** [comment]
jenkins test

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by lprimak** [comment]
@jGauravGupta it's not going to work until Hazelcast 4.1 is released

**Pull request closed without merging**
