### PR TITLE
FISH-6355: disabling trace method from http OPTIONS call

### PR DESCRIPTION
**Pull request by breakponchito**
Disabling TRACE method from http OPTIONS call
## Description

This is a fix for a bug that returns the TRACE method available from an http OPTIONS call when the following property is set to false:

- configs.config.server-config.network-config.protocols.protocol.http-listener-{listener number}.http.trace-enabled

### Testing Environment

Windows 11, Azul JDK 8, Maven 3.8.3

### CODE REVIEW

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by kalinchan** [comment]
Is this going into the correct branch?

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
