### PR TITLE
NullPointerException bugfix related to #1632

### PR DESCRIPTION
**Pull request by esafzay**
I was facing a similar exception reported in this issue https://github.com/payara/Payara/issues/1632

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
CLA needs to be signed prior to merge

**Comment by smillidge** [comment]
Hi Can you sign a CLA so we can merge the PR. YOu can find a CLA here https://github.com/payara/Payara/blob/master/PayaraCLA.pdf

**Comment by esafzay** [comment]
[PayaraCLA.PDF](https://github.com/payara/Payara/files/1083520/PayaraCLA.PDF)

**Comment by smillidge** [comment]
Thanks got it. I'll delete it from here for your privacy.

**Pull request merged**
