### PR TITLE
PAYARA-1146 Hazelcast serialization

### PR DESCRIPTION
**Pull request by lprimak**
fixed problems with classloading and serialization for Hazlecast due to OSGi restrictions

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
This PR now fails when rebased against the current master branch, as does #1254.

Getting some HK2 errors regarding run levels, which are possibly stemming from class not found errors:

```
java.lang.NoClassDefFoundError: javax/jms/JMSException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getDeclaredConstructors(Class.java:2020)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1310)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1306)
...
Caused by: java.lang.ClassNotFoundException: javax.jms.JMSException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
MultiException stack 2 of 2
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
        implementation=fish.payara.notification.jms.JmsNotifierService
        name=service-jms
        contracts={fish.payara.notification.jms.JmsNotifierService,fish.payara.nucleus.notification.service.QueueBasedNotifierService,fish.payara.nucleus.notification.service.BaseNotifierService}
        scope=org.glassfish.hk2.runlevel.RunLevel
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=runLevelValue={10}
        rank=0
        loader=org.glassfish.hk2.bootstrap.impl.Hk2LoaderPopulatorPostProcessor$1@2ed2d9cb
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=877
        locatorId=0
        identityHashCode=151515831
        reified=false)
...
```

**Comment by mulderbaba** [comment]
@Pandrex247 should be related to my mega notification services PR, I'm trying this branch on my local now.

**Comment by Pandrex247** [comment]
@mulderbaba @lprimak Micro is actually just broken on the master branch atm, it's not this PR that does it. It's probably worth creating a new PR to fix it rather than tacking the fix on to another one.

**Comment by smillidge** [comment]
I think I may have already fixed this already in my mega Payara Micro PR which is due soon.

**Pull request merged**
