### PR TITLE
FISH-732 Fixes #4856 improved message in stacktrace

### LINKED ISSUE #4856: Misconfiguration of metrics.xml produces stacktraces that are not helpful. /FISH-732
# Description #
----------
For example copypaste of metadata element that causes duplicate key with different configuration produces following stack trace that does not help to fix the wrong configuration without digging into source code of Payara.

## Expected Outcome
  Metadata ['some.configured.key {some attributes of that key}'] already registered, does not match provided ['some.configured.key {some attributes of duplicated key}']. Check metrics.xml for duplicities.

## Current Outcome

```
[2020-08-27T15:34:09.389+0200] [Payara 5.2020.4] [WARNING] [] [fish.payara.microprofile.metrics.jmx.MBeanMetadataHelper] [tid: _ThreadID=103 _ThreadName=http-thread-pool::http-listener-1(16)] [timeMillis: 1598535249389] [levelValue: 900] [[
  Metadata ['fish.payara.microprofile.metrics.jmx.MBeanMetadata@50c21e27'] already registered, does not match provided ['fish.payara.microprofile.metrics.jmx.MBeanMetadata@fabb382e']
java.lang.IllegalArgumentException: Metadata ['fish.payara.microprofile.metrics.jmx.MBeanMetadata@50c21e27'] already registered, does not match provided ['fish.payara.microprofile.metrics.jmx.MBeanMetadata@fabb382e']
	at fish.payara.microprofile.metrics.impl.MetricRegistryImpl.checkReusableMetadata(MetricRegistryImpl.java:502)
	at fish.payara.microprofile.metrics.impl.MetricRegistryImpl.register(MetricRegistryImpl.java:467)
	at fish.payara.microprofile.metrics.impl.MetricRegistryImpl.register(MetricRegistryImpl.java:444)
	at fish.payara.microprofile.metrics.jmx.MBeanMetadataHelper.registerMetadata(MBeanMetadataHelper.java:116)
	at fish.payara.microprofile.metrics.MetricsService.initMetadataConfig(MetricsService.java:349)
	at fish.payara.microprofile.metrics.MetricsService.reregisterMetadataConfig(MetricsService.java:365)
	at fish.payara.microprofile.metrics.rest.MetricsResource.processRequest(MetricsResource.java:101)
	at fish.payara.microprofile.metrics.rest.MetricsResource.doGet(MetricsResource.java:247)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]
```

## Context (Optional)

If custom implementation of MBeanMetadata#toString is sufficient fix, then I can make pull request.

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Full 
- **JDK Version**: OpenJDK 11 
- **Operating System**: RedHat 7.8

### PR DESCRIPTION
**Pull request by sgflt**
### Testing Performed

Manual testing of provided use case.

```
2020-10-02T15:35:01.711+0200] [Payara 5.2020.5-SNAPSHOT] [WARNING] [] [fish.payara.microprofile.metrics.jmx.MBeanMetadataHelper] [tid: _ThreadID=62 _ThreadName=payara-executor-service-task] [timeMillis: 1601645701711] [levelValue: 900] [[
  Metadata ['MBeanMetadata{
	 mBean='amx:pp=/mon/server-mon[server],type=transaction-service-mon,name=transaction-service/committedcount#count',
	 dynamic=true,
	 name='jdbc.connection.pool.numconnfree',
	 displayName='numconnfreePool',
	 description='The total number of already used connections.',
	 unit='none',
	 type='counter',
	 reusable=false,
	 valid=true,
	 tags=[fish.payara.microprofile.metrics.jmx.XmlTag@70ac0964]
}'] already registered, does not match provided ['MBeanMetadata{
	 mBean='amx:pp=/mon/server-mon[server],type=transaction-service-mon,name=transaction-service/activecount#count',
	 dynamic=true,
	 name='jdbc.connection.pool.numconnfree',
	 displayName='numconnfreePool',
	 description='The total number of free connections in the pool as of the last sampling.',
	 unit='none',
	 type='counter',
	 reusable=false,
	 valid=true,
	 tags=[fish.payara.microprofile.metrics.jmx.XmlTag@7ef163d4]
}']

```

### CODE REVIEW

**Review by jbee — APPROVED** [review]

**Comment by AlanRoth** [comment]
Just for clarity, this PR relates to issue #4856.

**Comment by MeroRai** [comment]
jenkins test please

**Review by dmatej — APPROVED** [review]

**Comment by jbee** [comment]
Look like this is ready to be merged - I leave it to you @MattGill98

**Comment by dmatej** [comment]
@rdebusscher  did something very similar, I'm not sure if those changes are equivalent or if here is something yet better. What do you think, @sgflt, is it worth of your rebase or we can close this PR unmerged now? :)

**Pull request merged**
