### PR TITLE
PAYARA-180 CDI Interceptor api for Request Tracing

### PR DESCRIPTION
**Pull request by mulderbaba**
@smillidge I'll revisit this part after getting your PR in.

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
I've merged my PR so this will need a little rework

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
Hi  can you move it out the nucleus package into somewhere in appserver. Nucleus shouldn't have references to JavaEE apis.

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Pull request merged**
