### PR TITLE
Fix FormAuthenticator corrupting post parameters.

### LINKED ISSUE #2318: Corrupted parameters in FormAuthenticator.restoreRequest for POST requests
# Description #
----------
If you have a form that send data via POST request to a page which is form-protected, if you're not logged it, the login page appears, and after login it continues with your submit.

In the process, org.apache.catalina.authenticator.FormAuthenticator corrupts one of your parameters by filling it with 0 at the end of the string.

If you use a get submit it works fine.
If you are already logged in it works fine (FormAuthenticator is not involved)

## Expected Outcome

You do the submit, login into the app and get the right parameters on the receving page.

## Current Outcome

One of the parameters values has a lot of "invisible" data (junk) at the end.

## Steps to reproduce

configure your app to have a form protected receive.jsp page
(full web.xml as example)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
	version="3.0">
	<display-name>example</display-name>
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>web application pages</web-resource-name>
			<url-pattern>/receive.jsp</url-pattern>
		</web-resource-collection>
		<auth-constraint>
			<role-name>examplerole</role-name>
		</auth-constraint>
	</security-constraint>
	<login-config>
		<auth-method>FORM</auth-method>
		<form-login-config>
			<form-login-page>/login.jsp</form-login-page>
			<form-error-page>/login.jsp?error=true</form-error-page>
		</form-login-config>
	</login-config>
	<security-role>
		<description>Example Role</description>
		<role-name>examplerole</role-name>
	</security-role>

</web-app>
```

make a unprotected form page which makes a post to the protected page

```html
	<form method="post" action="receive.jsp">
		<input type="text" id="name" name="name" value="example"/>
		<input type="submit"/>		
	</form>
```

read the parameter in the protected page
```java
    String param = request.getParameter("name");
    byte[] bytes = param.getBytes();
```
param has a lot of "zeros" at the end.

in short:
1. You must be logged out
2. use your browser to request the unprotected form page (index.jsp)
3. fill the data, submit the form
4. You are presented the login form: make the login.
5. After successful login you are redirected to receive.jsp, last parameter is corrupted

### Samples

[authenticator-bug-sampleapp.zip](https://github.com/payara/Payara/files/1661743/authenticator-bug-sampleapp.zip)

Sample app: eclipse project, with the files:

WebContent/WEB-INF/web.xml  
WebContent/WEB-INF/glassfish-web.xml
WebContent/WEB-INF/index.jsp (unprotected form)
WebContent/WEB-INF/receive.jsp (protected jsp which receives the data)
WebContent/WEB-INF/login.jsp (simple login page) 

To run the sample, you must have a Payar user in a group called "examplerole", 

## Proposed solution

After some research, I've found the bug in org.apache.catalina.authenticator.FormAuthenticator, at line ~450

```java
ByteChunk body = saved.getBody();

if (body != null) {
    request.replayPayload(body.getBytes());
```

The problem is ByteChunk.getBytes() returns the internal buffer, witch is greater than the current stored data.

I've modified and sucessfully tested this change, to get a byte[] of the right size:

```java
ByteChunk body = saved.getBody();

if (body != null) {
    byte[] tempData = body.getBytes();
    byte[] data = new byte[body.getLength()];
    System.arraycopy(tempData, body.getStart(), data, 0, data.length);
    request.replayPayload(data);

```

## Environment ##

- **Payara Version**: 4.1.2.174
- **Edition**: Full
- **JDK Version**: 8u151 - OpenJDK
- **Operating System**:   Linux
- **Database**:

### PR DESCRIPTION
**Pull request by albfernandez**
Fixes #2318

### CODE REVIEW

**Comment by albfernandez** [comment]
I've provided a small test application #2318.

I would like to provide a JUnit test case but I'm having troubles setting up "environment" (I don't know how to setup Globals.setDefaultHabitat in a test envirnoment)

**Comment by Cousjava** [comment]
jenkins test please

**Comment by arjantijms** [comment]
Hi, thanks for discovering and reporting this! Before we can accept the PR you must have signed the CLA, or did you already sign it?

As for the test; since one the parameters will be corrupted, I guess it will show as corrupted just as well in a regular Servlet application, right? 

The easiest way for us to test that it's broken in version X and really fixed in X+1 is by means of the Java EE 7 samples test. In this case, it looks like it's only an extra test method in the existing test here: https://github.com/javaee-samples/javaee7-samples/tree/master/servlet/security-form-based

Would be ace if you could do a PR at that repo too with the test demonstrating the issue. Thanks in advance!

**Comment by albfernandez** [comment]
CLA signed and submitted.

I'll make the pull request to javaee7-sameples with the test case.

**Comment by albfernandez** [comment]
I've tried to reproduce the bug in javaee7-samples, but I've a working test working fine: without bug.


I've commited my work to my forked repo:

https://github.com/albfernandez/javaee7-samples/tree/formbased_authentication_corrupts_post_params_payara/servlet/security-form-based

I'll continue investigating next week.

**Comment by albfernandez** [comment]
I've finally "fixed" the test and I've done the PR to javaee7-samples repository

https://github.com/javaee-samples/javaee7-samples/pull/429

**Comment by arjantijms** [comment]
@albfernandez thx a lot!

**Pull request merged**
