### PR TITLE
PAYARA-2920 OpenAPI has Hardcoded 8080 Port

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Not yet, I will check the MP TCK runner.

**Comment by jGauravGupta** [comment]
Hi @MattGill98,

All tck passed.
> Tests run: 222, Failures: 0, Errors: 0, Skipped: 0

**Pull request merged**
