### PR TITLE
PAYARA-2383 Enabled ANSI coloured logs by default

### PR DESCRIPTION
**Pull request by Cousjava**
This is for Payara Server in verbose mode

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test Payara 5 please

**Comment by smillidge** [comment]
Jenkins quick test payara 5 please

**Comment by arjantijms** [comment]
Jenkins quick test payara 5 please

**Comment by arjantijms** [comment]
Jenkins quick test payara 5 please

**Pull request merged**
