### PR TITLE
PAYARA-3295 Upgrade hibernate-validator to 5.4.2.Final (Payara 4.x) 

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
v5.4.2.Final should be patched with correct MANIFEST.MF, here the ticket for v5.2.4.Final patch https://payara.atlassian.net/browse/PAYARA-1545

**Comment by arjantijms** [comment]
Jenkins test

**Comment by arjantijms** [comment]
Fails with:

```
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.hibernate:hibernate-validator:jar:payara-p1:5.4.2.Final in jvnet-nexus-releases (https://maven.java.net/content/repositories/releases/)
```

**Comment by jGauravGupta** [comment]
Hi @arjantijms ,

I had created the ticket [PAYARA-3448](https://payara.atlassian.net/browse/PAYARA-3448) to patch v5.4.2.Final, Earlier @mulderbaba did similar fix for [Manifest.mf related issue](https://payara.atlassian.net/browse/PAYARA-1545) and patched hibernate-validator, so helping for this too.

**Comment by mulderbaba** [comment]
Jenkins test

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Closing the obsolete PR for v5.4.2.Final as quicklook test are failing and v5.4.3.Final is released.

**Pull request closed without merging**
