### PR TITLE
PAYARA-1393 Deploy without checking the database

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by arjantijms** [comment]
Jenkins, do the thing!

**Comment by lprimak** [comment]
Jenkins, do the thing!

**Comment by lprimak** [comment]
Jenkins, do the thing!

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
Hi this is failing can you review?

**Comment by jGauravGupta** [comment]
Locally test are working , I will go through the jenkins log again.

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Hi @smillidge ,

I tried it with Payara test, build is successful. I am sure, this failure is caused by jenkins.

**Comment by smillidge** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Another PR #1736 jenkins test are passed successful with the same code. So closing this #1654 PR.

**Pull request closed without merging**
