### PR TITLE
PAYARA-2578 CDI roles Extension on Payara 4 doesn't have Arjan's rework

### PR DESCRIPTION
**Pull request by MeroRai**

### CODE REVIEW

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
Jenkins, quick test Payara 4 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by MeroRai** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Pull request merged**
