### PR TITLE
Level.FINE added for logging values below GOOD.

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
This PR is failing to build

**Comment by mulderbaba** [comment]
jenkins test please

**Pull request merged**
