### PR TITLE
PAYARA-1543 admin console shows restart required when a thread pool i…

### PR DESCRIPTION
**Pull request by Cousjava**
…s reconfigured and monitoring is enabled

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by lprimak** [comment]
The conflicts need to be resolved

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Pull request merged**
