### PR TITLE
PAYARA-4122 Set HK2 version to 2.6.1.payara-p1

### PR DESCRIPTION
**Pull request by Cousjava**
Fix for osgi global lock to resolve payara-micro-service

payara/patched-src-hk2#8
payara/Payara_PatchedProjects#271

### CODE REVIEW

**Comment by cubastanley** [comment]
Jenkins test please

**Comment by dmatej** [comment]
The HK2 branch is broken, there are two poms with 2.6.2-SNAPSHOT version.

**Comment by dmatej** [comment]
Linked PR: https://github.com/payara/patched-src-hk2/pull/11

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
Waiting for maven artifact to be found, I'd give it another hour or two before running again

**Comment by MattGill98** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by MattGill98** [comment]
Okay I guess wait until the end of the day

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
Anybody have any idea why it's not finding the dependency?

**Comment by cubastanley** [comment]
@MattGill98 I don't believe the new version has been added to patched projects yet due to a request for extra features from David

**Pull request merged**
