### PR TITLE
PAYARA-3383-Use-getInstanceRoot-method-instead-of-getDomainRoot-method

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by mulderbaba** [comment]
jenkins test

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Blocked by roque EJB test:

```
java.lang.ClassNotFoundException: com.sun.enterprise.naming.impl.SerialInitContextFactory
```

**Comment by mulderbaba** [comment]
> Blocked by roque EJB test:
> 
> ```
> java.lang.ClassNotFoundException: com.sun.enterprise.naming.impl.SerialInitContextFactory
> ```

is that a sporadic one?

**Comment by MarkWareham** [comment]
jenkins test please

**Pull request merged**
