### PR TITLE
Payara 457 classloader work

### PR DESCRIPTION
**Pull request by smillidge**
A load of work to fix a number of classloader leaks and filehandles kept open to make Payara Server more robust on redeployment of applications. Should help #434 #445

### CODE REVIEW

**Comment by smillidge** [comment]
payara test please

**Comment by dorpsidioot** [comment]
Is this included in the 154 release, if so I will download and test, since we're experiencing the 'inconsistent module state' issue with a clustered 153 setup.

**Comment by Pandrex247** [comment]
Yes, this will be included in the 154 release.

**Comment by dorpsidioot** [comment]
Can confirm improvements with the latest build, redeploys using autodeploy now work seamlessly and under windows development files are no longer in use when undeploying.

**Pull request merged**
