### PR TITLE
Fix to issue PAYARA-3186: Small null guard added in the case current …

### PR DESCRIPTION
**Pull request by fturizo**
Small NULL guard added to prevent NPE in obscure circumstances where the underlying transaction manager is incomplete.

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
