### PR TITLE
PAYARA-2726 - MicroProfile REST client v1.0.1 (Payara 4.x)

### PR DESCRIPTION
**Pull request by jGauravGupta**
- Microprofile TCK Runner : https://github.com/payara/MicroProfile-TCK-Runners/pull/7
- Jersey branch for Rest Client : https://github.com/payara/patched-src-jersey/commits/2.25.1_mp_rest
- Patched Rest Client API/TCK : https://github.com/payara/patched-src-microprofile-rest-client/tree/1.0.1-patch

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 4 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 please

**Comment by Pandrex247** [comment]
The tests seemed to hit a class cast exception on a couple of the JsonP tests

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 4 please

**Comment by jGauravGupta** [comment]
Weird, locally these tests are passed.

**Pull request merged**
