### PR TITLE
FISH-263 NPE when enabling versioned application with Microprofile Config

### LINKED ISSUE #4737: NPE when enabling versioned application with Microprofile Config
# Bug causing NPE in MP config #
----------

During enabling with multiple versioned applications, NPE appears
```
asadmin deploy guestbook:1.0
asadmin deploy --enabled=false guestbook:1.1
asadmin enable guestbook:1.1
```

```
[2020-06-22T19:52:45.160-0500] [Payara 5.2020] [WARNING] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=317 _ThreadName=GF Domain XML] [timeMillis: 1592873565160] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.NullPointerException
	at fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getAppInfo(ConfigProviderResolverImpl.java:220)
	at fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getConfig(ConfigProviderResolverImpl.java:279)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:105)
	at fish.payara.microprofile.openapi.impl.config.OpenApiConfiguration.<init>(OpenApiConfiguration.java:91)
	at fish.payara.microprofile.openapi.impl.OpenApiService$OpenApiMapping.<init>(OpenApiService.java:267)
	at fish.payara.microprofile.openapi.impl.OpenApiService.event(OpenApiService.java:170)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:368)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:621)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:652)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.enable(ApplicationLifecycle.java:2422)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.enable(ApplicationLifecycle.java:157)
	at com.sun.enterprise.v3.server.ApplicationConfigListener.enableApplication(ApplicationConfigListener.java:283)
	at com.sun.enterprise.v3.server.ApplicationConfigListener.handleAppEnableChange(ApplicationConfigListener.java:215)
	at com.sun.enterprise.v3.server.ApplicationConfigListener.transactionCommited(ApplicationConfigListener.java:175)
	at org.jvnet.hk2.config.Transactions$TransactionListenerJob.process(Transactions.java:367)
	at org.jvnet.hk2.config.Transactions$TransactionListenerJob.process(Transactions.java:358)
	at org.jvnet.hk2.config.Transactions$ListenerNotifier$1.call(Transactions.java:214)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jvnet.hk2.config.Transactions$Notifier$1$1.run(Transactions.java:168)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]
```
## Environment ##

- **Payara Version**: master latest
- **JDK Version**: any

### PR DESCRIPTION
**Pull request by lprimak**
# Description
Fixes #4737
When the applications is loaded, but not enabled, such as the case in versioned applications,
the ```appInfo.getClassLoader()``` may return null. This is why I changed the order of operation to fix the possible NPE

# Important Info
### Blockers
None

# Testing
### New tests
Referenced issue, trivial to test

### Testing Performed
Deployed and enabled versioned applications

### Testing Environment
Any environment, environment is not important

# Documentation
Simple NPE

# Notes for Reviewers
None

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by lprimak** [comment]
hmmm... try again?

**Comment by MeroRai** [comment]
@lprimak, we recently had issues with H2, which is fixed now on the master branch. I believe you will need to sync your branch with the master to pass the test.

**Comment by lprimak** [comment]
thanks, done!

**Comment by MeroRai** [comment]
jenkins test please

**Pull request merged**
