### PR TITLE
Modify Payara version number to adapt to the naming strategy

### PR DESCRIPTION
**Pull request by khasunuma**
Request again, because I had mistake of pull request #1703 

Please ignore #1703

### CODE REVIEW

**Comment by smillidge** [comment]
@arjantijms can you review please

**Comment by Pandrex247** [comment]
Jumping in quickly before this gets merged.
The version should be 5.0.0.173. Note the extra 0.

If we're sticking with our normal versioning of GlassFishVersion.PayaraVersion, we need it there in case Oracle do a GlassFish 5.x.x.
If it's not there, we break "latest" versions, as we could go from 5.0.173, to 5.0.1.174 - the former will always show as the "latest" because it technically has a higher version number

**Comment by arjantijms** [comment]
Another thing worth mentioning, the current number in the Payara-5-173 branch is just a working number. I made a snap decision there, since it's based on Payara 4.1.2.173 and not on GlassFish 5.0. Basically it's our own independent upgrade of Payara 4 to incorporate all new components.

The idea was basically to set the version number right when it gets merged to master, and Payara 4.x gets branched to a rolling new branch, but that was just an idea, no decision has been made there

**Comment by smillidge** [comment]
I agree with @Pandrex247 this should be 5.0.0.173

**Comment by khasunuma** [comment]
I see. I agree with @Pandrex247 comments.

**Comment by smillidge** [comment]
Subject to raging debate internally on version numbers. This is now a good working 5 version number. @arjantijms Can you review?

**Comment by khasunuma** [comment]
@arjantijms , I see your opinion. But I still have following problems;
* I don't think a good version number without this request based on issue #1702 .
* I can't explain why the version number on Payara-5 branch was '5.0.0.163-SNAPSHOT'.

**Comment by Pandrex247** [comment]
This was unintentionally closed, new PR at #1777

**Pull request closed without merging**
