### PR TITLE
FISH-6483 add several other js require in admingui

### PR DESCRIPTION
**Pull request by aubi**
## Description
Added require for function calls on table, so they succeed.

Currently, there is no (known) JS warning in the log while working with admin gui.
There is only 404 for a js file (will be consecutive PR).

### Testing Performed
Going through admin gui (e.g. select list of JDBC resources, go to detail, ping, deploy application, etc.)

### Testing Environment
Linux, OpenJDK 11

## Notes for Reviewers
Open JS debugger while going through admin gui and watch uncatched exceptions.

### CODE REVIEW

**Comment by aubi** [comment]
Jenkins test, please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by aubi** [comment]
Jenkins test, please

**Comment by aubi** [comment]
@arieki 
Fixed. Let me know, if you will find some other issues.

**Comment by arieki** [comment]
> @arieki Fixed. Let me know, if you will find some other issues.

I believe you want to mention @luiseufrasio instead

**Review by luiseufrasio — APPROVED** [review]
LGTM! It was fixed

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by aubi** [comment]
Jenkins test please

**Pull request merged**
