### PR TITLE
Fixs for Payara 4 build

### PR DESCRIPTION
**Pull request by Cousjava**

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Pandrex247** [comment]
Seems to be failing to download an artefact for some reason.

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Pull request merged**
