### PR TITLE
PAYARA-2352 Fix Windows Data Grid Discovery

### PR DESCRIPTION
**Pull request by smillidge**
Fix selection of IP addresses on Windows Server

### CODE REVIEW

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by lprimak** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
