### PR TITLE
PAYARA-1269-Upgrade-libpam4j-to-v1.8-with-groupid-org-kohsuke

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
Does this class not need to change?

https://github.com/payara/Payara/blob/master/appserver/security/core-ee/src/main/java/com/sun/enterprise/security/auth/realm/pam/PamRealm.java

**Comment by mulderbaba** [comment]
no @smillidge. I used that class for the realm config.

**Comment by smillidge** [comment]
So the classnames are still org.jvnet?

**Comment by mulderbaba** [comment]
exactly, see https://github.com/kohsuke/libpam4j/tree/master/src/main/java/org/jvnet/libpam

**Comment by smillidge** [comment]
Doesn't it need an upgraded JNA?

**Comment by mulderbaba** [comment]
upgraded jna comes with the libpam4j as a transitive dependency. our version of jna is now 4.0.0. I'm planning to update it as well, after forking libpam4j and sending a PR. if that doesn't get accepted in a timely manner we can host it in patched projects repo.

**Pull request merged**
