### PR TITLE
PAYARA-3262 dont create a new response in the jaxrs container exception mapper - Payara4

### PR DESCRIPTION
**Pull request by mulderbaba**
Maintenance PR of: https://github.com/payara/Payara/pull/3451

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins test MicroProfile please

**Comment by mulderbaba** [comment]
Jenkins test MicroProfile please

**Comment by mulderbaba** [comment]
Jenkins test MicroProfile please

**Comment by smillidge** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
Jenkins test MicroProfile please

**Comment by arjantijms** [comment]
Jenkins test MicroProfile please

**Pull request merged**
