### PR TITLE
PAYARA-1556 Upgraded Derby to 10.13.1.1

### PR DESCRIPTION
**Pull request by michaelranaldo**

### CODE REVIEW

**Comment by michaelranaldo** [comment]
Jenkins, would you kindly?

**Comment by arjantijms** [comment]
This one needs a new test, as JDK8 is minimum now

**Comment by michaelranaldo** [comment]
This should work on JDK8 as is; payara_patchedprojects has the fixed javadb. Jira has been created for new tests

**Comment by michaelranaldo** [comment]
Jenkins JDK8 test please

**Comment by michaelranaldo** [comment]
Jenkins JDK8 test please

**Pull request closed without merging**
