### PR TITLE
Added links to JCache API

### LINKED ISSUE #942: JSR107 Javadocs should be linked from the root GitHub page
There is a link to the Payara Micro API javadoc, but no link to the jsr107 javadoc here:
http://payara.github.io/Payara/appserver_API/New%20folder/payara-appserver-modules_api/payara-jsr107_api/site/apidocs/

### PR DESCRIPTION
**Pull request by OndrejM**
Preview of the changes available at https://ondrejm.github.io/Payara/
Fixes #942.

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by OndrejM** [comment]
The branch gh-pages does not contain any code therefore any tests. It is only static html page available here: https://payara.github.io/Payara/

**Comment by smillidge** [comment]
jenkins test please

**Comment by OndrejM** [comment]
@smillidge, @MeroRai - this branch does not contain any test, only static html page. Therefore Jenkins fails saying no tests found.

**Comment by jerrinot** [comment]
Hi, some feedback. As a user I find this confusing:  
image

What's the difference between "Payara JSR 107 API" and  "JSR 107 (JCache) API" ? 
(I actually know what the difference is, but I still find it non-intuitive)

**Comment by OndrejM** [comment]
Thanks for the fedback, @jerrinot. I also find it confusing, but I could find a better way to name the links. What would you suggest?

**Comment by smillidge** [comment]
Payara Cache API?

**Comment by OndrejM** [comment]
How is the Payara API related to JCache API? Does it depend on JCache, extend JCache? "Payara Cache API" suggests it is an alternative to standard JCache API, which I think is not the case...

**Comment by jerrinot** [comment]
Payara API is just a glue, isn't it? Integration / CDI extension, something along these lines.

**Comment by smillidge** [comment]
Yep just glue and a CDI extension for @NamedCache and some producers for injecting CacheManager and CachingProvider.

**Comment by OndrejM** [comment]
What do you think about "Payara JCache extensions" and "JCache API"? (I would get rid of JSR 107, as it is very obscure for beginners)

**Comment by jerrinot** [comment]
I agree "JSR-107" sounds obscure. Analogy: I use "Servlet API", not "JSR 340"

"JCache API" sounds good. 
"Payara JCache Extensions" less so. It does not give away what is it good for. What about "Payara JCache Integration(s)" ? + perhaps some intro at directly at the [site](http://payara.github.io/Payara/appserver_API/New%20folder/payara-appserver-modules_api/payara-jsr107_api/site/apidocs/) ?

**Pull request merged**
