### PR TITLE
FISH-6110 Upgrade to latest H2 version

### PR DESCRIPTION
**Pull request by arieki**
## Description

This is a fix for `quicklook` failing on test cases related to H2. 
H2 does not support IDENTITY() function anymore from H2 2.x version

### Blockers

None

### New tests

None

### Testing Performed

Run payara quicklook test

### Testing Environment

Ubuntu 20.04.4 LTS, OpenJDK11, Maven 3.6.3

## Documentation

None

### CODE REVIEW

**Comment by arieki** [comment]
jenkins test please

**Comment by pdudits** [comment]
Upgrade commit was reverted in base branch. You want to apply version change again

**Comment by arieki** [comment]
> Upgrade commit was reverted in base branch. You want to apply version change again

I've just pushed the change

**Comment by arieki** [comment]
jenkins test please

**Comment by pdudits** [comment]
I'm confused, version is still not upgraded:

https://github.com/payara/Payara/blob/Payara6/pom.xml#L227

**Comment by pdudits** [comment]
> I'm confused, version is still not upgraded:
> 
> https://github.com/payara/Payara/blob/Payara6/pom.xml#L227

The version is changed on your branch though, but diff of this PR is not showing that. Try rebasing again and include upgrade to h2 version as well.

**Comment by arieki** [comment]
> > I'm confused, version is still not upgraded:
> > https://github.com/payara/Payara/blob/Payara6/pom.xml#L227
> 
> The version is changed on your branch though, but diff of this PR is not showing that. Try rebasing again and include upgrade to h2 version as well.

rebased and updated the required changes for H2 @pdudits

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Pull request merged**
