### PR TITLE
PAYARA-3757-SPEC-45-Upgrade-jacc-api-to-1.6.1

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by arjantijms** [comment]
>I think it all looks good. Just one thing to check, does the javax.security.jacc.jar reference in files like appserver/admin/gf_template/src/main/resources/config/default-web.xml have any bearing on this?

The `system-jar-includes` should indeed be updated as well.

**Comment by mulderbaba** [comment]
@arjantijms @MattGill98  `default-web.xml` contains `javax.security.jacc.jar` which is not the artifact I upgraded to. Mine was `javax.security.jacc-api.jar` and updated to `jakarta.security.jacc-api.jar` and yet there is no artifact under Payara with name `javax.security.jacc.jar`, so this is now confusing:)

**Comment by arjantijms** [comment]
@mulderbaba You're right, very confusing that one indeed. Okay, so I think we can leave that one as is, or can remove the invalid entry. Thx!

**Comment by arjantijms** [comment]
Jenkins test please

**Pull request merged**
