### PR TITLE
FISH-7204 Removes internal ASURLClassLoader throwable reference to avoid ClassLoader leaks

### PR DESCRIPTION
**Pull request by ctabin**
## Description
Fixes potential ClassLoader leaks that might be kept in the StackTrace reference of the internal `Throwable` in [ASURLClassLoader](https://github.com/payara/Payara/blob/master/nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java#L1105).

Here is what we have in visualvm:

screen

One can also note there is a lot of cleaner for `SentinelInputStream` pending.

Probably due to #6179.

## Environment

- payara-embedded-all 6.2023.2
- JDK17
- Linux Debian Bullseye

### CODE REVIEW

**Review by lprimak — APPROVED** [review]

**Comment by ctabin** [comment]
Jenkins test please

**Comment by ctabin** [comment]
Error seems to be unrelated to this PR: `Could not resolve dependencies for project fish.payara.samples:ejb-http-remoting:war:6.2023.3-SNAPSHOT: Failed to collect dependencies at org.glassfish.mq:imq:jar:6.1.1: Failed to read artifact descriptor for org.glassfish.mq:imq:jar:6.1.1: Could not transfer artifact org.glassfish.mq:imq:pom:6.1.1 from/to zulu-jdk (https://nexus.payara.fish/content/repositories/zulu-jdk/): Authentication failed for https://nexus.payara.fish/content/repositories/zulu-jdk/org/glassfish/mq/imq/6.1.1/imq-6.1.1.pom 401 Unauthorized`

**Comment by aubi** [comment]
We are fixing it and we'll restart the build.

**Comment by aubi** [comment]
Build is fixed

**Comment by ctabin** [comment]
Thanks @aubi. Who may I ask for a review ?

**Comment by lprimak** [comment]
It's up to Payara folks. I can review it :)

**Review by lprimak — APPROVED** [review]

**Comment by ctabin** [comment]
@breakponchito Could you take a look or assign to someone ? Thanks and sorry for the bothering.

**Comment by ctabin** [comment]
For information, this problem is still present in 6.2023.3.

**Comment by ctabin** [comment]
Jenkins test please

**Comment by ctabin** [comment]
@shub8968 Since those modifications have been merged in GlassFish, can you assign someone ? It should be pretty straightforward and prevents us to upgrade from 6.2023.1. :pray:

**Comment by ctabin** [comment]
@JamesHillyard Would it be possible to also raise an internal ticket for this please ? :pray:

**Comment by JamesHillyard** [comment]
Hi @ctabin,

Yes of course - The internal issue `FISH-7332` has been raised to track this issue. Thank you again for your contribution and your patience while we find time to test and review your contributions

**Comment by smillidge** [comment]
CLA received

**Review by aubi — APPROVED** [review]
Approved, sorry for the long time.

**Pull request merged**
