### PR TITLE
QACI-195 Add MP TCKs to PR tests

### PR DESCRIPTION
**Pull request by AlanRoth**
Adds MP TCK Runners to Jenkinsfile to include them as standard testing when merging a PR.

### CODE REVIEW

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by jbee** [comment]
Are we having some faster CI servers or will running all MP TCKs mean we have to wait about an extra hour?

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
> Are we having some faster CI servers or will running all MP TCKs mean we have to wait about an extra hour?

I appreciate the concern, however priorities are elsewhere at the moment

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by jbee** [comment]
FYI: https://github.com/payara/Payara/pull/4614 has a list of the env vars needed to run the mentioned TCKs

**Comment by AlanRoth** [comment]
The problem is jenkins doesn't like to recognize those vars existing wherever they're set

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by AlanRoth** [comment]
jenkins test please

**Pull request closed without merging**
