### PR TITLE
PAYARA-2575 Yubikey  - Payara4

### PR DESCRIPTION
**Pull request by MarkWareham**

### CODE REVIEW

**Comment by MarkWareham** [comment]
Jenkins, quick test Payara 4 please

**Comment by MarkWareham** [comment]
Failure looks to be related to something else.

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 4 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 4 please

**Comment by arjantijms** [comment]
>  > git fetch --tags --progress https://github.com/payara/Payara +refs/pull/*:refs/remotes/origin/pr/*
> ERROR: Error fetching remote repo 'origin'
> hudson.plugins.git.GitException: Failed to fetch from https://github.com/payara/Payara
> 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:825)
> 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1092)
> 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1123)
> 	at hudson.scm.SCM.checkout(SCM.java:495)

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 4 please

**Pull request merged**
