### PR TITLE
FISH-8100: fixing issue when totalizing buckets for prometheus format

### PR DESCRIPTION
**Pull request by breakponchito**
Fix buckets counting for Prometheus format
## Description

This is a fix for an issue to totalize the occurrences of bucket values
### Testing Performed

Manual testing by executing metrics application with histogram and timer metrics and custom configuration for percentiles and buckets

image

TCK results for metrics:
image

result from samples:
image

steps to reproduce on the ticket:

https://payara.atlassian.net/browse/FISH-8100

### Testing Environment

windows 11, azul jdk 11, maven 3.9.5 / ubuntu 20.04, azul jdk 11, maven 3.8.6

### CODE REVIEW

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by luiseufrasio — APPROVED** [review]
LGTM!

**Pull request merged**
