### PR TITLE
Payara-769: Make resetAssociation() more robust

### LINKED ISSUE #769: Connection pool sometimes does not recover from JDBC Errors
Sometimes broken connections get stuck in the pool, and continue to get handed out to client code. The connection verification code will not clean them out because `ManagedConnectionImpl#transactionInProgress` is set to true continuously and `com.sun.gjc.spi.ManagedConnectionFactoryImpl#isValid` skips validation. 

It might be loosely related with the situations some commenters describe [GLASSFISH-19475](https://java.net/jira/browse/GLASSFISH-19475).

As soon as the error is trigged the log is being flooded with execptions, some during rollback, some during checkout, for example:

```
java.lang.RuntimeException: org.jooq.exception.DataAccessException: Error getting connection from data source com.sun.gjc.spi.jdbc40.DataSource40@28cfb72a
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueDriver.dequeue(OracleAdvancedQueueDriver.java:138)
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueDriver.dequeueOnce(OracleAdvancedQueueDriver.java:73)
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueDriver.dequeueWithTimeout(OracleAdvancedQueueDriver.java:79)
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueDriver.dequeue(OracleAdvancedQueueDriver.java:56)
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueWrapper.fetchSingle(OracleAdvancedQueueWrapper.java:59)
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueWrapper.poll(OracleAdvancedQueueWrapper.java:34)
    at COMPANY.APPLICATION.grandjunction.GrandJunction.listenForAssignedTaskTokens(GrandJunction.java:90)
    at COMPANY.APPLICATION.grandcentral.GrandCentralImpl.lambda$setupAssignedListener$1(GrandCentralImpl.java:144)
    at COMPANY.APPLICATION.grandcentral.GrandCentralImpl$$Lambda$62/413365507.apply(Unknown Source)
    at COMPANY.APPLICATION.grandcentral.GrandCentralImpl$QueueListener.lambda$work$16(GrandCentralImpl.java:675)
    at COMPANY.APPLICATION.grandcentral.GrandCentralImpl$QueueListener$$Lambda$66/2072266415.apply(Unknown Source)
    at COMPANY.APPLICATION.taskengine.base.DatabaseAdapter.lambda$withConnectionDo$32(DatabaseAdapter.java:27)
    at COMPANY.APPLICATION.taskengine.base.DatabaseAdapter$$Lambda$61/634900652.get(Unknown Source)
    at COMPANY.APPLICATION.taskengine.base.TxHandler.doWithTransaction(TxHandler.java:60)
    at COMPANY.APPLICATION.taskengine.base.TxHandler.doWithRequiresNew(TxHandler.java:44)
    at COMPANY.APPLICATION.taskengine.base.DatabaseAdapter.withConnectionDo(DatabaseAdapter.java:27)
    at COMPANY.APPLICATION.grandcentral.GrandCentralImpl$QueueListener.work(GrandCentralImpl.java:673)
    at COMPANY.APPLICATION.base.utility.BackgroundDaemon.run(BackgroundDaemon.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.jooq.exception.DataAccessException: Error getting connection from data source com.sun.gjc.spi.jdbc40.DataSource40@28cfb72a
    at COMPANY.APPLICATION.base.jooq.impl.LazyEDatabaseConnectionProvider.acquire(LazyEDatabaseConnectionProvider.java:72)
    at org.jooq.util.oracle.OracleDSL$DBMS_AQ.dequeue(OracleDSL.java:852)
    at COMPANY.APPLICATION.base.advancedqueues.OracleAdvancedQueueDriver.dequeue(OracleAdvancedQueueDriver.java:127)
    ... 18 more
Caused by: java.sql.SQLException: Error in allocating a connection. Cause: java.lang.RuntimeException: Got exception during XAResource.start:
    at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:121)
    at COMPANY.APPLICATION.base.jooq.impl.LazyEDatabaseConnectionProvider.acquire(LazyEDatabaseConnectionProvider.java:70)
    ... 20 more
Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a connection. Cause: java.lang.RuntimeException: Got exception during XAResource.start:
    at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)
    at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
    at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
    at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
    at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:114)
    ... 21 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: java.lang.RuntimeException: Got exception during XAResource.start:
    at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:221)
    at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
    at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
    ... 25 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: java.lang.RuntimeException: Got exception during XAResource.start:
    at com.sun.enterprise.resource.rm.SystemResourceManagerImpl.enlistResource(SystemResourceManagerImpl.java:107)
    at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:211)
    ... 27 more
Caused by: java.lang.RuntimeException: Got exception during XAResource.start:
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistResource(JavaEETransactionManagerSimplified.java:388)
    at com.sun.enterprise.resource.rm.SystemResourceManagerImpl.enlistResource(SystemResourceManagerImpl.java:103)
    ... 28 more
Caused by: javax.transaction.xa.XAException: com.sun.appserv.connectors.internal.api.PoolingException: javax.resource.spi.LocalTransactionException: Closed Connection
    at com.sun.enterprise.resource.ConnectorXAResource.handleResourceException(ConnectorXAResource.java:115)
    at com.sun.enterprise.resource.ConnectorXAResource.start(ConnectorXAResource.java:150)
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistResource(JavaEETransactionManagerSimplified.java:386)
    ... 29 more
```

### PR DESCRIPTION
**Pull request by retoo**
Payara-769: Make resetAssociation() more robust by avoiding begin()ingtx in error handling/finally

Otherwise we will crash right again in our finally/resetAssociation block which will
cause the connection pool entry to have avery inconsistent state from which the
server does not recover.

Fixes #769

### CODE REVIEW

**Comment by retoo** [comment]
jenkins test please

**Comment by retoo** [comment]
The new diff is even more aggressiv. Should an error happen during the 'start/begin' phase we throw the connection away. There's IMHO no good reason to keep a connection that had trouble with setAutcommit() during the begin/start phase of a transaction.

Stacktrace:
```
Caused by: java.sql.SQLException: Error in allocating a connection. Cause: java.lang.RuntimeException: Got exception during XAResource.start:
        at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:121)
        at COMPANY.APPLICATION.base.jooq.impl.LazyEDatabaseConnectionProvider.acquire(LazyEDatabaseConnectionProvider.java:57)
        ... 20 more
Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a connection. Cause: java.lang.RuntimeException: Got exception during XAResource.start:
        at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
        at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:115)
        ... 21 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: java.lang.RuntimeException: Got exception during XAResource.start:
        at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:221)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
        ... 25 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: java.lang.RuntimeException: Got exception during XAResource.start:
        at com.sun.enterprise.resource.rm.SystemResourceManagerImpl.enlistResource(SystemResourceManagerImpl.java:107)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:211)
        ... 27 more
Caused by: java.lang.RuntimeException: Got exception during XAResource.start:
        at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistResource(JavaEETransactionManagerSimplified.java:389)
        at com.sun.enterprise.resource.rm.SystemResourceManagerImpl.enlistResource(SystemResourceManagerImpl.java:103)
        ... 28 more
Caused by: javax.transaction.xa.XAException: com.sun.appserv.connectors.internal.api.PoolingException: javax.resource.spi.LocalTransactionException: Closed Connection
        at com.sun.enterprise.resource.ConnectorXAResource.handleResourceException(ConnectorXAResource.java:115)
        at com.sun.enterprise.resource.ConnectorXAResource.start(ConnectorXAResource.java:150)
        at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.enlistResource(JavaEETransactionManagerSimplified.java:386)
        ... 29 more
```

**Comment by smillidge** [comment]
@retoo thanks for the pull request and the detailed investigation it's appreciated. We need you to sign a CLA so us to pull your fix. Take a look at https://github.com/payara/Payara/blob/master/Contributing.md

**Comment by smillidge** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by retoo** [comment]
Can I be of any assistance, on our build server the payara build/test seems to run through.

**Comment by smillidge** [comment]
@retoo this is failing in an internal test suite so it may pass on your build servers. I'll take a look at which tests are failing and let you know.

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
@retoo there are a number of JPA Failures in the test suite.The tests that are failing are based on the JavaEE 7 samples prohect on GitHub. These tests fail in your PR same exception for the first two tests;
```shell
[INFO] Java EE 7 Sample: jpa - datasourcedefinition-webxml-pu FAILURE [  6.647 s]
[INFO] Java EE 7 Sample: jpa - datasourcedefinition-annotation-pu FAILURE [  7.107 s]
[INFO] Java EE 7 Sample: jpa - extended-pc ................ FAILURE [  6.097 s]
```
Failure exceptions are the same below for the first two. These tests deploy a datasource that is defined in the web.xml, the final test uses an ExtendedPersistenceContext;

```java
Running org.javaee7.jpa.datasourcedefinition_webxml_pu.DataSourceDefinitionWebxmlPuTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.14 sec <<< FAILURE! - in org.javaee7.jpa.datasourcedefinition_webxml_pu.DataSourceDefinitionWebxmlPuTest
insertAndQueryEntity(org.javaee7.jpa.datasourcedefinition_webxml_pu.DataSourceDefinitionWebxmlPuTest)  Time elapsed: 0.354 sec  <<< ERROR!
javax.ejb.EJBException: Unable to complete container-managed transaction.
	at com.sun.jts.CosTransactions.RegisteredResources.distributeRollback(RegisteredResources.java:1187)
	at com.sun.jts.CosTransactions.TopCoordinator.rollback(TopCoordinator.java:2291)
	at com.sun.jts.CosTransactions.CoordinatorTerm.rollback(CoordinatorTerm.java:530)
	at com.sun.jts.CosTransactions.TerminatorImpl.rollback(TerminatorImpl.java:286)
	at com.sun.jts.jta.TransactionImpl.rollback(TransactionImpl.java:162)
	at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:494)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:854)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:721)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:505)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy887.saveNewEntity(Unknown Source)
	at org.javaee7.jpa.datasourcedefinition_webxml_pu.service.__EJB31_Generated__TestService__Intf____Bean__.saveNewEntity(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:434)
	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:127)
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
	at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:67)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.javaee7.jpa.datasourcedefinition_webxml_pu.service.TestService$Proxy$_$$_Weld$EnterpriseProxy$.saveNewEntity(Unknown Source)
	at org.javaee7.jpa.datasourcedefinition_webxml_pu.DataSourceDefinitionWebxmlPuTest.insertAndQueryEntity(DataSourceDefinitionWebxmlPuTest.java:53)
```

```java
javax.ejb.EJBException: Transaction aborted
	at org.apache.derby.client.am.Statement.completeExecute(Unknown Source)
	at org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)
	at org.apache.derby.client.net.NetStatementReply.readExecute(Unknown Source)
	at org.apache.derby.client.net.StatementReply.readExecute(Unknown Source)
	at org.apache.derby.client.net.NetPreparedStatement.readExecute_(Unknown Source)
	at org.apache.derby.client.am.PreparedStatement.readExecute(Unknown Source)
	at org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)
	at org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)
	at org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)
	at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:125)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:892)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:964)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:633)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2055)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:306)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180)
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489)
	at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80)
	at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90)
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301)
	at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:803)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1790)
	at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:227)
	at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:126)
	at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4260)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.issueSQLbeforeCompletion(UnitOfWorkImpl.java:3168)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.issueSQLbeforeCompletion(RepeatableWriteUnitOfWork.java:355)
	at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:158)
	at org.eclipse.persistence.transaction.JTASynchronizationListener.beforeCompletion(JTASynchronizationListener.java:68)
	at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:452)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:854)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:721)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:505)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.StatefulSessionContainer.postInvokeTx(StatefulSessionContainer.java:1853)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy1138.commitChanges(Unknown Source)
	at org.javaee7.jpa.extended.pc.__EJB31_Generated__CharactersBean__Intf____Bean__.commitChanges(Unknown Source)
	at org.javaee7.jpa.extended.pc.ExtendedPersistenceContextTest.should_update_characters_after_transaction_flush(ExtendedPersistenceContextTest.java:68)
```

**Comment by smillidge** [comment]
jenkins test please

**Comment by retoo** [comment]
Can I reproduce the test on our environment? We are using the patch now for one project without any noticeable problems so far.

**Comment by smillidge** [comment]
Hi 

The tests are based on the code here https://github.com/javaee-samples/javaee7-samples/tree/master/jpa
The tests failing are;

[INFO] Java EE 7 Sample: jpa - datasourcedefinition-webxml-pu FAILURE [  6.647 s]
[INFO] Java EE 7 Sample: jpa - datasourcedefinition-annotation-pu FAILURE [  7.107 s]
[INFO] Java EE 7 Sample: jpa - extended-pc ................ FAILURE [  6.097 s]

**Comment by retoo** [comment]
We ported the patch to a newer version. See pull request #1148

**Pull request closed without merging**
