### PR TITLE
PAYARA-1382, PAYARA-1574 admin console notifiers integration

### PR DESCRIPTION
**Pull request by Cousjava**

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins, would you kindly?

**Pull request merged**
