### PR TITLE
FISH-6969: Use OpenTelemetry as basis for OpenTracing Support

### PR DESCRIPTION
**Pull request by pdudits**
## Description

As transitional step, we use OpenTracing shim to bridge all use of opentracing in the server with OpenTelemetry.

Whenever OpenTracing is used, OpenTelemetry SDK is auto-configured on per-application basis respecting system properties and environment variables.

### New tests
So far there is no application API beyond using OpenTracing to get to OTEL, so they will arrive later

### Testing Performed
Payara Samples and OpenTracing TCKs should still pass without problems, let's see what Jenkins thinks about it.

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Review by arieki — APPROVED** [review]
Some of copyright needs to be updated

**Comment by pdudits** [comment]
Will update that in followup PR.

**Pull request merged**
