### PR TITLE
FISH-326 Remove Example Notifier

### PR DESCRIPTION
**Pull request by MattGill98**
Notifier example has been moved to the new repository: https://github.com/payara/Notifiers

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Review by Cousjava — APPROVED** [review]

**Comment by MattGill98** [comment]
Failed due to incorrect checksums - fixing patched projects now

**Comment by MattGill98** [comment]
Fixed them: https://github.com/payara/Payara_PatchedProjects/pull/335

**Comment by MattGill98** [comment]
jenkins test please

**Pull request merged**
