### PR TITLE
PAYARA-3580 Merge JDK11 branch back into master PAYARA-3788 PAYARA-3779

### PR DESCRIPTION
**Pull request by Cousjava**
PAYARA-3580 - Merge JDK11 Branch back into master
PAYARA-3788 Fixed error of Unknown Protocol: jrt in JDK11
PAYARA-3779 JDK11 Can now create new instance from admin console

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Quicklook passes when run locally

**Comment by Pandrex247** [comment]
We will need to sort out Jenkins before this can be merged, as otherwise it will impact all other PRs.
The error it throws trying to run quicklook is... interesting....
```
/var/lib/jenkins/workspace/PayaraQuickBuildAndTest/appserver/tests/quicklook/gfproject/build-impl.xml:134: Unable to find a javac compiler;
com.sun.tools.javac.Main is not on the classpath.
Perhaps JAVA_HOME does not point to the JDK.
It is currently set to "/usr/lib/jvm/zulu-8-amd64/jre"
```

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by pdudits** [comment]
The diffference is in profile `all` activated in quicklook. [This isn't activated on master](https://github.com/payara/Payara/pull/3923/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R51). Would this be a solution?

**Comment by Cousjava** [comment]
No because I have tried running the same command for quicklook locally without the same issues.

**Comment by Cousjava** [comment]
replaced by #3929

**Pull request closed without merging**
