### PR TITLE
PAYARA-3749-SPEC-57-Upgrade-servlet-api-to-4.0.2

### PR DESCRIPTION
**Pull request by mulderbaba**
SPEC-57 

See https://github.com/eclipse-ee4j/servlet-api

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by arjantijms** [comment]
This seems to have missed some dependency adjustment in the EE Security module:

```
Unable to resolve 
    fish.payara.payara-modules.healthcheck-cpool [69](R 69.0): 
    missing requirement 
    [fish.payara.payara-modules.healthcheck-cpool [69](R 69.0)] 
    osgi.wiring.package; 
    (&(osgi.wiring.package=com.sun.enterprise.resource.pool)(version>=5.192.0)(!(version>=6.0.0))) 
    caused by: 
        
        Unable to resolve org.glassfish.main.connectors.runtime [23](R 23.0):
            missing requirement 
            [org.glassfish.main.connectors.runtime [23](R 23.0)] 
            osgi.wiring.package; 
            (&(osgi.wiring.package=com.sun.enterprise.security.permissionsxml)(version>=5.192.0)(!(version>=6.0.0))) [
            caused by: 
        
            Unable to resolve org.glassfish.main.security.ee [43](R 43.0): 
                missing requirement 
                [org.glassfish.main.security.ee [43](R 43.0)] 
                osgi.wiring.package; 
                (&(osgi.wiring.package=javax.servlet)(version>=3.0.0)(!(version>=4.0.0)))]] 

Unresolved requirements: 
    [[fish.payara.payara-modules.healthcheck-cpool [69](R 69.0)] 
    osgi.wiring.package; 
    (&(osgi.wiring.package=com.sun.enterprise.resource.pool)(version>=5.192.0)(!(version>=6.0.0)))]
```

**Comment by mulderbaba** [comment]
jenkins test

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
@smillidge can you look at this again?

**Comment by arjantijms** [comment]
Jenkins test please

**Pull request merged**
