### PR TITLE
FISH-6022 FISH-6299 FISH-6047: Payara 6 port for JWT and SSO issues

### PR DESCRIPTION
**Pull request by pdudits**
Port of #6021 and #6053 for Payara6

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Comment by Softwaremanufaktur** [comment]
@Pandrex247 @pdudits 

Is there a chance to get to know why the commit/merge of https://github.com/payara/Payara/pull/6021/files was reverted here? (Same project which initially opened the issue https://github.com/payara/Payara/issues/5746 but new developer. We again have the same behaviour as mentioned in the issue with Version 6.2023.6

**Comment by Pandrex247** [comment]
It was initially reverted because it broke the MicroProfile TCK: https://github.com/payara/Payara/pull/6141
Looking at the commit history, I'm now not sure if we ever revisited it for Payara 6 (the fix at the time was written for the Payara 5 branch).

Please feel free to raise an issue if you're still encountering the issue.

**Pull request merged**
