### PR TITLE
FISH-8248 Increment Version Numbers 7.2024.1.Alpha2-SNAPSHOT

### PR DESCRIPTION
**Pull request by Pandrex247**
## Description
Increments the version numbers for the next alpha release.

### Blockers
Cargotracker will not like the fact we're changing the version number, because it uses a maven shrinkwrap resolver which can only read the pom as-is (ignoring our usual strategy of overriding the payara dependency version using a property)
https://github.com/payara/cargotracker/pull/35

### New tests
Narp

### Testing Performed
Niet

### Testing Environment
Jenkins

## Documentation
N/A

## Notes for Reviewers
Narp

### CODE REVIEW

**Comment by kalinchan** [comment]
Cargotracker test doesn't seem happy

**Comment by Pandrex247** [comment]
> Cargotracker test doesn't seem happy

Cargotracker will not like the fact we're changing the version number, because it uses a maven shrinkwrap resolver which can only read the pom as-is (ignoring our usual strategy of overriding the payara dependency version using a property)
https://github.com/payara/cargotracker/pull/35

😉

**Review by luiseufrasio — APPROVED** [review]
LGTM!

**Comment by luiseufrasio** [comment]
jenkins test please

**Pull request merged**
