### PR TITLE
PAYARA-1694 Healthcheck still prints out error in log

### PR DESCRIPTION
**Pull request by Pandrex247**
Don't mark command as failed when not enabled

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins, would you kindly?

**Comment by Cousjava** [comment]
should this replace #1626 ?

**Comment by Pandrex247** [comment]
Nah it's in addition to it.
Mert's PR stops the command from returning as failed later on in its execution when it's retrieving the stuff, mine stops it from failing at the command's entry point.

**Comment by Pandrex247** [comment]
jenkins test please

**Pull request merged**
