### PR TITLE
Combined pull request for various issues

### PR DESCRIPTION
**Pull request by phillipross**
This pull request combines two earlier pull requests containing fixes for issues #330, #319, and #316 
Previous pull requests with some code review comments: #317, #320

### CODE REVIEW

**Comment by phillipross** [comment]
Reworking this pull requests as #331

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
fixes #330 fixes #319 fixes #316

**Pull request merged**
