### PR TITLE
PAYARA-2387-Singleton-JAX-RS-failure

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins quick test payara 5 please

**Comment by mulderbaba** [comment]
jenkins quick test payara 5 please

**Comment by smillidge** [comment]
Fixes #2248

**Comment by smillidge** [comment]
jenkins quick test payara 5 please

**Comment by Pandrex247** [comment]
jenkins quick test payara 5 please

**Pull request merged**
