### PR TITLE
PAYARA-1907 CDI Weld probe activated causes exceptions with stateless EJB

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
I tested the application without EJB, It is working.
And I also tested JavaEE7-Samples with CDI Dev enable mode and disable mode, the execution result is same. So I think these changes have no impact.

**Comment by jGauravGupta** [comment]
In case of JavaEE7-Samples, servlet - security test are failing in both case either dev mode is enabled or disabled.

**Comment by smillidge** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Hi Steve,

I tested these changes for application includes CDI / CDI  + EJB / EJB classes without any issue.

**Comment by smillidge** [comment]
OK I'll merge

**Pull request merged**
