### PR TITLE
Payara issue 502.2

### PR DESCRIPTION
**Pull request by dmatej**
And this is the second part. It contains much more changes, but it seems much better in my opinion ... but I'm not sure if it is completely correct. Someone should check it.
This part also should help to resolve similar issues ...

### CODE REVIEW

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
Similar to the other comments on the other pull requests

One thing we need changing to comply with the CDDL we need a comment in each changed file of the form;

Portions Copyright [2015] [C2B2 Consulting Limited]

Can you add please?

**Comment by smillidge** [comment]
Given the number of changes on this pull request we can get one of our developers to add the comments if you don't have time.

**Comment by dmatej** [comment]
I'm in half of the work ... what to do with files that are completely new? Should I add still the same header? (Portions ...)

**Comment by smillidge** [comment]
Completely new files should have
```java
/*
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 Copyright (c) 2015 C2B2 Consulting Limited. All rights reserved.
 The contents of this file are subject to the terms of the Common Development
 and Distribution License("CDDL") (collectively, the "License").  You
 may not use this file except in compliance with the License.  You can
 obtain a copy of the License at
 https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
 or packager/legal/LICENSE.txt.  See the License for the specific
 language governing permissions and limitations under the License.
 When distributing the software, include this License Header Notice in each
 file and include the License file at packager/legal/LICENSE.txt.
 */
```

**Comment by dmatej** [comment]
Done :-)

**Comment by smillidge** [comment]
payara test please

**Pull request merged**
