### PR TITLE
FISH-6876 FISH-7757 Parsson 1.1.4 & JSON-P API 2.1.2

### PR DESCRIPTION
**Pull request by Pandrex247**
## Description
Updates the JSON-P implementation (Parsson) to 1.1.4.
This is a patched version of Parsson, since the published 1.1.4 has a malformed OSGi manifest and doesn't work.

Also updates the JSON-P API to 2.1.2.

### Blockers
https://github.com/payara/patched-src-parsson/pull/1

### New tests
None

### Testing Performed
* Created a temp maven repo: `mkdir D:\Downloads\FISH-7757`
* Built patched parsson and let unit tests run: `mvn clean install -Dmaven.repo.local=D:\Downloads\FISH-7757`
* Build Payara server, overriding version of parsson in pom: `mvn clean install -Dmaven.repo.local=D:\Downloads\FISH-7757 -Dparsson.version=1.1.4.payara-p2-SNAPSHOT`
* Started server

### Testing Environment
Windows 11, Zulu JDK 11.0.20

## Documentation
N/A

## Notes for Reviewers
None

### CODE REVIEW

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by luiseufrasio — APPROVED** [review]
LGTM

**Pull request merged**
