### PR TITLE
PAYARA-3882: Remove glassfish groupIds

### PR DESCRIPTION
**Pull request by pdudits**
This PR changes all `groupId`s of the modules so that:
* all modules are subgroups of `fish.payara.server`
* second level directory is part of groupId (the child directory of `appserver` or `nucleus`)
* except for distribution artifacts, which retain their groupIds
* modules not intended for public consumption are subgroup of `fish.payara.server.internal`

Few artifacts changed names:
* `appserver/packager/external/(javadb|h2db)` is `$1-repackaged` (conflict with packager artifact of same name)
* `appserver/featuresets/(payara.*)` renamed to `$1-featureset` to prevent conflict with distribution artifacts
* `appserver/packager/payara-micro` renamed to `payara-micro-package`

These two last changes give back meaning to `mvn -pl :payara -am` which now finally builds the distribution, rather than a featureset. Similar to `mvn -pl :payara-micro -am`.  This is even faster way to build than QuickBuild, as `mvn -pl :payara,:payara-micro -am` only requires 443 modules to build, compared to quickbuild's 627.

I recommend reviewing by commit to see the `rhythm` of the changes, but still this is too much to look after manually. The constraints above were verified with help of few scripts and clever spreadsheet ;).

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
jenkins test please

**Comment by pdudits** [comment]
jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
And final distribution of artifacts when running `-PBuildExtras` looks like this:

```
groupId                                                   artifacts
----                                                          -----
fish.payara.api                                                   2
fish.payara.distributions                                         5
fish.payara.extras                                                5
fish.payara.server.appclient                                      7
fish.payara.server.internal.admin                                31
fish.payara.server.internal.admingui                             67
fish.payara.server.internal.ant-tasks                             1
fish.payara.server.internal.appclient                             2
fish.payara.server.internal.appclient.server                      3
fish.payara.server.internal.batch                                 6
fish.payara.server.internal.cluster                              10
fish.payara.server.internal.common                               25
fish.payara.server.internal.concurrent                            5
fish.payara.server.internal.connectors                           13
fish.payara.server.internal.core                                 12
fish.payara.server.internal.deployment                           23
fish.payara.server.internal.diagnostics                           3
fish.payara.server.internal.distributions                         2
fish.payara.server.internal.docker                                1
fish.payara.server.internal.ejb                                  14
fish.payara.server.internal.extras                               15
fish.payara.server.internal.featuresets                           9
fish.payara.server.internal.flashlight                            8
fish.payara.server.internal.grizzly                               6
fish.payara.server.internal.ha                                    3
fish.payara.server.internal.hk2                                   4
fish.payara.server.internal.jdbc                                  8
fish.payara.server.internal.jdbc.jdbc-ra.jdbc-core                1
fish.payara.server.internal.jdbc.jdbc-ra                          2
fish.payara.server.internal.jdbc.jdbc-ra.jdbc-ra-distribution     1
fish.payara.server.internal.jdbc.jdbc-ra.jdbc30                   1
fish.payara.server.internal.jdbc.jdbc-ra.jdbc40                   1
fish.payara.server.internal.jms                                  10
fish.payara.server.internal.load-balancer                         5
fish.payara.server.internal.monitoring-console                    1
fish.payara.server.internal                                       1
fish.payara.server.internal.orb                                   5
fish.payara.server.internal.osgi-platforms                       11
fish.payara.server.internal.packager                            140
fish.payara.server.internal.payara-appserver-modules             32
fish.payara.server.internal.payara-modules                       18
fish.payara.server.internal.persistence.cmp                      19
fish.payara.server.internal.persistence                           8
fish.payara.server.internal.resourcebase.resources                1
fish.payara.server.internal.resources                             8
fish.payara.server.internal.security                             18
fish.payara.server.internal.test-utils                            3
fish.payara.server.internal.tests                                 1
fish.payara.server.internal.transaction                           7
fish.payara.server.internal.web                                  28
fish.payara.server.internal.webservices                           9
fish.payara.server.monitoring-console                             2
fish.payara.server                                                3
fish.payara.server.payara-appserver-modules                       7

**Comment by pdudits** [comment]
Attached is a diff file that only lists non-trivial changes (excluding poms where only changes related to groupIds are done)

[simplified.zip](https://github.com/payara/Payara/files/3565518/simplified.zip)

**Comment by pdudits** [comment]
All right, that one helps catching some heavy-handed replacements

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by pdudits** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Aside from me personally not liking `internal` this looks good to me. I'd like to get more opinions on this before pushing it through though as people seem to be pretty ambivalent on this - but it's the kind of thing people will immediately start cereal spitting over once they notice.

**Comment by pdudits** [comment]
consistently falling test in javaee8 samples gives more time for review, as it will take same time until I can attend to it

**Comment by pdudits** [comment]
jenkins test please

**Comment by pdudits** [comment]
jenkins test please

**Comment by jbee** [comment]
:rocket:

**Pull request merged**
