### PR TITLE
PAYARA-3420 Upgrade jsftemplating to 2.1.3

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by Cousjava** [comment]
Would it not be better to wait for the Jakarta version to be released and upgrade to that instead, as it is due to be released shortly?

**Comment by jGauravGupta** [comment]
Ok @Cousjava, I will wait for other Java EE components to released under EE4J.

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by arjantijms** [comment]
@Cousjava We can still accept this one, to have some pre-testing during the cycle.

**Pull request merged**
