### PR TITLE
PAYARA-3403 Upgrade build-helper-maven-plugin to 3.0.0 (Payara 4.x)

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Pull request merged**
