### PR TITLE
PAYARA-3171 custom keystore

### PR DESCRIPTION
**Pull request by arjantijms**
PAYARA-3171 cherry-picked https://github.com/payara/Payara/commit/9ea2b82aca2e5c4f481894bf45035e3c1c8dd39d

And added extra check for if principal is X500Name again.

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by mulderbaba** [comment]
Jenkins, quick test Payara 4 please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
