### PR TITLE
PAYARA-3160 Minimum Log File Size Error Ignored - Payara4 Part 2

### PR DESCRIPTION
**Pull request by MattGill98**
Fixes bug introduced with https://github.com/payara/Payara/pull/3629/files where instance wouldn't log anything.

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
~~~
Caused by: java.lang.ClassNotFoundException: org.jboss.weld.environment.se.WeldContainer
~~~

Doesn't look relevant to my PR, does anyone know what this is?

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Don't think I've seen that error before o.0
We'll need to check manually if its Jenkins that's broken or your branch, but I agree I don't immediately see why your change would break either weld or the build.

**Comment by Cousjava** [comment]
The jenkins failure look to similar to #3616, which is also a failure coming from weld when the files changed are nothing to do with it, but rather to do with files

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Pull request merged**
