### PR TITLE
PAYARA-2405 Fix Java EE 7 Samples batch tests against Payara Micro (Payara-5) 

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by lprimak** [comment]
jenkins test payara 5

**Comment by lprimak** [comment]
Jenkins, quick test Payara 5

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
