### PR TITLE
Issue #217 Using Mojarra 2.2.10

### PR DESCRIPTION
**Pull request by dmatej**

### CODE REVIEW

**Comment by smillidge** [comment]
ok to test

**Comment by smillidge** [comment]
ok to test

**Comment by smillidge** [comment]
@Pandrex247 The Jenkins build is failing with a weird SSL error. Can you check the Jenkins server config.

**Comment by Pandrex247** [comment]
Jenkins was failing to get a JAR dependency. I've manually put it in, so hopefully should work now.

**Comment by smillidge** [comment]
ok to test

**Comment by smillidge** [comment]
@Pandrex247 build is still broken on this pull request.
Failed to collect dependencies at org.glassfish:javax.faces:jar:2.2.10: Failed to read artifact descriptor for org.glassfish:javax.faces:jar:2.2.10: Could not transfer artifact org.glassfish:javax.faces:pom:2.2.10 from/to jvnet-nexus-promoted (https://maven.java.net/content/repositories/promoted/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]

https://jenkins.payara.co:8181/jenkins/job/payara-github/18/console 

Are we using OpenJDK on this box?

**Comment by dmatej** [comment]
It seems artifact is not present in any of Glassfish repositories (we use GF4 promoted, GF3, and GF4-snapshot), but it is in maven central:
http://mvnrepository.com/artifact/org.glassfish/javax.faces/2.2.10

**Comment by Pandrex247** [comment]
ok to test

**Comment by Pandrex247** [comment]
We're using Oracle JDK.

Not sure why it failed the second time, as I'd manually given it the pom and jar (and I haven't changed anything on the server since). Maven or network connection hiccup I assume.

**Pull request merged**
