### PR TITLE
FISH-992 Be able to use default values in data source definitions when translating values #5079

### PR DESCRIPTION
**Pull request by cfiguera**
## Description

This is a PR for feature request #5079.

When declaring database connections using the <data-source> descriptor in web.xml, we can use environment variables using ${ENV=xxxxx} or MicroProfile properties through ${MP_CONFIG=xxxxx}.

Right now the existing behavior is that if the environment variables are not setted, the application is not deployed due to a database connection error. There are many projects where, for example, the database schema is never modified or test environments where we want non-secret values to be used by default if the environment variables are not setted (i.e: admin/admin).

That is why I think it's interesting to be able to set default values, if the environment variables are not informed, to simplify the deployment of applications especially in local or test environments. This default value could be declared after a colon, as other programming languages do.

### New tests
TranslatedValueTest.java

### Testing Environment

- **Payara Version**: 5.2020.8-SNAPSHOT
- **Edition**: Full
- **JDK Version**: 8u271 - Oracle
- **Operating System**: Ubuntu 18.04
- **Database**: Postgres 9.6

### CODE REVIEW

**Comment by AlanRoth** [comment]
Hi @cfiguera,

Thank you for the PR, we're happy to receive your contribution, before we can proceed you will need to sign the CLA and send it to us.

https://github.com/payara/Payara/blob/master/PayaraCLA.pdf

Thank you,
Alan

**Comment by cfiguera** [comment]
Hi @AlanRoth,

I signed and sended the CLA on December 30th, maybe an error occurred.
Do you want I resend it now?

Carles

**Comment by AlanRoth** [comment]
Hi @cfiguera,

I'm double-checking with @smillidge as he is the only one who can confirm CLAs, our records may be out of date due to the holidays.

Sorry for the inconvenience and thank you for your patience :)
Alan

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by cfiguera** [comment]
Hi @AlanRoth ,
My tests failed because I used the environment variable $USER as part of the tests and Jenkins doesn't seem to set this variable. I'm going to fix it.

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by cfiguera** [comment]
Hi @AlanRoth,

It seems like in pipeline there is no environment variables. `System.getenv().entrySet().stream().findAny()` is empty
I going to remove part of the tests.

**Comment by AlanRoth** [comment]
Hi @cfiguera,

Jenkins is finicky about environment variables, you may be able to set them in maven - last I remember that worked. However, it may be best to remove them just to make sure they don't break in the future.

**Comment by AlanRoth** [comment]
jenkins test please

**Comment by cfiguera** [comment]
No idea what happened now... @AlanRoth

**Comment by cfiguera** [comment]
Yes, but I can't see more details from asserts, @AlanRoth .
I can't resolve the tests failures because I have no failures on local environment

**Comment by AlanRoth** [comment]
Hi @cfiguera, I'm not sure how to proceed, @lprimak any ideas?

**Comment by lprimak** [comment]
jenkins test

**Review by lprimak — APPROVED** [review]

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by cfiguera** [comment]
Thanks @lprimak. I saw habitat initialization was missing but I had no idea how to initialize it... Thanks a lot for the help!

**Pull request merged**
