### PR TITLE
FISH-743 Upgrade to HK2 2.6.1.payara-p4

### PR DESCRIPTION
**Pull request by jGauravGupta**
This is a fix, addressing the Github issue https://github.com/payara/Payara/issues/4952

## Depends on 
https://github.com/payara/patched-src-hk2/pull/17
https://github.com/payara/patched-src-hk2/pull/18
https://github.com/payara/Payara_PatchedProjects/pull/345

### Testing Performed
OpenAPI TCK and Unit tests

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Review by MarkWareham — APPROVED** [review]

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by MeroRai** [comment]
@jGauravGupta test failed as the PR to the Patched projects has not been merged.

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Pull request merged**
