### PR TITLE
QA-3 Sonar PR analysis

### PR DESCRIPTION
**Pull request by MarkWareham**
Adds sonar analysis to the (PR) Jenkinsfile. Webhooks already configured, so once this has been merged to master all subsequent PRs should be decorated with sonar reports

### CODE REVIEW

**Comment by MarkWareham** [comment]
No point doing a Jenkins test here as in this PR it will use the master Jenkinsfile, not the PR Jenkinsfile

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
```
java.lang.NullPointerException
    at org.eclipse.jgit.lib.ObjectIdOwnerMap.get (ObjectIdOwnerMap.java:138)
    at org.eclipse.jgit.revwalk.RevWalk.parseAny (RevWalk.java:888)
    at org.eclipse.jgit.revwalk.RevWalk.parseCommit (RevWalk.java:800)
    at org.sonarsource.scm.git.GitScmProvider.prepareTreeParser (GitScmProvider.java:196)
    at org.sonarsource.scm.git.GitScmProvider.branchChangedFiles (GitScmProvider.java:90)
    at org.sonar.scanner.scm.ScmChangedFilesProvider.loadChangedFilesIfNeeded (ScmChangedFilesProvider.java:70)
    at org.sonar.scanner.scm.ScmChangedFilesProvider.provide (ScmChangedFilesProvider.java:50)
```

**Comment by MarkWareham** [comment]
Jenkins test please

**Pull request merged**
