### PR TITLE
PAYARA-733 Add capability to output logs in JSON format

### PR DESCRIPTION
**Pull request by savage-engineer**
Initial version for a JSON Log Formatter.
Stick with the JSONObjectBuilder or no?

### CODE REVIEW

**Comment by savage-engineer** [comment]
jenkins test please

**Comment by smillidge** [comment]
I don't like the javaee 7 dependency creeping into nucleus. Either move the formatter into its own module in appserver or lose the JavaEE 7 api dependency

**Comment by savage-engineer** [comment]
Will aim to drop the JavaEE dependency.

**Comment by savage-engineer** [comment]
jenkins test please

**Comment by savage-engineer** [comment]
jenkins test please

**Pull request merged**
