### PR TITLE
FISH-6816 FISH-6967 Merge Payara6 into master

### PR DESCRIPTION
**Pull request by Pandrex247**
## Description
Merges Payara6 into the master branch.

### Blockers
Test repos need adjusting - none of the recent changes for Jenkins have been ported to the respective Payara6 branches.

https://github.com/payara/patched-src-javaee7-samples/pull/83
https://github.com/payara/patched-src-javaee8-samples/pull/29
https://github.com/payara/cargotracker/pull/32
https://github.com/payara/MicroProfile-TCK-Runners/pull/200

The weekly JakartaEE TCK run job also needs adjusting: https://github.com/payara/jenkinsjobs/pull/155

### New tests
None

### Testing Performed
Started the domain, ran Payara samples.
Started Payara Micro.

Jenkins test please pending...
TCKs pending...

### Testing Environment
Windows 11, Zulu JDK 11
WSL OpenSUSE 15.4, Zulu JDK 11

## Documentation
N/A

## Notes for Reviewers
~Currently investigating the version substitution not working for Payara Micro. This is not introduced by this branch, it's also present on master (not on 5.2022.5 tag so must be a recent change).~
Fixed, see commits for FISH-6967:
* https://github.com/payara/Payara/pull/6153/commits/62f70869d3d7c7e43983049fd9eefb6d5875dc17
* https://github.com/payara/Payara/pull/6153/commits/7b8a1839bd93b5eb33ce711979899116ec53de8e

### CODE REVIEW

**Comment by Pandrex247** [comment]
Force push was me fixing the names of the last two commits: 69**6**7 - should have worn my glasses rather than my contacts.

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Pull request merged**
