### PR TITLE
PAYARA-1450 Updated Jersey version to latest

### PR DESCRIPTION
**Pull request by Cousjava**
for 4.1.1.172

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by smillidge** [comment]
I think this requires a later HK2. Can you check?

**Comment by Cousjava** [comment]
It does require a later hk2, updated version for that as well, amended commit

**Comment by smillidge** [comment]
jenkins test please

**Comment by Cousjava** [comment]
needs PAYARA-1402 before it will work.

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
DO NOT MERGE until release of HK2 is finalized
See #1393 PAYARA-1402

**Comment by mulderbaba** [comment]
@Cousjava #1393 is building ok now, you can move on.

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
@Cousjava I fixed conflict errors but this still needs attention as there is compilation errors on tests.

**Pull request closed without merging**
