### PR TITLE
FISH-6067 Upgrade Jackson 2.12.4 -> 2.12.6

### PR DESCRIPTION
**Pull request by MarkWareham**
## Description
This is a dependency update

relates to #5641

### CODE REVIEW

**Comment by MarkWareham** [comment]
Jenkins test please

**Comment by kalinchan** [comment]
Copyright header needs updating

**Comment by MarkWareham** [comment]
A version number change doesn't require copyright

**Comment by MarkWareham** [comment]
Linked issue is different branch

**Comment by Pandrex247** [comment]
> A version number change doesn't require copyright

Says who? Strictly it does I think

**Comment by Pandrex247** [comment]
Also this should be coming from your own fork - don't push branches to the main repo for things like this please.

**Review by Pandrex247 — APPROVED** [review]

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
