### PR TITLE
PAYARA-2442 H2 jdbc-connection-pool config

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
On of the quick look tests fail:

```
   [testng] FAILED: test
   [testng] java.lang.AssertionError: Unexpected Results expected:<true> but was:<false>
   [testng] 	at test.CmpRosterTestNG.test(CmpRosterTestNG.java:102)
   [testng] ... Removed 26 stack frames
   [testng] 
   [testng] ===============================================
   [testng]     ejb_cmp_ear
   [testng]     Tests run: 1, Failures: 1, Skips: 0
   [testng] ===============================================
```

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by jGauravGupta** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
