### PR TITLE
PAYARA-2256 Remove Derby from Payara Micro

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by ggam** [comment]
Just curiousity, which advantages will h2 provide over Derby? Wasn't Derby already run in-memory?

**Comment by jGauravGupta** [comment]
Yes, Derby run in-memory, but performance is main reason for switch.

**Comment by jGauravGupta** [comment]
Jenkins quick test Payara 5 please

**Comment by ggam** [comment]
Have you performed some kind of benchmark? H2 is usually said to be more performant but it's difficult to find independent measurements.

**Comment by smillidge** [comment]
Neither should be used in production they are there because a default datasource is required by JavaEE. H2 is small and Derby relatively large.

**Comment by jGauravGupta** [comment]
Jenkins quick test Payara 5 please

**Comment by Cousjava** [comment]
Jenkins quick test Payara 5 please

**Comment by jGauravGupta** [comment]
Jenkins quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins quick test Payara 5 please

**Pull request merged**
