### PR TITLE
PAYARA-2784 Session passivation no working for session file persistence type - Payara4

### PR DESCRIPTION
**Pull request by MarkWareham**

### CODE REVIEW

**Comment by arjantijms** [comment]
jenkins quick test payara 4

**Comment by arjantijms** [comment]
jenkins quick test payara 4 jdk7

**Comment by arjantijms** [comment]
jenkins quick test payara 4 jdk7

**Comment by Pandrex247** [comment]
jenkins quick test payara 4 jdk7

**Pull request merged**
