### PR TITLE
PAYARA-1731-Upgrade-Grizzly-to-2.3.31

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by adamdva** [comment]
I think the grizzly version is also specified in one of the assembly py files

**Comment by mulderbaba** [comment]
@adamdva thanks for pointing out, sent another commit for the fix.

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Pull request merged**
