### PR TITLE
PAYARA-3031 HTTP/2 Trailer Issue

### PR DESCRIPTION
**Pull request by MattGill98**
Depends on: https://github.com/payara/Payara_PatchedProjects/pull/213.

Needs fairly rigorous testing.

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by arjantijms** [comment]
@MattGill98 
>Needs fairly rigorous testing.

How do you propose to test this change? Add a series of tests to e.g. EE 8 samples?

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by MattGill98** [comment]
@arjantijms I would recommend investigating the possibility of an extension to the HTTP/2 test that just adds trailers and checks they all go through. Also if anyone notices general Grizzly problems either manually or in Jenkins (you know the classics) then let me know!

**Pull request merged**
