### PR TITLE
FISH-5662 Integration of security connectors (2nd attempt)

### PR DESCRIPTION
**Pull request by OndroMih**
This adds back the exact same changes in the following PRs that were reverted by #5351:

* #5265 
* #5338 
* #5336

No fix was required for the failing DI TCK issues, they are fixed by adjusting the TCK porting package: https://github.com/payara/ditck-porting/pull/7

### CODE REVIEW

**Comment by OndroMih** [comment]
Jenkins test please

**Comment by OndroMih** [comment]
Jenkins test please

**Review by cubastanley — APPROVED** [review]

**Review by pdudits — APPROVED** [review]

**Comment by OndroMih** [comment]
Jenkins test please

**Comment by OndroMih** [comment]
Jenkins test please

**Pull request merged**
