### PR TITLE
PAYARA-3110 Made TracedInterceptor serializable

### PR DESCRIPTION
**Pull request by Cousjava**
This resolves a warning when persisting session scoped beans

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by svendiedrichsen** [comment]
@Cousjava You could keep the TracedInterceptor serializable if you don't inject the BeanManager but use CDI.getBeanManager() whenever the BeanManager is needed.

**Comment by arjantijms** [comment]
@smillidge @Cousjava @svendiedrichsen 

The concern regarding the bean manager is addressed by section 6.6.3 of the CDI spec:

> the built-in beans of type Instance, Event, InjectionPoint and BeanManager are passivation capable dependencies.

See https://docs.jboss.org/cdi/spec/2.0-PFD/cdi-spec.html#passivation_capable_dependency

**Pull request merged**
