### PR TITLE
FISH-6979 Add support for RSA-OAEP-256 for MP JWT 2.1

### PR DESCRIPTION
**Pull request by arieki**
## Description

The changes include upgrading MP JWT to 2.1

### Blockers

mp jwt tck 2.1 - https://github.com/payara/MicroProfile-TCK-Runners/pull/204

### Testing Performed

Build server and run MP JWT TCK

### Testing Environment

Windows 11, OpenJDK11, Maven 3.8.4

## Documentation

N/A

## Notes for Reviewers

N/A

### CODE REVIEW

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Review by Pandrex247 — APPROVED** [review]
LGTM.

That failure in MicroProfile Metrics is reproducible for me, but I don't think that's anything to do with your PR.

**Comment by arieki** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Pull request merged**
