### PR TITLE
[FISH-1289 QACI-579] fix race condition with duplicate initialization of Micro ports

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Bug fix. Removes duplicate HTTP ports from Payara Micro. Fixes race condition on startup that causes duplicate ports.

## Testing
Fixes Payara Micro Arquillian tests suites along with the release of Connectors 2.4.1

### Testing Performed
MP TCK

## Notes for Reviewers
As usual, use "ignore white space changes"

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Review by Pandrex247 — APPROVED** [review]
LGTM

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test

**Pull request merged**
