### PR TITLE
PAYARA-3196 Upgrade grizzly-npn to 1.8.1 for JDK 8u191

### LINKED ISSUE #3284: TLS fails with jdk 8u191
# TLS connections fail with oracle jdk 8u191 #
----------

TLS connections (for example: https-listener, jdbc connection pool using tls (mysql/postgresql)) fail using oracle jdk 8u191. No problems when using 8u181.

## Expected Outcome
```
curl --insecure https://localhost:8181
```
should present the payara index page.

## Current Outcome
curl return an error. Payara logs the following stack trace:
```
[2018-10-17T15:20:32.654+0200] [Payara 5.183] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=94 _ThreadName=http-thread-pool::http-listener-2(1)] [timeMillis: 1539782432654] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:862)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:245)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1077)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:1017)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:1014)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1497)
        at org.glassfish.grizzly.ssl.SSLUtils.executeDelegatedTask(SSLUtils.java:250)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:683)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:598)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:310)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
]]

```
## Steps to reproduce
1 - `export JAVA_HOME=/path/to/oracle-jdk8u191`
2 - `./asadmin start-domain payaradomain`
3 - `curl --insecure https://localhost:8181/`

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: Oracle jdk 8u191
- **Operating System**: Linux

### PR DESCRIPTION
**Pull request by Cousjava**
fixes #3284

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by smillidge** [comment]
Do we need to add to the release notes that ONLY u191 now works?

**Comment by johnmanko** [comment]
Should all grizzly-npn artifacts be replaced?   I found the following:

`glassfish/lib/grizzly-npn-bootstrap.jar`
`glassfish/modules/grizzly-npn-osgi.jar`

I know definitely bootstrap, but how about osgi?  Also, the API wasn't found in payara.

[Grizzly NPN Bootstrap 1.8.1](https://mvnrepository.com/artifact/org.glassfish.grizzly/grizzly-npn-bootstrap/1.8.1)
[Grizzly NPN OSGi 1.8.1](https://mvnrepository.com/artifact/org.glassfish.grizzly/grizzly-npn-osgi/1.8.1)
[Grizzly NPN API 1.8.1](https://mvnrepository.com/artifact/org.glassfish.grizzly/grizzly-npn-api/1.8.1)

**Comment by MattGill98** [comment]
Hi @johnmanko,

No, only the bootstrap jar is required to be replaced.

Kind regards,

Matt

**Pull request merged**
