### PR TITLE
#385 (GLASSFISH-21371)

### PR DESCRIPTION
**Pull request by dteleguin**
Fix for Payara #385 and GLASSFISH-21371

### CODE REVIEW

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
Hi thanks for your contribution it is really appreciated. Can you send us a Signed Contributor as we can't pull your changes without one?

See https://github.com/payara/Payara/blob/master/Contributing.md

**Comment by smillidge** [comment]
Can you send over a signed CLA or shall I re-implement the fix directly?

**Comment by cargosoft** [comment]
Hi Steve,

I'd appreciate if you re-implement the fix (since it's trivial). I'm afraid signing a CLA will take some time due to vacations. Will you accept a CLA signed by our CEO/CTO, so that it covers all possible future contributions from our employees? Thx

**Comment by smillidge** [comment]
Yes a company wide CLA signed by the CEO is great.

**Comment by smillidge** [comment]
Superceded by #416

**Pull request closed without merging**
