### PR TITLE
Fixed  typo in path.

### PR DESCRIPTION
**Pull request by johnmanko**

### CODE REVIEW

**Comment by smillidge** [comment]
Thanks good catch

**Comment by johnmanko** [comment]
I seems like there are a lot of places where META-INF, WEB-INF, *.xml strings are defined.  I wouldn't mind consolidating all of those to a single definition some place.  If you're ok with that, I'll work on it.  Which class/interface should define all of those?  There is ` Payara/appserver/resources/resources-connector/src/main/java/org/glassfish/resources/api/ResourceConstants.java`, but I think the current ones defined in there will also have to be renamed to account for `WEB-INF`.  Perhaps move the definitions from ` Payara/appserver/resources/resources-connector/src/main/java/org/glassfish/resources/util/ResourceUtil.java` to `ResourceConstants.java`?

**Comment by cubastanley** [comment]
Jenkins test please

**Comment by pdudits** [comment]
@johnmanko, please check our [contribution guide](/payara/Payara/tree/master/.github/CONTRIBUTING.md), and fill out the CLA. 

Thanks for your contribution!

**Pull request merged**
