### PR TITLE
FISH-7262 : monitoring console using jQuery 3.6.1

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
Vulnerability on JQuery 1.2 < 3.5.0

### Blockers
Depends On: 

- https://github.com/payara/monitoring-console/pull/39 being merged
- monitoring-console 2.0.2 deploy on Nexus 

### New tests
None

### Testing Environment
Zulu JDK 11.0.11 on Windows 11 with Maven 3.8.4

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
See https://github.com/payara/monitoring-console/pull/39#pullrequestreview-1739551570

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by aubi — APPROVED** [review]
I verified it locally, so after solving the infrastructure stuff (where to publish the artifact + build), the PR is fine.

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by aubi** [comment]
Thank you, @eliotmartin

**Pull request merged**
