### PR TITLE
Fix of domainConfig argument, the index specified error.

### PR DESCRIPTION
**Pull request by kazuhira-r**
DomainConfig index specified in the start-up argument is, it seem to be wrong.

### CODE REVIEW

**Comment by smillidge** [comment]
ok to test

**Comment by smillidge** [comment]
Good Catch. We need a signed CLA https://github.com/payara/Payara/blob/master/PayaraCLA.pdf in order to pull your changes. Alternatively we will just make the change directly in the source. I would recommend signing the CLA if you want to contribute more changes.

Once again thanks

**Comment by kazuhira-r** [comment]
Your reply, thank you. @smillidge

I am sorry. I did not make a pre-condition of Contribute.
Now, because I can not decide to sign the CLA, this Pull Request is withdrawn.

I apologize trouble, I'm sorry.

**Comment by smillidge** [comment]
No problem. A CLA is common for many open source projects as it assigns copyright for your work to the project. We'll make the fix then.

**Pull request closed without merging**
