### PR TITLE
Unique IDs are kept based on the name of the EJB -

### PR DESCRIPTION
**Pull request by lprimak**
- facilitating rolling upgrade

This is another issue I have encountered with rolling updates.
When serializing / deserializing local EJB references within a web session, the unique IDs have to be the same (right now they are sorted by EJB name) .
This pull request is a solution for this problem.  Instead of sorted EJB index, a UUID chunk is used for unique ID of EJBs

Related ticket #455

### CODE REVIEW

**Comment by smillidge** [comment]
Hi Thanks for the pull request it's appreciated we need a signed CLA on file before we can merge any pull requests. Can you take a look at https://github.com/payara/Payara/blob/master/Contributing.md and get the CLA over to us.

Thanks

**Comment by smillidge** [comment]
jenkins test please

**Comment by lprimak** [comment]
CLA Done

**Comment by smillidge** [comment]
Thanks got it

**Comment by lprimak** [comment]
did some cleanup on this patch

**Comment by lprimak** [comment]
After some extensive testing, this request is causing sided facts in weld. Will re-request when this is fixed.

**Comment by lprimak** [comment]
Ahhh, Weld...  The issue turned out to be unrelated to the fix. Reopening the pull request with enhancements

**Comment by lprimak** [comment]
Last commit... I promise :)

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
I'm afraid it's not the last commit. Can you add the comment
// Portions Copyright [2016] [C2B2 Consulting Limited and/or its affiliates]

to each of the changed files. This is a requirement of the upstream Oracle CDDL license.

Also can you let us know the symptoms of the problem you are solving so we can reproduce and create a test for the situation.

Thanks for your help

**Comment by lprimak** [comment]
I don't think these test failures are due to the current fix.
Please verify

**Comment by smillidge** [comment]
yeah I think you are right. We'll look into it.

**Comment by lprimak** [comment]
As far as the symptoms of the problem, it's all related to #455 rolling application upgrades without session loss.  Without this fix, when, for example adding @Stateless session bean to a new version of the app, the uniqueId for the all the beans get changed, and inevitable errors with serialization of the bean references lead to session loss.
With this fix, the uniqueIDs remain as stable as possible, so the session loss occurs only if a very drastic change to the application happens, which is a rare case.

Here is an example of the exception:

```
[2016-01-14T09:54:38.134-0500] [Payara 4.1] [WARNING] [AS-WEB-HA-00005] [javax.enterprise.web.ha] [tid: _ThreadID=7456 _ThreadName=ajp-listener-1(5)] [timeMillis: 1452783278134] [levelValue: 900] [[
  Exception occurred in getSession
java.io.IOException
	at com.sun.enterprise.container.common.impl.util.GlassFishObjectInputStream.resolveObject(GlassFishObjectInputStream.java:112)
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1399)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at java.util.HashMap.readObject(HashMap.java:1396)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at java.util.HashMap.readObject(HashMap.java:1396)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.catalina.session.StandardSession.readRemainingObject(StandardSession.java:2079)
	at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1987)
	at sun.reflect.GeneratedMethodAccessor1390.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.catalina.session.StandardSession.deserialize(StandardSession.java:1274)
	at org.apache.catalina.session.StoreBase.readSession(StoreBase.java:296)
	at org.glassfish.web.ha.session.management.ReplicationStore.getSession(ReplicationStore.java:567)
	at org.glassfish.web.ha.session.management.ReplicationStore.getSession(ReplicationStore.java:519)
	at org.glassfish.web.ha.session.management.ReplicationStore.loadFromBackingStore(ReplicationStore.java:433)
	at org.glassfish.web.ha.session.management.ReplicationStore.load(ReplicationStore.java:416)
	at org.apache.catalina.session.PersistentManagerBase.doSwapIn(PersistentManagerBase.java:1215)
	at org.apache.catalina.session.PersistentManagerBase.swapIn(PersistentManagerBase.java:1180)
	at org.glassfish.web.ha.session.management.ReplicationManagerBase.findSession(ReplicationManagerBase.java:161)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3223)
	at org.apache.catalina.connector.Request.getSession(Request.java:2891)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:920)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)
	at org.apache.shiro.web.servlet.ShiroHttpServletRequest.getSession(ShiroHttpServletRequest.java:147)
	at org.apache.shiro.web.servlet.ShiroHttpServletRequest.getSession(ShiroHttpServletRequest.java:188)
	at org.apache.shiro.web.session.mgt.ServletContainerSessionManager.createSession(ServletContainerSessionManager.java:108)
	at org.apache.shiro.web.session.mgt.ServletContainerSessionManager.start(ServletContainerSessionManager.java:64)
	at org.apache.shiro.mgt.SessionsSecurityManager.start(SessionsSecurityManager.java:121)
	at org.apache.shiro.subject.support.DelegatingSubject.getSession(DelegatingSubject.java:336)
	at org.apache.shiro.subject.support.DelegatingSubject.getSession(DelegatingSubject.java:312)
	at org.apache.shiro.mgt.DefaultSubjectDAO.mergePrincipals(DefaultSubjectDAO.java:204)
	at org.apache.shiro.mgt.DefaultSubjectDAO.saveToSession(DefaultSubjectDAO.java:166)
	at org.apache.shiro.mgt.DefaultSubjectDAO.save(DefaultSubjectDAO.java:147)
	at org.apache.shiro.mgt.DefaultSecurityManager.save(DefaultSecurityManager.java:383)
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:350)
	at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846)
	at org.apache.shiro.web.subject.WebSubject$Builder.buildWebSubject(WebSubject.java:148)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.createSubject(AbstractShiroFilter.java:292)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:359)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate$SerializableLocalObjectDelegate.createObject(EJBLocalObjectInvocationHandlerDelegate.java:161)
	at com.sun.enterprise.container.common.impl.util.GlassFishObjectInputStream.resolveObject(GlassFishObjectInputStream.java:95)
	... 118 more
]]
```

**Comment by smillidge** [comment]
jenkins test please

**Comment by davidweaver** [comment]
Is there a test case you have been using to verify your changes that we could integrate into our checks?

**Comment by lprimak** [comment]
> Is there a test case you have been using to verify your changes that we could integrate into our checks?

Ah... not easy.  Not sure this is doable in an automated test.

- Set up standalone instance in Payara, using Hazelcast session replication
- Set up Payara domain using Hazelcast session replication
- Patched Weld module (based on Weld 2.2.16.Final) https://github.com/weld/core/compare/2.2.16.Final...flowlogix:rolling-upgrade-patch-2.2.16

As stated in #455, I use the following commands:
```
asadmin deploy --availabilityenabled --property org.glassfish.ejb.container.application_unique_id=3604480 --contextroot my app --target inst1 --name my-website..version1
asadmin undeploy my-website..version1
asadmin deploy --availabilityenabled --property org.glassfish.ejb.container.application_unique_id=3604480 --contextroot my app --target inst1 --name my-website..version2

```
We use our production app for testing, but the basic app would contain the following:

- few @Stateless EJBs
- @SessionScoped bean that @Inject's (or @EJB) the @Stateless EJBs

The difference between versions is that one version has fewer or greater number @Stateless EJBs,
thus triggering the re-shuffling of the unique IDs.

**Comment by davidweaver** [comment]
Thanks

**Comment by davidweaver** [comment]
Payara Server is likely to move to Weld 2.3 in a forthcoming release.
Will this affect any of your patches? 

Is this change dependent on any outstanding Weld patches to be effective?

Are there likely to be any potential issues from patching Payara Server without having the associated Weld patches?

**Comment by lprimak** [comment]
This will not affect any of my patches, as they are largely independent.
There will be no sideffects if the Weld patches aren't present.
For rolling upgrades to work though, both this patch for EJBs and the Weld patch for CDI is needed.

I'll probably come out with a patch for Weld 2.3 when that's finished as well.
based on this: https://github.com/weld/core/compare/2.2.16.Final...flowlogix:rolling-upgrade-patch-2.2.16
as it should slide right into weld 2.3

**Comment by davidweaver** [comment]
Thanks for all your help with this.
It is anticipated that this will be included in the Payara Server 4.1.1.162 release in early May.
If you find a problem with the snapshot before then, please let me know.

**Comment by lprimak** [comment]
Thank you for all your help David as well, and will keep an eye on it.

**Comment by lprimak** [comment]
Is it easy/ difficult to upgrade existing Payara to Weld 3?
Looks like the Weld folks will be integrating the rolling update fix into that version and they want to test it

https://github.com/weld/core/pull/1300

**Comment by smillidge** [comment]
Weld 3 is Java EE 8 CDI 2.0 so I don't know how easy or hard it would be to integrate. It would need to be in a Payara 5.0 branch though as it can't come into the 4.x branch.

**Pull request merged**
