### PR TITLE
FISH-765 #4653 Propagate VirtualServer config to WebModule

### PR DESCRIPTION
**Pull request by sgflt**
## Description
This a bug fix to fix the issue described in #4653

### Testing Performed

Manual verification of result and "mvn clean verify -pl :web-glue"

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
@sgflt if this fails, can you please re-merge master and re-push this PR?
thank you

**Review by lprimak — APPROVED** [review]

**Comment by lprimak** [comment]
Took me a bit to see what's going on, but looks like a nice refactoring and fixes the problem

**Comment by MattGill98** [comment]
Thank you for the contribution!

**Pull request merged**
