### PR TITLE
Payara 1578 incorporate improvements provided on usage of the smack api

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
@smillidge this obsoletes PR#1510 and containing commits from @Flowdalic. build is ok now.

**Comment by smillidge** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Pull request merged**
