### PR TITLE
PAYARA-3129 add dependencies for classes removed in JDK11

### PR DESCRIPTION
**Pull request by Cousjava**
With this PR Payara Micro works on JDK11 with the command
java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED -jar payara-micro.jar

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by smillidge** [comment]
I think this needs to be on a different branch. Adding these into 184 will just bloat it.

**Pull request merged**
