### PR TITLE
Fish-7776: adding last version of mp specs 6.1

### PR DESCRIPTION
**Pull request by breakponchito**
This is to add last version of specs for MP 6.1

### CODE REVIEW

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Pull request merged**
