### PR TITLE
FISH-6906 FISH-6299 FISH-6022 Unify Principals Returned from SecurityContext and HttpServletRequest

### PR DESCRIPTION
**Pull request by arieki**
## Description

This is a fix that broke MP JWT TCK test

### Blockers

N/A

### New tests

N/A

### Testing Performed

+ Build and run MP JWT TCK on local machine
+ [EE10 authentication, authorization, security TCK](https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-10-TCK/detail/JakartaEE-10-TCK/282/pipeline/)

### Testing Environment

Windows 11, OpenJDK11, Maven 3.8.4

## Documentation

N/A

## Notes for Reviewers

N/A

### CODE REVIEW

**Comment by arieki** [comment]
jenkins test please

**Review by pdudits — APPROVED** [review]
We've seen that it works, I recommend adding more comments around that code given the uncertainty we've got around why is this :),

For example, I might have verified that the problem does not occur in `shouldRegisterSession` branch, but we should try again and check whether principals match e. g. by using `AccesTokenCallerPrincipal` from OpenID (e. g. in Payara Cloud API invocation via cli) -- I belive that one takes that branch.

And also a comment about how we believe that WebPrincipal is not relevant in context of Jaspic.

**Comment by arieki** [comment]
jenkins test please

**Comment by arieki** [comment]
jenkins test please

**Pull request merged**
