### PR TITLE
FISH-6399 Implement New Payara 6 Version Text in Header of Payara Server 6

### PR DESCRIPTION
**Pull request by jGauravGupta**
This PR adds Payara Major version to the top tool bar in the Web Admin console.
image

### CODE REVIEW

**Review by Pandrex247 — COMMENTED** [review]
Is there a reason we're only listing the major version?
I could find this info out by simply clicking on "About..."

**Comment by Pandrex247** [comment]
I query the point of this. Personally I think this is both redundant and ugly 😂

**Comment by diturner** [comment]
Ideally if the UI had a footer this kind of info would sit in there, unfortunately it doesn't so this is the compromise. 

Knowing how tricky this can be to edit I feel adding a whole footer for this would probably be uncalled for.

**Review by diturner — APPROVED** [review]

**Comment by jGauravGupta** [comment]
Hi @Pandrex247 , Initially discussion started with the updated Payara 6 logo (shows 6 version number) but later on agreed to add the version number to the top of the admin console page and keep the logo as Payara 5.

**Comment by jGauravGupta** [comment]
jenkins test please

**Pull request merged**
