### PR TITLE
PAYARA-2548 OpenAPI 1.0 Implementation Payara 4

### PR DESCRIPTION
**Pull request by MattGill98**

### CODE REVIEW

**Comment by arjantijms** [comment]
> Compilation failure
> [ERROR] /JenkinsWorkspace/JenkinsJobs/PayaraQuickBuild-JDK8/appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java:[141,62] method references are not supported in -source 1.7

**Comment by MattGill98** [comment]
jenkins quick test payara 4 please

**Comment by MattGill98** [comment]
jenkins quick test payara 4 please

**Comment by MattGill98** [comment]
jenkins quick test payara 4 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 4 JDK7 please

**Pull request merged**
