### PR TITLE
use patched Eclipselink

### PR DESCRIPTION
**Pull request by smillidge**

### CODE REVIEW

**Comment by Pandrex247** [comment]
ok to test

**Comment by Pandrex247** [comment]
ok to test

**Comment by dmatej** [comment]
What was patched?

**Comment by davewinters** [comment]
This eclipselink project is patched which addresses defect https://bugs.eclipse.org/bugs/show_bug.cgi?id=441546: org.eclipse.persistence.core

**Comment by smillidge** [comment]
Also https://github.com/payara/Payara/issues/239 is fixed by patching moxy

**Comment by davewinters** [comment]
Adding the jvm option below to the maven_opts in the jenkins system configurations fixed the build exception when pulling in the new jars  jars from the patched_projects repo  java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

 -Djavax.net.ssl.trustStore=/home/ec2-user/jdk1.7.0_71/jre/lib/security/cacerts

**Pull request merged**
