### PR TITLE
Merge branch 'master' into Payara-5

### PR DESCRIPTION
**Pull request by arjantijms**
Conflicts fixed:
	
```
        appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/ApplicationArchivist.java
	appserver/extras/embedded/web/pom.xml
	appserver/extras/payara-micro/payara-micro-distribution/pom.xml
	appserver/jdbc/pom.xml
	appserver/jms/gf-jms-connector/pom.xml
	appserver/packager/external/libpam4j/pom.xml
	appserver/packager/microprofile-package/pom.xml
	appserver/payara-appserver-modules/microprofile/config/pom.xml
	appserver/payara-appserver-modules/requesttracing-api/pom.xml
	appserver/pom.xml
	appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
	appserver/web/web-core/src/main/java/org/apache/catalina/LogFacade.java
	nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
	nucleus/payara-modules/nucleus-microprofile/config-service/pom.xml
	nucleus/pom.xml
```

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins quick test Payara 5 please

**Comment by Cousjava** [comment]
Jenkins quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins quick test Payara 5 please

**Comment by arjantijms** [comment]
@Cousjava test now passed, I forgot to do and merge a PR for the patched repo on which the merge depended. My bad, but it's done now ;)

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
