### PR TITLE
PAYARA-2453 Deployment Group upon Creation should be able to select available instance

### PR DESCRIPTION
**Pull request by MeroRai**

### CODE REVIEW

**Comment by MeroRai** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by MeroRai** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
