### PR TITLE
FISH-6607: Remove dependency on core-bom from payara-bom

### PR DESCRIPTION
**Pull request by pdudits**
## Description

Payara BOM should not depend on Payara Core BOM, as that one contains lots of internal information. The public dependencies from Core BOM has been copied to Payara BOM (most of them were already there).

Core BOM import moved into nucleus parent, which is next in inheritance hierarchy.

Identified few of the properties that core BOM used, but didn't actually define, they well still in root.

### CODE REVIEW

**Comment by pdudits** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Adjusting target branch to not alter in-progress release as it shouldn't break anything.
We can discuss next week what we think the BOMs should look like rather than making snap decisions in the heat of the moment.

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Needs rebase after altering branch target to not pull in extraneous commit

**Comment by pdudits** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]
LGTM.
Tried building core solo - still worked.
Eyeballing the payara-bom and payara-api boms - seem fine (alebit payara-api is missing a project `<url>` but we've got a separate issue for that).

**Pull request merged**
