### PR TITLE
FISH-662 MicroProfile Metrics 3.0 (MP 4.0)

### PR DESCRIPTION
**Pull request by jbee**
### Summary
This PR makes changes required to update implementation of MicroProfile Metrics to version 3.0 and pass its TCK.

Changes include:

* methods in `Metadata` changed (breaking), `Optional`s are now returned by property named methods, e.g. `unit()`, whereas `getUnit()` returns the value or a default value.
* `MetricRegistry` is now an interface
* `MetricRegistry` `getMetadata` is not included in the MP API (did exist in our implementation before)
* `MetricRegistry` got a new `getType()` method returning `base`, `vendor` or `application` 
* `MetricRegistry` got numerous new methods to get or create metrics, one group to support using `MetricID` arguments, another group (`gauge`) to support this operation for `Gauge`s which did not allow it directly before.
* `MetricRegistry` got numerous new methods to access metrics by their `MetricID` (or return null)
* all metrics are now considered _reusable_, therefore the flag got removed from all annotations, metadata and implementation
* global tags are no longer added within `MetricID` class but added explicitly during export
* `@Metric` is no longer used in the role to indicate registration of a metric producing method (in connection with `@Produces`) - it is now only used to `@Inject` a metric. Therefore most CDI fiddling could be removed.
* CDI sterotype handling is explicitly done in `AnnotationReader`
* `SimpleTimer` got a new `getMaxTimeDuration`, `getMinTimeDuration` and `getElapsedTime` methods
* `Timer` got new `getElapsedTime` method
* `Histogram` got new `getSum` method
* methods added to different metrics all added to both JSON and Open Metrics export formats of those metrics

Changes that could also be considered bug fixes:

* OpenMetrics export correctly computes seconds with fractions from `Duration` (would not consider sub seconds time before)
* JSON export does not include type nodes (e.g. `application`) if they have no child nodes 

### Testing
Because of the extended API of `MetricRegistry` many of our unit tests could now use the interface instead of requiring the implementation.

#### Updates to Unit Tests
Existing tests were extended to cover the newly added methods of metrics and the `MetricRegistry`.
Some tests were removed that were testing difference between _reusable_ and _not reusable_ metrics which no longer exists.
New test were added which are based on TCK tests that failed while our unit tests passed indicating untested feature.

#### Testing Performed
Testing was done with MP API and TCK RC-4 as updated for TCK runner in this PR https://github.com/payara/MicroProfile-TCK-Runners/pull/126

Build the community server and started it with:
```bash
export MP_METRICS_TAGS=tier=integration
asadmin start-domain
```
run the MP TCK (in same shell) using
```bash
 mvn clean install "-Ppayara-server-remote" "-Dpayara.version=5.2020.7-SNAPSHOT"
```

### Documentation
Relevant changes in MP Metrics can be found https://download.eclipse.org/microprofile/microprofile-metrics-3.0-RC3/microprofile-metrics-spec-3.0-RC3.html#release_notes_3_0

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by jbee** [comment]
jenkins test please

**Comment by MattGill98** [comment]
@cubastanley I've proposed disabling the fault tolerance TCK (which depends on Metrics). This will allow us to test the Metrics TCK with this PR, and the Fault Tolerance TCK can be enabled with its own upgrade. Have you any thoughts or objections?

Relevant test disabling PR is here: https://github.com/payara/MicroProfile-TCK-Runners/pull/129

**Comment by MattGill98** [comment]
jenkins test please

**Comment by jbee** [comment]
@MattGill98 @AlanRoth Looks like MP Metrics runs the wrong TCK version.

**Comment by MattGill98** [comment]
@jbee i haven’t upgraded the TCK again yet, I’m currently working on getting open tracing merged first

**Comment by MattGill98** [comment]
Can be tested once https://github.com/payara/Payara/pull/5002 is merged

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
This looks to be a race condition, I'm looking into it

**Comment by MattGill98** [comment]
jenkins test please

**Review by MattGill98 — APPROVED** [review]

**Comment by jbee** [comment]
:rocket:

**Pull request merged**
