### PR TITLE
PARAYA-2925 Background for admin console in IE is wrong colour

### PR DESCRIPTION
**Pull request by diturner**
Updated link to new suntheme.

### CODE REVIEW

**Comment by diturner** [comment]
Jenkins, quick test Payara 5 please

**Comment by Cousjava** [comment]
Jenkins test okease

**Comment by arjantijms** [comment]
jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Comment by Cousjava** [comment]
Jenkins test please

**Pull request merged**
