### PR TITLE
PAYARA-2940 Secure Admin Support Portal Fix- Payara4

### PR DESCRIPTION
**Pull request by MattGill98**
Maintenance PR of https://github.com/payara/Payara/pull/3390

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins quick test payara 4 please

**Comment by MattGill98** [comment]
jenkins quick test payara 4

**Comment by MattGill98** [comment]
Jenkins, quick test Payara 4 please

**Comment by MattGill98** [comment]
Jenkins, quick test Payara 4 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 4 please

**Comment by MeroRai** [comment]
Jenkins test please

**Pull request merged**
