### PR TITLE
CUSTCOM-284 Remove Expired Certificates

### PR DESCRIPTION
**Pull request by MattGill98**

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
Just playing around with the boundaries of the check to verify which parts of the log count for error checks

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Pull request merged**
