### PR TITLE
PAYARA-3406 Upgrade maven-bundle-plugin to 4.1.0 (Payara 4.x)

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Same failure again, Payara Minimal Distribution build is failing.

**Comment by jGauravGupta** [comment]
Payara Minimal Build is failing with org.glassfish.build:glassfishbuild-maven-plugin:3.2.20.payara-p1. 
Build passed after reverting it back to org.glassfish.build:glassfishbuild-maven-plugin:3.2.20.

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Pull request closed without merging**
