### PR TITLE
[FISH-1176] Test Failure - Instance Counter test stability

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Instance Counter test was failing under certain circumstances
It was depending on GC doing it's think within a certain timeframe, which was unreasonable.
Fixed it so the timing issues should not be a factor

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
