### PR TITLE
FISH-5686 Log warning when not running on a supported (LTS) JDK version

### PR DESCRIPTION
**Pull request by JamesHillyard**
## Description
Updated the current JDK checks to be up to date, checking the user is running an LTS JDK version. If they aren't a message will be printed in the console and a warning will be present in the logs, even if the Admin Console failed to start. A warning is also printed for Micro on startup (See images below)

### Testing Performed
Programmatically tested the logic works for the correct JDK versions. Manually tested the warnings are shown where appropriate.

### Testing Environment
Windows 10 Pro, JDK8/9, Maven 3.6.3

## Documentation
No documentation needed.

## Notes for Reviewers
_Starting the domain on JDK9_
image

_Admin Console warning_
image

_Payara Micro on Startup_
image

### CODE REVIEW

**Comment by JamesHillyard** [comment]
Jenkins test please

**Comment by kalinchan** [comment]
Missing some portions copyright headers.

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by rdebusscher — APPROVED** [review]
Looks good

**Pull request merged**
