### PR TITLE
PAYARA-1450 update jersey to version 2.25.1

### PR DESCRIPTION
**Pull request by Cousjava**
replaces #1386

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by Cousjava** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Pull request merged**
