### PR TITLE
PAYARA-3748-Upgrade-hazelcast-kubernetes-version-to-1.4

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by Pandrex247** [comment]
Needs confirming that this doesn't break the Kubernetes integration - Jenkins doesn't run any tests against this feature

**Comment by arjantijms** [comment]
@Pandrex247 

Mentioned he would be the most suited person to test this

**Comment by Pandrex247** [comment]
My test environment has been broken by the fact that kubernetes mandated that I update it, and has now broken itself: https://github.com/kubernetes/kubernetes/issues/73111

**Comment by lprimak** [comment]
this has been superceeded by Hazelcast 4

**Pull request closed without merging**
