### PR TITLE
PAYARA-3085 Support global configuration during application deployment

### PR DESCRIPTION
**Pull request by edthorne**
@smillidge I don't have a Github repo handy to reproduce the issue. I can however offer this PR as a solution. I've tested this locally and here's my understanding of the problem:

* During application deployment, the application's class loader has not yet been assigned.
* The application exists in the application registry during deployment.
* The check at `ConfigProviderResolverImpl:169` passes because the null class loader is passed to the `equals` method.
* The check at `ConfigProviderResolverImpl:202` attempts to pass the current loader to the application classloader's `equals` method, resulting in an NPE.

I've simply added a null check before calling `equals`. In hindsight, reversing the comparison to match line 169 would be sufficient to solve the problem.

### CODE REVIEW

**Comment by edthorne** [comment]
Related to #3085

**Comment by smillidge** [comment]
Thanks for the contribution with these changes does the deployment work?

**Comment by edthorne** [comment]
The deployment works as expected with the secrets mapped into files by the container and referenced in the `glassfish-resources.xml` contained in the WAR file using `${MPCONFIG=db_user}`.

As I was typing up the PR description, I noticed that the code could be further simplified to match a check earlier in the method. I thought I'd let the review decide if it needed to change and if my analysis was correct.

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by ischuraev** [comment]
I'd like to add another description how you could get a NPE in ConfigProviderResolverImpl:202. We experienced the NPE-problem in Payara 5.183 in combination with versioned applications.
The fix in this pull request solves the problem with NPE. In my opinion the "search in the app registry" in lines 200+ shouldn't be executed at all, at least in my case.

I'll try to describe steps to reproduce the problem here. If it is not enough, I can open a new issue with more details
1) All applications on the affected server are versioned.
2) Deployment of Applications. Restart of Payara-Server.
3) Call of JerseyClient ClientBuilder.newClient().get() in an application -> the call works.
4) redeployment of an application. It should not be the application from step 3.
5) repeat step 3. -> NPE in ConfigProviderResolverImpl:202

This NPE is not a problem anymore because this pull request fixed it. I think, that the real problem is in the lines 181-184
```
        } else {
            String appName = currentInvocation.getAppName();
            appInfo = applicationRegistry.get(appName);
        }
```
Our application has the name "cms:version". _appName_-variable is resolved to "cms" and _appInfo_ is _null_ as result. If we fill _appName_ with _currentInvocation.getRegistrationName()_ instead,  then _appInfo_ isn't _null_ anymore and in my case "_appInfo != null && appInfo.getAppClassLoader().equals(loader)_" equals to _true_.

**Pull request merged**
