### PR TITLE
FISH-320 Remove Hipchat Notifier

### PR DESCRIPTION
**Pull request by MattGill98**
Hipchat is no longer usable, so all the hipchat related code can be removed.

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by Cousjava** [comment]
The hipchat notifier could just be removed with any changes, as Hipchat is discontinued in all versions now.

**Comment by MattGill98** [comment]
@Cousjava issue has been rescoped, pleas review again

**Comment by MattGill98** [comment]
jenkins test please

**Review by Cousjava — APPROVED** [review]

**Pull request merged**
