### PR TITLE
rollbacked to the artefacts of 4.1.153 for getting WSIT enabled WS se…

### PR DESCRIPTION
**Pull request by mulderbaba**
rollbacked to the artefacts of 4.1.153 for getting WSIT enabled WS services running

### CODE REVIEW

**Comment by mulderbaba** [comment]
payara test please

**Comment by smillidge** [comment]
payara test please

**Comment by smillidge** [comment]
Should fix #493

**Comment by mulderbaba** [comment]
added PAX logging and looks like it resolves the issue with ClassNotFoundException on commons-logging. The commit should be in the same pull request with the previous commit of mine.

**Comment by smillidge** [comment]
what's the license for PAX logging?

**Comment by mulderbaba** [comment]
Apache License 2.0
https://github.com/ops4j/org.ops4j.pax.logging/blob/master/LICENSE.txt

**Comment by smillidge** [comment]
OK thanks. Does this indicate it's an OSGI issue?

**Comment by mulderbaba** [comment]
implicitly yes. I don't know the real reason behind why Metro guys bundled xmlsec.jar content with their own codebase (https://metro.java.net doesn't give any hints about the changelog for the artefacts) but loading those classes as an OSGI bundle demands the loading of apache commons-logging as an OSGI bundle too.

**Comment by danPowell52** [comment]
Flow Test Please

**Comment by smillidge** [comment]
Hi can you resolve the branch conflicts please

**Comment by mulderbaba** [comment]
done and pushed to mulderbaba/PAYARA-492 branch. please merge the pull request on Payara_PatchedProjects before merging this one.

**Comment by Pandrex247** [comment]
Cleaned up and resubmitted in #545

**Pull request closed without merging**
