### PR TITLE
Add support for default pincipal->group mapping #906 and PAYARA-936

### LINKED ISSUE #906: Provide default group to role mapping
Most of the time a 1:1 group to role with same name mapping is done and so the glassfish-web.xml could be avoided. 

This is already done by WildFly and is proposed for JSR 375 (Security API).

An option should be added to revert to the original behaviour where no automatic mapping is done.

### PR DESCRIPTION
**Pull request by lprimak**
added property default-role-mapping in glassfish-web.xml
Fixes #906 and PAYARA-936

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
PR #996

**Comment by OndrejM** [comment]
Hi @lprimak,

For glassfish-application.xml and glassfish-ejb-jar.xml, the new element <property> should be also added to their DTD, is that correct? I don't see the element in the [DTD for application.xml](https://github.com/payara/Payara/blob/master/appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-application_6_0-1.dtd).

**Comment by lprimak** [comment]
@OndrejM you are right.  I assumed that if it was in glassfish-web.xml it would be in the other two, I guess i was wrong

**Comment by lprimak** [comment]
jenkins test please

**Pull request merged**
