### PR TITLE
PAYARA-2148 Update version properties

### PR DESCRIPTION
**Pull request by Pandrex247**
Removes the _payara\_version_ and _payara\_update\_version_ properties, as we don't need them any more.

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by lprimak** [comment]
jenkins quick test payara 5

**Comment by lprimak** [comment]
jenkins quick test payara 5

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
