### PR TITLE
FISH-6718 Upgrade Build and Test Plugins

### PR DESCRIPTION
**Pull request by JamesHillyard**
## Description
Updates various components to newer versions.

### Blockers
None

### New tests
None

### Testing Performed
Compiled and started the server, created an instance and deployed application.

### Testing Environment
Windows 10, Maven 3.6.3, JDK 8

## Documentation
None

## Notes for Reviewers
None

### CODE REVIEW

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by arieki — APPROVED** [review]
LGTM

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Breaks generation of javadoc.

**Comment by JamesHillyard** [comment]
Jenkins test please

**Pull request merged**
