### PR TITLE
Minor improvements related to the usage of the Smack API

### PR DESCRIPTION
**Pull request by Flowdalic**

### CODE REVIEW

**Comment by Cousjava** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
Hi @Flowdalic thanks for your PR, awesome having the maintainer of Smack contributing!
Can you send us a signed CLA so we can merge your PR? See https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md

**Comment by Flowdalic** [comment]
CLA send

**Comment by smillidge** [comment]
Thanks we got the CLA.

**Comment by lprimak** [comment]
jenkins test please

**Comment by smillidge** [comment]
This is failing wrt to OSGI bundle requirements on boot. @mulderbaba can you take a look?

**Comment by mulderbaba** [comment]
@smillidge the packager structure that we have is need of defining the transitive dependencies. @Flowdalic omitted a couple of coming from smack-java7 but that results in absence of regarding artefacts, jxmpp-core and jxmpp-util-cache, in glassfish/modules directory.

**Comment by smillidge** [comment]
commits added via #1528

**Pull request closed without merging**
