### PR TITLE
PAYARA-1862 Wrappers for SQL should support JDBC 4.2

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by arjantijms** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins quick test payara 5

**Comment by arjantijms** [comment]
jenkins quick test payara 5

**Comment by jGauravGupta** [comment]
Sure, I will add JDBC 4.2 test case

**Pull request merged**
