### PR TITLE
PAYARA-3746-Upgrade-hazelcast-version-to-3.12

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by arjantijms** [comment]
jenkins test

**Comment by svendiedrichsen** [comment]
There is a code change in the Hazelcast lib which breaks the build:
```
09:05:17.940 [ERROR] /var/lib/jenkins/workspace/PayaraQuickBuildAndTest/nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java:[64,8] fish.payara.nucleus.hazelcast.MemberAddressPicker is not abstract and does not override abstract method getPublicAddress(com.hazelcast.instance.EndpointQualifier) in com.hazelcast.spi.MemberAddressProvider
```

**Comment by mulderbaba** [comment]
jenkins test

**Pull request merged**
