### PR TITLE
Payara 573 incorporate jsf 2.3

### PR DESCRIPTION
**Pull request by Pandrex247**

### CODE REVIEW

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by arjantijms** [comment]
@smillidge 

For integration with Payara and GlassFish, we've made a small SPI-like jar available that removes the necessity to add a FakeEndpoint as mentioned here: http://blog.payara.fish/jsf-2.3-the-websocket-quickstart-under-payara-server

It concerns this project: https://github.com/jsf-spec/mojarra/tree/master/spi/websocket-activation/tyrus

The idea is that integrators for a server that uses Tyrus either directly add the `tyrus-mojarra-activator` bundle to /modules, or if it better suits the target server use it as an example.

cc @BalusC

**Pull request merged**
