### PR TITLE
PAYARA-1945 Updated Payara 5 readme

### PR DESCRIPTION
**Pull request by arjantijms**
PAYARA-1945

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
Jenkins, quick test Payara 5 please

**Comment by Pandrex247** [comment]
I think there's an unrelated issue preventing this from passing, looking at the test log it's to do with OSGi.

**Pull request merged**
