### PR TITLE
FISH-6424 Concurrent CDI Extension Moved to Referential Implementation

### PR DESCRIPTION
**Pull request by aubi**
## Description
Glassfish team asked to backport CDI extension to the RI project. The RI part is here: https://github.com/eclipse-ee4j/concurrency-ri/pull/56 (already merged).
This PR is the Payara counterpart.

### Testing Performed
Payara samples/concurrency, Concurrency TCK

### Testing Environment
OpenJDK, Linux

### CODE REVIEW

**Comment by smillidge** [comment]
RC2 is on staging. Do you need it in maven Central?

**Comment by aubi** [comment]
No more changes are done, we can release RI 3.0.0. Then this PR can be tested and accepted.

**Comment by aubi** [comment]
Jenkins test please

**Comment by aubi** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by aubi** [comment]
Jenkins test please

**Pull request merged**
