### PR TITLE
FISH-391 OutOfMemoryError exception caused by OpenApi refactor

### PR DESCRIPTION
**Pull request by jGauravGupta**
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

## Description
This is a fix to discard HK2 types info after OpenAPI document creation. And with this fix, OpenAPI document creation is now performed after deployment of the application in a separate thread.

### Testing
Microprofile OpenAPI TCK
Microprofile  Fault-Tolerance TCK

### CODE REVIEW

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Review by MattGill98 — APPROVED** [review]
LGTM. What does the testing hang on?

**Comment by AlanRoth** [comment]
> 
> 
> LGTM. What does the testing hang on?

The beginning of Fault Tolerance. We've had the issue of FT hanging for maybe couple hours before, never a complete hang though

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Both Microprofile OpenAPI and Fault-Tolerance TCK passed.

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by MarkWareham** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Comment by jGauravGupta** [comment]
Jenkins test please

**Review by MattGill98 — APPROVED** [review]

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
@MarkWareham @Pandrex247 @jGauravGupta 

My understanding is that this branch currently contains the OpenAPI fix, the Grizzly revert and the ServerLogTest disable. With these 3 it should pass the tests - is that about right?

**Comment by jGauravGupta** [comment]
Yes @MattGill98 , You are right this PR contains all 3 mentioned changes.

**Comment by MattGill98** [comment]
jenkins test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Pull request merged**
