### PR TITLE
PAYARA-2060 Healthcheck Service Logs Warnings For CDI Eventbus

### PR DESCRIPTION
**Pull request by MattGill98**

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins quick test please

**Comment by MattGill98** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Can you prepend PAYARA-2060 to your commit please?
`git commit --amend -m PAYARA-2060 Moved stuck-thread remove call into correct method`

**Comment by MattGill98** [comment]
It should still work. The stuck thread store is always running and was the component producing the errors. The service just enables or disables the ability to check the store, which shouldn't affect the errors

**Pull request merged**
