### PR TITLE
PAYARA-3997 Add TLS 1.3 support when using Zulu JDK 8

### PR DESCRIPTION
**Pull request by MeroRai**
# Description
This is a feature to add TLS 1.3 support when using Zulu JDK 1.8_222 and higher. This possible due to OpenJSEE project, OpenJSEE is a JSEE provider created by Azul to support TLS 1.3 on Java SE 8. You can enable TLS 1.3 support with the Java option `--XX:+UseOpenJSSE`. See [TLS 1.3 Support in Zulu
8 with OpenJSSE](https://docs.azul.com/openjsse/index.htm) for more information.

# Important Info
- Implemented vendor specific JVM options, since TLS 1.3 is only supported in Zulu JDK. E.g. `[Azul-1.8.0u222|1.8.0u500]-XX:+UseOpenJSSE` this option will on included if the JDK vendor is Azul.
- The checkbox to enable TLS 1.3 should not be visible if you are using Zulu JDK lower 1.8_222 or JDK 8 provided by other vendors.
- You will need to add the following Java Options to the asadmin script for TLS 1.3 to work on the asadmin CLI:

    -  **-XX:+UseOpenJSSE** flag makes OpenJSSE default TLS provider
    - **-Dfish.payara.clientHttpsProtocol=TLSv1.3** 

# Testing

### New tests
None

### Testing Performed
* **Manual testing**
     * Enabled TLS 1.3 on admin-listener and enabled secure admin. Restarted the domain and checked if it is indeed using TLS 1.3 by going to developer tools in Chrome, clicking on the Security tab and view connection details. More information regarding this can be found here: https://support.cloudflare.com/hc/en-us/articles/227172348-Understanding-TLS-1-3.
    * Tested it on Windows and Elementary OS with Oracle, Azul Zulu JDK, AdoptOpenJDK, Red Hat OpenJDK and Amazon Corretto.
* **local build test**

### Testing Environment
Zulu JDK 1.8_222 on Elementary OS 0.4.1 Loki with Maven 3.5.4

# Documentation

TODO

# Notes for Reviewers

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by smillidge** [comment]
Can you describe the testing performed rather than just "manual testing"

**Comment by smillidge** [comment]
Have you tested the negative cases;
Does the option disappear when the underlying JVM does not support TLS 1.3?
Does the domain still start after your changes on a non-Zulu 8.x JVM?
Can you enable TLS 1.3 on JDK 11 OK?

Also 
Is there a PR to backport to 4.x as this is targeting master?

**Comment by MeroRai** [comment]
@smillidge I have now tested all the test cases you mentioned. In regards, to backport to 4.x, I have made a PR in BitBucket.

**Comment by MeroRai** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by smillidge** [comment]
I have concerns about the changes to the parsing of the versioned JVM parameters I think this needs extensive testing on a number of setups and JVMs to ensure there is not a raft of bug reports when this goes out.

**Comment by MeroRai** [comment]
jenkins test please

**Pull request merged**
