### PR TITLE
FISH-6669 Update Docker JDK Versions

### PR DESCRIPTION
**Pull request by JamesHillyard**
## Description
Update docker images to latest JDK versions

### Blockers
None

### New tests
None

### Testing Performed
Build docker images

### Testing Environment
Maven 3.6.3, JDK 8, Windows 10

## Documentation
None

## Notes for Reviewers
None

### CODE REVIEW

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by Pandrex247 — APPROVED** [review]

**Comment by JamesHillyard** [comment]
Jenkins test please

**Comment by JamesHillyard** [comment]
Jenkins test please

**Review by breakponchito — APPROVED** [review]
LGTM

**Pull request merged**
