### PR TITLE
PAYARA-693 fixes #729 do not override an existing system property

### LINKED ISSUE #729: Payara micro: setting SSL trustStore / keyStore manually
It seems that when deploying a WAR file in Payara Micro, the Java system properties `javax.net.ssl.trustStore` / `javax.net.ssl.keyStore` seem to be ignored in favour of a keystore and truststore within the payara-micro.jar itself. It would be great to be able to override these when required much as you can in full Payara or Glassfish domains.

### PR DESCRIPTION
**Pull request by smillidge**
Fixes #729

### CODE REVIEW

**Comment by MeroRai** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by MeroRai** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Pull request merged**
