### PR TITLE
Changed XMPP configuration variable

### PR DESCRIPTION
**Pull request by MattGill98**
Changed XMPP configuration variable named roomName to roomId and text from Name to ID.

### CODE REVIEW

**Comment by MattGill98** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
@MattGill98 so this makes [PR#1410](https://github.com/payara/Payara/pull/1410) obsolete?

**Comment by MattGill98** [comment]
It does, sorry I didn't check that PR before making mine! I think this PR covers all changes from  #1410  though.

**Comment by MattGill98** [comment]
Jenkins test please

**Comment by mulderbaba** [comment]
cool @MattGill98 I'm closing the other one, [PR#1410](PR#1410), then.

**Pull request merged**
