### PR TITLE
PAYARA-1780-healthcheck-configure-gives-errors-if-deprecated-option--notifierEnabled-is-missing

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by smillidge** [comment]
@mulderbaba can you resolve @MattGill98 comments.

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
@MattGill98 fixed

**Comment by MattGill98** [comment]
jenkins test please

**Comment by smillidge** [comment]
There seems to be some junk in the PR can you rebase?

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by mulderbaba** [comment]
jenkins test please

**Pull request merged**
