### PR TITLE
FISH-5898 Unable to deploy Jakarta EE 9.1 and Primefaces 10 application 

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Review by kalinchan — APPROVED** [review]
LGTM - Payara Builds and Reproducer deploys successfully.

**Review by Pandrex247 — APPROVED** [review]

**Comment by jGauravGupta** [comment]
jenkins tests please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by jGauravGupta** [comment]
jenkins test please

**Comment by ederks85** [comment]
Sorry if it is not the appropriate place to ask here, but can you provide any details on when this fix is going to be released in the payara-micro community edition?

**Comment by jGauravGupta** [comment]
Hi @ederks85 ,
[Payara Platform Community v5.2022.2](https://github.com/payara/Payara/releases/tag/payara-server-5.2022.2) is now available with the fix.

**Comment by JD-CSTx** [comment]
> Hi @ederks85 ,
> [Payara Platform Community v5.2022.2](https://github.com/payara/Payara/releases/tag/payara-server-5.2022.2) is now available with the fix.

It seems the fix isn't the final solution: https://github.com/payara/Payara/issues/5425#issuecomment-1110883205.

**Comment by ederks85** [comment]
Ok thanks @jGauravGupta and @JD-CSTx for the follow-up. I will keep monitoring the changes.

**Pull request merged**
