### PR TITLE
FISH-9098: fix for deployments caused by referenced resources from apps

### PR DESCRIPTION
**Pull request by breakponchito**
This is a fix to a reported bug caused by referenced resources used on app's
### Testing Performed

Manual testing on the server following described steps on the following tickets:

- https://payara.atlassian.net/browse/FISH-6659
- https://payara.atlassian.net/browse/FISH-9098

step 1: create instance and start:
image

step 2: create jdbc resource without assigned to an specific target
image

step3: deploy application to the instance created: clusterjsp and SimpleJndiLookup-1.0-SNAPSHOT

Observe components section for both:

image

image

step 4: Stop the instance and domain

step 5: Start the domain again, now you can't see any error during startup, this means the issue of the resource is fixed and if we look the Modules and Components for the applications we will see the details for it each application and both should look the same as previous test before to restart server:

image

image

### Testing Environment

Ubuntu 20.04, azul jdk 11, maven 3.8.6

### CODE REVIEW

**Comment by breakponchito** [comment]
Jenkins test please

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
This reintroduces FISH-6659

* Start the DAS
* Create an instance and start it
* Deploy clusterjsp **specifically to that instance**
* Observe that it lists various components e.g. `ClearSession`, `HaJsp`...
* Restart the **DAS**
* The components will no longer be shown

**Comment by breakponchito** [comment]
Jenkins test please

**Comment by breakponchito** [comment]
> This reintroduces FISH-6659
> 
> * Start the DAS
> * Create an instance and start it
> * Deploy clusterjsp **specifically to that instance**
> * Observe that it lists various components e.g. `ClearSession`, `HaJsp`...
> * Restart the **DAS**
> * The components will no longer be shown

I already fixed the issue now is maintaining the details of the components list without any issue on logs and the UI view

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
