### PR TITLE
Edit REST targets to point at new endpoints

### PR DESCRIPTION
**Pull request by Pandrex247**

### CODE REVIEW

**Comment by Pandrex247** [comment]
New Rest endpoints introduced in #1299

**Comment by mulderbaba** [comment]
jenkins test please

**Comment by OndrejM** [comment]
Is this something that needs to be documented?

**Comment by mulderbaba** [comment]
@OndrejM I guess not, are we documenting our REST endpoints? or just consuming them through Admin Console?

**Comment by OndrejM** [comment]
I think that documenting only the monitoring endpoints is important, therefore no, it's not necessary.

**Comment by smillidge** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
jenkins test please

**Pull request merged**
