### PR TITLE
PAYARA-1183 default web service realm configuration

### PR DESCRIPTION
**Pull request by lprimak**
added default EJB web service login configuration

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Pull request merged**
