### PR TITLE
ClassLoader delegation Fixes #419 and #431 PAYARA-677

### LINKED ISSUE #419: Enhancement: Create a FilteringClassLoader for EJB applications
Weblogic allows an application to specify classes to prefer to be loaded from jars in the EAR file before delegating to the parent classloader.

the relevent part of weblogic-application.xml looks like this:

    <prefer-application- packages >
        <package-name>org.apache.log4j.*</package-name>
        <package-name>antlr.*</package-name>
    </prefer-application-packages>

I'm looking for a similar feature in Glassfish/Payara for EJB applications.

Or, something similar to the glassfish-web.xml class-loader delegate="false" that could be specified in the glassfish-application.xml would also suffice.

### PR DESCRIPTION
**Pull request by lprimak**
Enabled by the following system property (Boolean - default = true):
`fish.payara.classloading.delegate` = false 

Also, enabled by `<classloading-delegate>false</classloading-delegate>`
in `META-INF/glassfish-application.xml` EAR descriptor

### CODE REVIEW

**Comment by OndrejM** [comment]
It akes sense to me to rename the system property to fish.payara.classloading.delegate=false, so that it is in line with the similar setting in glassfish-web.xml used with webapps.

**Comment by smillidge** [comment]
It would also be good if we can get it on a per deployment basis as well. It's a great first cut I also like Ondrej's suggested property name for consistency.

**Comment by lprimak** [comment]
Both good points. I'll take care of it.

**Comment by smillidge** [comment]
jenkins test please

**Comment by lprimak** [comment]
jenkins test please

**Comment by danPowell52** [comment]
jenkins test please

**Comment by Pandrex247** [comment]
Closing, as all of the commits have already been merged as a part of https://github.com/payara/Payara/pull/777

It's showing conflicts due to the fact that we squashed the commits in #777 when we merged them in.

**Pull request closed without merging**
