### PR TITLE
FISH-6009 hazelcast-kubernetes dependency now patched

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
After patching hazelcast-kubernetes dependency we need to update its version

### Blockers
None

### New tests
None

### CODE REVIEW

**Review by Pandrex247 — APPROVED** [review]

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Comment by luiseufrasio** [comment]
jenkins test please

**Pull request merged**
