### PR TITLE
PAYARA-1740 Deployment and initialization order for Payara 5

### PR DESCRIPTION
**Pull request by lprimak**

### CODE REVIEW

**Comment by smillidge** [comment]
There's a load of unrelated commits in that PR. Can you clean it up.

**Comment by lprimak** [comment]
The "unrelated" commits come from master.  They need to be merged into here before this can go any further.  They need to be there to make the stuff work.
This is the cleanest I could make it with the current state of Payara 5 branch.

**Comment by smillidge** [comment]
Can you rebase and redo?

**Comment by lprimak** [comment]
I'll try.  Arjan has merged master into the Payara branch now so this should go smoother

**Comment by lprimak** [comment]
@smillidge 
Ok, I was now able to do a clean PR.
Success!

**Pull request closed without merging**
