### PR TITLE
PAYARA-2465 fixes #2328 added in removed public constructor

### LINKED ISSUE #2328: Cannot run payara from Intellij IDEA
# Cannot run payara 5 Beta 2 from Intellij IDEA
----------

## Expected Outcome

Everything should work.

### Server
Waiting for payaradomain to start .....Error running admin process:
Message: java.lang.NoSuchMethodError: com.sun.enterprise.admin.util.AuthenticationInfo.<init>(Ljava/lang/String;Ljava/lang/String;)V Stack trace: com.intellij.javaee.process.common.JavaeeProcessUtilException: java.lang.NoSuchMethodError: com.sun.enterprise.admin.util.AuthenticationInfo.<init>(Ljava/lang/String;Ljava/lang/String;)V at com.intellij.javaee.process.common.MethodInvocator.invoke(MethodInvocator.java:47) at com.intellij.javaee.oss.process.JavaeeProcess.processRequest(JavaeeProcess.java:112) at com.intellij.javaee.oss.process.JavaeeProcess.run(JavaeeProcess.java:52) at com.intellij.javaee.oss.process.JavaeeProcess.main(JavaeeProcess.java:31) Caused by: java.lang.NoSuchMethodError: com.sun.enterprise.admin.util.AuthenticationInfo.<init>(Ljava/lang/String;Ljava/lang/String;)V at com.intellij.javaee.oss.glassfish.agent.Glassfish31Agent.getConnection(Glassfish31Agent.java:36) at com.intellij.javaee.oss.glassfish.agent.Glassfish3AgentBase.invoke(Glassfish3AgentBase.java:183) at com.intellij.javaee.oss.glassfish.agent.Glassfish3AgentBase.doConnect(Glassfish3AgentBase.java:39) at com.intellij.javaee.oss.agent.SimpleAgentBase$1.doJob(SimpleAgentBase.java:17) at com.intellij.javaee.oss.agent.SimpleAgentBase$1.doJob(SimpleAgentBase.java:13) at com.intellij.javaee.oss.agent.SimpleAgentJob.perform(SimpleAgentJob.java:12) at com.intellij.javaee.oss.agent.SimpleAgentBase.connect(SimpleAgentBase.java:25) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.intellij.javaee.process.common.MethodInvocator.invoke(MethodInvocator.java:41) ... 3 more

###Glassfish Log

[2018-01-26T13:24:24.071+0200] [Payara 5..Beta2] [SEVERE] [] [] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1516965861034] [timeMillis: 1516965864071] [levelValue: 1000] [[
  Error: URI=file:/Users/andrii.frunt/java/payara5/glassfish/lib/registration/servicetag-registry.xml Line=43: Document root element "registry", must match DOCTYPE root "null".]]

[2018-01-26T13:24:24.072+0200] [Payara 5..Beta2] [SEVERE] [] [] [tid: _ThreadID=29 _ThreadName=RunLevelControllerThread-1516965861034] [timeMillis: 1516965864072] [levelValue: 1000] [[
  Error: URI=file:/Users/andrii.frunt/java/payara5/glassfish/lib/registration/servicetag-registry.xml Line=43: Document is invalid: no grammar found.]]

## Steps to reproduce (Only for bug reports) 

1. Create an empty Maven WAR module
2. Deploy it to payaradomain 

## Environment ##

- **Payara Version**: 5 Beta 2
- **Edition**: Full
- **JDK Version**: 8 u152 - Oracle
- **Operating System**: Mac
- **Database**: 

screen shot 2018-01-26 at 1 32 05 pm

screen shot 2018-01-26 at 1 35 20 pm

screen shot 2018-01-26 at 1 36 53 pm

### PR DESCRIPTION
**Pull request by smillidge**

### CODE REVIEW

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Quick build and test passed!

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Pull request merged**
