### PR TITLE
FISH-1654: remove ConsoleHandler unless in verbose mode and fix logtoConsole property.

### PR DESCRIPTION
**Pull request by rdebusscher**
## Description
ConsoleHandler is always active but unless domain is started with --verbose option, there is no console to write the output to. Since ConsoleHandler.publish() is synchronized, it is a bottleneck in performance when multiple threads perform logging.

This PR also fixes the .logtoConsole logging property but it only has effect when running in verbose mode

There is no impact/change on Payara Micro and Payara Embedded.

**Important**

`./asadmin list-log-attributes` returns the 'active' state of the handlers attributes (so ConsoleHandler is not reported when not active)

When custom Docker Images are used, make sure the domain is started in verbose mode to have the output with `docker logs`.

### Testing Performed

- Running in verbose mode and non-verbose mode and tested logging from within application
- Verified ConsoleHandler is indeed not active in non-verbose mode
- Tested output of `list-log-attributes``
- Tested Docker image

### Testing Environment
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.4 with Maven 3.6.3

## Documentation

https://github.com/payara/Payara-Community-Documentation/pull/185

### CODE REVIEW

**Review by Pandrex247 — APPROVED** [review]

**Comment by Pandrex247** [comment]
Jenkins test please

**Comment by OndroMih** [comment]
Won't go into the next release.

**Comment by rdebusscher** [comment]
jenkins test please

**Comment by rdebusscher** [comment]
jenkins test please

**Pull request merged**
