### PR TITLE
ITOPS-2585 Update Jenkinsfile for New Engineering Jenkins Compatibility

### PR DESCRIPTION
**Pull request by JamesHillyard**
Updates the agent label and sets the maven version to allow PR testing on New Engineering Jenkins. This breaks old engineering jenkins PR testing.

### CODE REVIEW

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
Test Comment

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins Test Please

**Comment by JamesHillyard** [comment]
DevJenkins test please

**Comment by JamesHillyard** [comment]
DevJenkins Test

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
