### PR TITLE
PAYARA-1018 Changed thread pools default value to 2

### PR DESCRIPTION
**Pull request by michaelranaldo**

### CODE REVIEW

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by davidweaver** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test this branch

**Comment by michaelranaldo** [comment]
jenkins test this pull request

**Comment by michaelranaldo** [comment]
jenkins test this pull request

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by michaelranaldo** [comment]
Jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by smillidge** [comment]
jenkins test please

**Comment by michaelranaldo** [comment]
jenkins test please

**Pull request merged**
