### PR TITLE
Revert PAYARA-2354 and PAYARA-2303

### PR DESCRIPTION
**Pull request by lprimak**
The bug is actually in JMSContext, the fixes would have hidden this bug further,
so reverting these fixes

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test please

**Comment by lprimak** [comment]
Fix no longer applicable

**Comment by hmeerlo** [comment]
Ok, this has cost me some hours :-) @lprimak can you explain why this was reverted, because now the ConcurrentModificationException has returned for me (only under load).

**Comment by hmeerlo** [comment]
Never mind, must be caused elsewhere because the iterator construction is perfectly fine.

**Pull request merged**
