### PR TITLE
 PAYARA-2113 Made stop-domain a little more descriptive (P-5)

### PR DESCRIPTION
**Pull request by michaelranaldo**

### CODE REVIEW

**Comment by michaelranaldo** [comment]
jenkins quick test payara 5 please

**Comment by michaelranaldo** [comment]
jenkins quick test payara 5 please

**Comment by michaelranaldo** [comment]
jenkins quick test payara 5 please

**Comment by smillidge** [comment]
jenkins quick test payara 5 please

**Pull request merged**
