### PR TITLE
Prevent cpu wastage when not logging to file

### LINKED ISSUE #2942: Payara 5.182 Full stops responding to http-requests if only the console-Logger is activated in admin-panel
# Description #
----------
Payara 5.182 Full (fresh downloaded - no modifications) stops responding to Http-request after about 5000 requests (jmeter 20 threads in parallel) if only the console-Logger is activated and each requests logs one simple log-entry via java.util-Logging. If the file-logger and the console-logger or only the file logger is activated everything works just fine.

## Expected Outcome
The Server continues answering requests and writing logs

## Current Outcome
The server stops answering requests after about 5000 requests

## Steps to reproduce (Only for bug reports) 

1. Download fresh Payara 5.182  (build 303)
2. Deploy minimalistic REST-App: just two Classes: JaxRSConfiguration and one REST-Resource which logs one line with java.util.logging and returns Response 200.
3. Load Test with jmeter to the endpoint
4. After 5000 requests the server stops answering requests if only the console logger is activated. 

## Environment ##

- **Payara Version**:  5.182  (build 303)
- **Edition**: Full
- **JDK Version**: Oracle 1.8_171
- **Operating System**: Mac

### LINKED ISSUE #3506: Eating 100% CPU when setting com.sun.enterprise.server.logging.GFFileHandler.logtoFile=false
# Description #

Summary: I see a 100% CPU load on one CPU core when starting my application, due to a "RUNNABLE" thread.

When using https://github.com/payara/docker-payaraserver-full Docker image (using **Payara 5.183** and **OpenJDK 1.8.0u171**), the logging to file disabled via setting:
```
asadmin set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logtoFile=false
```
(See [Dockerfile](https://github.com/payara/docker-payaraserver-full/blob/43b62b2038b91c9a9072d20c65e23721967eb600/Dockerfile#L70)).

The application logs to console, which is just fine, but it is burning a CPU core infinitely.

I don't know if #2117 is related. Seems to be the only other issue I could find.

## Expected Outcome
The server should not be using a complete CPU core for logging...?

## Current Outcome
Top from container, see PID 100:
grafik

Related thread dump, with `nid=0x64` == PID 100:
```
dv> "GFFileHandler log pump" #27 daemon prio=5 os_prio=0 tid=0x00007fbedc175800 nid=0x64 runnable [0x00007fbef0ffd000]
dv>    java.lang.Thread.State: RUNNABLE
dv>     at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
dv>     at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
dv>     - locked <0x00000003dfc96488> (a java.io.OutputStreamWriter)
dv>     at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
dv>     at java.util.logging.StreamHandler.flush(StreamHandler.java:259)
dv>     - locked <0x00000003dfc963c8> (a com.sun.enterprise.server.logging.GFFileHandler)
dv>     at com.sun.enterprise.server.logging.GFFileHandler.log(GFFileHandler.java:960)
dv>     at com.sun.enterprise.server.logging.GFFileHandler$3.run(GFFileHandler.java:610)
```

## Steps to reproduce (Only for bug reports)

While the below stays to be a valid option for reproducing, @pioneer2k stated in payara/docker-payaraserver-full#72 this is even a problem when just starting the domain without even a deployment.

----
You should be able to reproduce by using my feature branch.
Docker, Maven and Git is assumed as installed:
```
git clone https://github.com/poikilotherm/dataverse -b 5292-small-container
mvn -Pcontainer clean package docker:build docker:run -DskipTests
```

Then enter the container via:
```
docker exec -it dataverse-1 /bin/bash
top -H
```
And watch it burn the CPU.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: OpenJDK 1.8.0u171
- **Operating System**: Linux/Docker

### PR DESCRIPTION
**Pull request by svendiedrichsen**
- only start pump thread if logging to file (prevents cpu wastage)
- Store into `pendingRecords` queue only if logging to file (prevents server freezing when queue full)
- draining the pending records if the pump thread gets disabled during server runtime

Fixes #3506 and https://github.com/payara/docker-payaraserver-full/issues/72
and may also fix #2942 
and might also be related to #2117

### CODE REVIEW

**Comment by mulderbaba** [comment]
jenkins test

**Comment by svendiedrichsen** [comment]
The GFFileHandlers property `flushFrequency` has a default value of 1. This results in LogRecords being written and flushed one at a time. This may cause some higher cpu usage when server is under load. Shouldn't this be some sensibly higher number by default. At least in the example `production` domain?

**Comment by rdebusscher** [comment]
I tried this patch out and it seems that it doesn't solve the issue. CPU still at 100%. I'll investigate more.

**Comment by svendiedrichsen** [comment]
@rdebusscher I have just rechecked and found that if I set `logtoFile` to `false` and starting a fresh domain from a freshly built server without any interactionwith the server:
- on MASTER cpu usage at 99% to 101%
- on this PRs branch cpu usage 0.5% to 1.5%

**Comment by svendiedrichsen** [comment]
@MattGill98 The reason why this problem comes up with the docker image 5.184 is this commit where the `logtoFile` property is set to `false`. https://github.com/payara/docker-payaraserver-full/commit/92e6c65dca4d65806bb128f33e0123193bb6536d

**Comment by rdebusscher** [comment]
@svendiedrichsen Don't know what went wrong (or is it due to your last commit), but the first time I tested your patch I had issues with the following scenario. (updating a running server)

```
./asadmin start-domain
-> CPU low
./asadmin set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logtoFile=false
-> CPU 100%
```

But now that seems to be ok.

Thx for your time to have a look at this issue.

**Comment by svendiedrichsen** [comment]
@rdebusscher You are welcome. But it is also in my best interest to see those bugs gone. ;)
> (or is it due to your last commit)
This was just merging the master changes into this branch. It had worked for me before.

**Comment by smillidge** [comment]
jenkins test please

**Comment by svendiedrichsen** [comment]
This test failed and does it irregularly with different PRs:
```
   [testng] FAILED: helloRemote
   [testng] javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.enterprise.naming.impl.SerialInitContextFactory [Root exception is java.lang.ClassNotFoundException: com.sun.enterprise.naming.impl.SerialInitContextFactory]
   [testng] 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:674)
   [testng] 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
   [testng] 	at javax.naming.InitialContext.init(InitialContext.java:244)
   [testng] 	at javax.naming.InitialContext.<init>(InitialContext.java:216)
   [testng] 	at test.ejb.remoteview.RemoteViewTestNG.helloRemote(RemoteViewTestNG.java:59)
   [testng] Caused by: java.lang.ClassNotFoundException: com.sun.enterprise.naming.impl.SerialInitContextFactory
   [testng] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
   [testng] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   [testng] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
   [testng] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   [testng] 	at java.lang.Class.forName0(Native Method)
   [testng] 	at java.lang.Class.forName(Class.java:348)
   [testng] 	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:72)
   [testng] 	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:61)
   [testng] 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:672)
   [testng] 	... 26 more
   [testng] ... Removed 22 stack frames
   [testng] SKIPPED: portableGlobal
   [testng] SKIPPED: nonPortableGlobal
```

**Comment by MarkWareham** [comment]
jenkins test please

**Pull request merged**
